In [1]:
import configparser
import os

import pandas as pd

In [ ]:
os.chdir('../')

In [2]:
dataset = 'all_noHypoHyper'

In [3]:
data = configparser.ConfigParser(interpolation=configparser.ExtendedInterpolation())
data.read('../data.ini')
data = data['DEFAULT']

In [4]:
mutations = pd.read_csv("../" + data[f'{dataset}___mutations'], sep="\t", comment='#')
mutations = mutations[['Hugo_Symbol', 'Tumor_Sample_Barcode']].rename(columns={'Hugo_Symbol': 'GeneSymbol', 'Tumor_Sample_Barcode': 'Sample'})

mutations_RAS = pd.read_csv("../" + data[f'{dataset}_RAS___mutations'], sep="\t", comment='#')
mutations_RAS = mutations_RAS[['Hugo_Symbol', 'Tumor_Sample_Barcode']].rename(columns={'Hugo_Symbol': 'GeneSymbol', 'Tumor_Sample_Barcode': 'Sample'})

mutations_nonRAS = pd.read_csv("../" + data[f'{dataset}_nonRAS___mutations'], sep="\t", comment='#')
mutations_nonRAS = mutations_nonRAS[['Hugo_Symbol', 'Tumor_Sample_Barcode']].rename(columns={'Hugo_Symbol': 'GeneSymbol', 'Tumor_Sample_Barcode': 'Sample'})

In [5]:
mutations

       GeneSymbol                     Sample
0            A1BG    coadread_dfci_2016_1231
1            A1BG    coadread_dfci_2016_1231
2            A1BG  coadread_dfci_2016_230737
3            A1BG    coadread_dfci_2016_2429
4            A1BG    coadread_dfci_2016_2624
...           ...                        ...
388628     GPR112            TCGA-T9-A92H-01
388629    DCAF8L2            TCGA-T9-A92H-01
388630     MAGEB1            TCGA-T9-A92H-01
388631        DMD            TCGA-T9-A92H-01
388632    CCDC120            TCGA-T9-A92H-01

[388633 rows x 2 columns]

In [6]:
clinicalSamples = pd.read_csv("../" + data[f'{dataset}___samples'], sep="\t", comment='#')
all_samples = clinicalSamples['SAMPLE_ID'].tolist()

In [7]:
pivot = mutations.pivot_table(index='GeneSymbol', columns='Sample', aggfunc='size', fill_value=0)
pivot = pivot.reindex(columns=all_samples, fill_value=0)

pivot_RAS = mutations_RAS.pivot_table(index='GeneSymbol', columns='Sample', aggfunc='size', fill_value=0)
pivot_RAS = pivot_RAS.reindex(columns=all_samples, fill_value=0)

pivot_nonRAS = mutations_nonRAS.pivot_table(index='GeneSymbol', columns='Sample', aggfunc='size', fill_value=0)
pivot_nonRAS = pivot_nonRAS.reindex(columns=all_samples, fill_value=0)

In [8]:
pivot

Sample,coadread_dfci_2016_207430,coadread_dfci_2016_1241,coadread_dfci_2016_3701,coadread_dfci_2016_3640,coadread_dfci_2016_1222,coadread_dfci_2016_345,coadread_dfci_2016_267922,coadread_dfci_2016_1212,coadread_dfci_2016_1791,coadread_dfci_2016_3321,...,TCGA-QG-A5YW-01,TCGA-QG-A5YX-01,TCGA-QG-A5Z1-01,TCGA-QG-A5Z2-01,TCGA-QL-A97D-01,TCGA-RU-A8FL-01,TCGA-SS-A7HO-01,TCGA-T9-A92H-01,TCGA-5M-AAT5-01,TCGA-5M-AATA-01
GeneSymbol,,,,,,,,,,,,,,,,,,,,,
A1BG,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A1CF,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A2M,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A2ML1,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
A3GALT2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11B,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ZYX,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
ZZEF1,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ZZZ3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
hsa-mir-150,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
pivot.to_csv("../" + data[f'maxmif___{dataset}___in'], sep="\t", index=True)
pivot_RAS.to_csv("../" + data[f'maxmif___{dataset}_RAS___in'], sep="\t", index=True)
pivot_nonRAS.to_csv("../" + data[f'maxmif___{dataset}_nonRAS___in'], sep="\t", index=True)