In [1]:
import configparser
import os

import pandas as pd

In [ ]:
os.chdir('../')

In [2]:
dataset = 'all_noHypoHyper'

In [3]:
data = configparser.ConfigParser(interpolation=configparser.ExtendedInterpolation())
data.read('../data.ini')
data = data['DEFAULT']

In [4]:
mutations = pd.read_csv("../" + data[f'{dataset}___mutations'], sep="\t", comment='#')
mutations_RAS = pd.read_csv("../" + data[f'{dataset}_RAS___mutations'], sep="\t", comment='#')
mutations_nonRAS = pd.read_csv("../" + data[f'{dataset}_nonRAS___mutations'], sep="\t", comment='#')

In [5]:
mutations

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,coadread_dfci_2016_1231,A1BG,A1BG,19,58862793,58862793,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100,8322,1,495
1,coadread_dfci_2016_1231,A1BG,A1BG,19,58862794,58862794,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100,8322,1,495
2,coadread_dfci_2016_230737,A1BG,A1BG,19,58858744,58858744,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100,8322,1,495
3,coadread_dfci_2016_2429,A1BG,A1BG,19,58862934,58862934,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100,8322,1,495
4,coadread_dfci_2016_2624,A1BG,A1BG,19,58858848,58858848,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.1351G>A,p.A451T,451.0,ENST00000263100,8322,1,495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388628,TCGA-T9-A92H-01,GPR112,GPR112,X,135428691,135428691,Silent,SNP,T,T,G,ENST00000370652.1:c.2826T>G,p.T942=,942.0,ENST00000370652,136094,1,3080
388629,TCGA-T9-A92H-01,DCAF8L2,DCAF8L2,X,27766401,27766401,Silent,SNP,T,T,C,ENST00000451261.2:c.1389T>C,p.F463=,463.0,ENST00000451261,158410,1,631
388630,TCGA-T9-A92H-01,MAGEB1,MAGEB1,X,30269452,30269452,Missense_Mutation,SNP,C,C,G,ENST00000378981.3:c.842C>G,p.T281S,281.0,ENST00000378981,8309,1,347
388631,TCGA-T9-A92H-01,DMD,DMD,X,32381009,32381009,Missense_Mutation,SNP,A,A,C,ENST00000357033.4:c.5221T>G,p.L1741V,1741.0,ENST00000357033,2241765,1,3685
388632,TCGA-T9-A92H-01,CCDC120,CCDC120,X,48923135,48923135,Missense_Mutation,SNP,G,G,A,ENST00000496529.2:c.833G>A,p.R278Q,278.0,ENST00000496529,16409,1,630

In [6]:
occurrences = mutations['Hugo_Symbol'].value_counts().reset_index()
occurrences_RAS = mutations_RAS['Hugo_Symbol'].value_counts().reset_index()
occurrences_nonRAS = mutations_nonRAS['Hugo_Symbol'].value_counts().reset_index()

In [7]:
occurrences

         Hugo_Symbol  count
0                TTN   1317
1                APC   1073
2               TP53    667
3              SYNE1    476
4              MUC16    470
...              ...    ...
18803         HRSP12      1
18804          HRCT1      1
18805          HOXB8      1
18806        HORMAD2      1
18807  RP11-998D10.1      1

[18808 rows x 2 columns]

In [8]:
hugo_to_entrez = pd.read_csv("../" + data['muffinn'] + '/hugo_symbol_to_entrez_id.csv', sep="\t")
hugo_to_entrez

         hugo_symbol entrez_id
0               A1BG         1
1               A1CF     29974
2                A2M         2
3              A2ML1    144568
4            A3GALT2    127550
...              ...       ...
18803          NBPF6    653149
18804         SDHAF1    644096
18805         GTF2H5    404672
18806            SCT      6343
18807  RP11-998D10.1       NaN

[18808 rows x 2 columns]

In [9]:
occurrences_entrez = occurrences.merge(hugo_to_entrez, left_on='Hugo_Symbol', right_on='hugo_symbol', how='left').rename(columns={'count': 'occurrences'})[['hugo_symbol', 'entrez_id', 'occurrences']]
occurrences_entrez_RAS = occurrences_RAS.merge(hugo_to_entrez, left_on='Hugo_Symbol', right_on='hugo_symbol', how='left').rename(columns={'count': 'occurrences'})[['hugo_symbol', 'entrez_id', 'occurrences']]
occurrences_entrez_nonRAS = occurrences_nonRAS.merge(hugo_to_entrez, left_on='Hugo_Symbol', right_on='hugo_symbol', how='left').rename(columns={'count': 'occurrences'})[['hugo_symbol', 'entrez_id', 'occurrences']]

In [10]:
occurrences_entrez

         hugo_symbol entrez_id  occurrences
0                TTN      7273         1317
1                APC       324         1073
2               TP53      7157          667
3              SYNE1     23345          476
4              MUC16     94025          470
...              ...       ...          ...
18803         HRSP12       NaN            1
18804          HRCT1    646962            1
18805          HOXB8      3218            1
18806        HORMAD2    150280            1
18807  RP11-998D10.1       NaN            1

[18808 rows x 3 columns]

In [11]:
occurrences_entrez[occurrences_entrez['entrez_id'].isna()]

          hugo_symbol entrez_id  occurrences
96              GPR98       NaN          139
102          KIAA1109       NaN          137
216            GCN1L1       NaN          107
222            PTCHD2       NaN          105
258             SOGA3       NaN          100
...               ...       ...          ...
18784      AC129492.6       NaN            1
18785          ZNF720       NaN            1
18799  CTD-2583A14.10       NaN            1
18803          HRSP12       NaN            1
18807   RP11-998D10.1       NaN            1

[1376 rows x 3 columns]

In [12]:
# TODO: remove na??
occurrences_entrez = occurrences_entrez[occurrences_entrez['entrez_id'].notna()]
occurrences_entrez_RAS = occurrences_entrez_RAS[occurrences_entrez_RAS['entrez_id'].notna()]
occurrences_entrez_nonRAS = occurrences_entrez_nonRAS[occurrences_entrez_nonRAS['entrez_id'].notna()]

In [13]:
occurrences_entrez[occurrences_entrez['entrez_id'].str.contains('|', regex=False)]

      hugo_symbol           entrez_id  occurrences
7677          TEC    7006 | 100124696           18
8866         MMD2  221938 | 100505381           15
12154         HBD    3045 | 100187828           10

In [14]:
# TODO: take first??
occurrences_entrez.loc[:,'entrez_id'] = occurrences_entrez['entrez_id'].apply(lambda x: x.split('|')[0])
occurrences_entrez_RAS.loc[:,'entrez_id'] = occurrences_entrez_RAS['entrez_id'].apply(lambda x: x.split('|')[0])
occurrences_entrez_nonRAS.loc[:,'entrez_id'] = occurrences_entrez_nonRAS['entrez_id'].apply(lambda x: x.split('|')[0])

In [15]:
occurrences_entrez = occurrences_entrez[['entrez_id', 'occurrences']]
occurrences_entrez_RAS = occurrences_entrez_RAS[['entrez_id', 'occurrences']]
occurrences_entrez_nonRAS = occurrences_entrez_nonRAS[['entrez_id', 'occurrences']]

In [16]:
occurrences_entrez

      entrez_id  occurrences
0          7273         1317
1           324         1073
2          7157          667
3         23345          476
4         94025          470
...         ...          ...
18801      8870            1
18802     25764            1
18804    646962            1
18805      3218            1
18806    150280            1

[17432 rows x 2 columns]

In [17]:
occurrences_entrez.to_csv("../" + data[f'muffinn___{dataset}___in'], sep="\t", index=False, header=False)
occurrences_entrez_RAS.to_csv("../" + data[f'muffinn___{dataset}_RAS___in'], sep="\t", index=False, header=False)
occurrences_entrez_nonRAS.to_csv("../" + data[f'muffinn___{dataset}_nonRAS___in'], sep="\t", index=False, header=False)