In [1]:
import configparser
import os

import numpy as np
import pandas as pd
from pyensembl import EnsemblRelease

In [2]:
os.chdir('../')

In [3]:
ensembl = EnsemblRelease(75)

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
data = configparser.ConfigParser(interpolation=configparser.ExtendedInterpolation())
data.read('data.ini')
data = data['DEFAULT']

## Giannakis

### Mutation

In [6]:
dataMutation_Giannakis = pd.read_csv(data['original___Giannakis___mutations'], sep='\t', engine='python', comment='#')

In [7]:
dataMutation_Giannakis

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,dbSNP_RS,dbSNP_Val_Status,Tumor_Sample_Barcode,Matched_Norm_Sample_Barcode,Match_Norm_Seq_Allele1,Match_Norm_Seq_Allele2,Tumor_Validation_Allele1,Tumor_Validation_Allele2,Match_Norm_Validation_Allele1,Match_Norm_Validation_Allele2,Verification_Status,Validation_Status,Mutation_Status,Sequencing_Phase,Sequence_Source,Validation_Method,Score,BAM_File,Sequencer,t_ref_count,t_alt_count,n_ref_count,n_alt_count,HGVSc,HGVSp,HGVSp_Short,Transcript_ID,RefSeq,Protein_position,Codons,Hotspot,Amino_Acid_Change
0,A1BG,NaN,dfci.harvard.edu,GRCh37,19,58862793,58862793,+,missense_variant,Missense_Mutation,SNP,C,C,T,NaN,NaN,coadread_dfci_2016_1231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000263100.3:c.874G>A,p.Gly292Arg,p.G292R,ENST00000263100,NM_130786.3,292.0,Ggg/Agg,0,p.G292R
1,A1BG,NaN,dfci.harvard.edu,GRCh37,19,58862794,58862794,+,synonymous_variant,Silent,SNP,G,G,A,NaN,NaN,coadread_dfci_2016_1231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000263100.3:c.873C>T,p.Ser291=,p.S291=,ENST00000263100,NM_130786.3,291.0,tcC/tcT,0,p.S291S
2,A1BG,NaN,dfci.harvard.edu,GRCh37,19,58862775,58862775,+,missense_variant,Missense_Mutation,SNP,C,C,T,NaN,NaN,coadread_dfci_2016_2269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000263100.3:c.892G>A,p.Glu298Lys,p.E298K,ENST00000263100,NM_130786.3,298.0,Gag/Aag,0,p.E298K
3,A1BG,NaN,dfci.harvard.edu,GRCh37,19,58858744,58858744,+,synonymous_variant,Silent,SNP,G,G,A,NaN,NaN,coadread_dfci_2016_230737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000263100.3:c.1455C>T,p.Ser485=,p.S485=,ENST00000263100,NM_130786.3,485.0,agC/agT,0,p.S485S
4,A1BG,NaN,dfci.harvard.edu,GRCh37,19,58862934,58862934,+,missense_variant,Missense_Mutation,SNP,G,G,A,NaN,NaN,coadread_dfci_2016_2429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000263100.3:c.733C>T,p.Arg245Cys,p.R245C,ENST00000263100,NM_130786.3,245.0,Cgc/Tgc,0,p.R245C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331418,ZZZ3,NaN,NaN,GRCh37,1,78098587,78098587,+,synonymous_variant,Silent,SNP,C,C,T,NaN,NaN,coadread_dfci_2016_430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000370801.3:c.453G>A,p.Val151=,p.V151=,ENST00000370801,NM_015534.4,151.0,gtG/gtA,0,p.V151V
331419,ZZZ3,NaN,NaN,GRCh37,1,78047826,78047827,+,intron_variant,Intron,INS,-,-,A,NaN,NaN,coadread_dfci_2016_4500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000370801.3:c.1645-16dupT,NaN,*549*,ENST00000370801,NM_015534.4,NaN,NaN,0,NaN
331420,ZZZ3,NaN,NaN,GRCh37,1,78031395,78031395,+,missense_variant,Missense_Mutation,SNP,C,C,G,NaN,NaN,coadread_dfci_2016_50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000370801.3:c.2642G>C,p.Arg881Thr,p.R881T,ENST00000370801,NM_015534.4,881.0,aGa/aCa,0,p.R881T
331421,ZZZ3,NaN,NaN,GRCh37,1,78047760,78047760,+,missense_variant,Missense_Mutation,SNP,C,C,T,NaN,NaN,coadread_dfci_2016_613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000370801.3:c.1696G>A,p.Val566Ile,p.V566I,ENST00000370801,NM_015534.4,566.0,Gta/Ata,0,p.V566I
331422,HIST2H2AC,NaN,dfci.harvard.edu,GRCh37,1,149858504,149858525,+,"coding_sequence_variant,5_prime_UTR_variant",5'UTR,DEL,TGTTTAACCTTGATTTCAGTCA,TGTTTAACCTTGATTTCAGTCA,-,NaN,NaN,coadread_dfci_2016_578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENST00000331380,NM_003517.2,NaN,NaN,0,NaN

In [8]:
dataMutation_Giannakis = dataMutation_Giannakis[['Tumor_Sample_Barcode', 'Hugo_Symbol', 'Chromosome', 'Start_Position', 'End_Position', 'Strand', 'Variant_Classification', 'Variant_Type', 'Reference_Allele', 'Tumor_Seq_Allele1', 'Tumor_Seq_Allele2', 'HGVSc', 'HGVSp_Short', 'Protein_position', 'Transcript_ID']]

In [9]:
dataMutation_Giannakis

,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID
0,coadread_dfci_2016_1231,A1BG,19,58862793,58862793,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100
1,coadread_dfci_2016_1231,A1BG,19,58862794,58862794,+,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100
2,coadread_dfci_2016_2269,A1BG,19,58862775,58862775,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.892G>A,p.E298K,298.0,ENST00000263100
3,coadread_dfci_2016_230737,A1BG,19,58858744,58858744,+,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100
4,coadread_dfci_2016_2429,A1BG,19,58862934,58862934,+,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331418,coadread_dfci_2016_430,ZZZ3,1,78098587,78098587,+,Silent,SNP,C,C,T,ENST00000370801.3:c.453G>A,p.V151=,151.0,ENST00000370801
331419,coadread_dfci_2016_4500,ZZZ3,1,78047826,78047827,+,Intron,INS,-,-,A,ENST00000370801.3:c.1645-16dupT,*549*,NaN,ENST00000370801
331420,coadread_dfci_2016_50,ZZZ3,1,78031395,78031395,+,Missense_Mutation,SNP,C,C,G,ENST00000370801.3:c.2642G>C,p.R881T,881.0,ENST00000370801
331421,coadread_dfci_2016_613,ZZZ3,1,78047760,78047760,+,Missense_Mutation,SNP,C,C,T,ENST00000370801.3:c.1696G>A,p.V566I,566.0,ENST00000370801
331422,coadread_dfci_2016_578,HIST2H2AC,1,149858504,149858525,+,5'UTR,DEL,TGTTTAACCTTGATTTCAGTCA,TGTTTAACCTTGATTTCAGTCA,-,NaN,NaN,NaN,ENST00000331380

In [10]:
uniqueHugo = dataMutation_Giannakis['Hugo_Symbol'].nunique()
uniqueTranscript = dataMutation_Giannakis['Transcript_ID'].nunique()
uniqueHugo, uniqueTranscript

(19206, 21023)

In [11]:
unknownHugo = (dataMutation_Giannakis['Hugo_Symbol'] == 'Unknown').sum()
emptyHugo = (dataMutation_Giannakis['Hugo_Symbol'] == '').sum()
naHugo = pd.isna(dataMutation_Giannakis['Hugo_Symbol']).sum()

unknownTranscript = (dataMutation_Giannakis['Transcript_ID'] == 'Unknown').sum()
emptyTranscript = (dataMutation_Giannakis['Transcript_ID'] == '').sum()
naTranscript = pd.isna(dataMutation_Giannakis['Transcript_ID']).sum()

unknownHugoUnknownTranscript = (dataMutation_Giannakis[dataMutation_Giannakis['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == 'Unknown').sum()
emptyHugoUnknownTranscript = (dataMutation_Giannakis[dataMutation_Giannakis['Hugo_Symbol'] == '']['Transcript_ID'] == 'Unknown').sum()
naHugoUnknownTranscript = (dataMutation_Giannakis[dataMutation_Giannakis['Hugo_Symbol'].isna()]['Transcript_ID'] == 'Unknown').sum()
unknownHugoEmptyTranscript = (dataMutation_Giannakis[dataMutation_Giannakis['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()
emptyHugoEmptyTranscript = (dataMutation_Giannakis[dataMutation_Giannakis['Hugo_Symbol'] == '']['Transcript_ID'] == '').sum()
naHugoEmptyTranscript = (dataMutation_Giannakis[dataMutation_Giannakis['Hugo_Symbol'].isna()]['Transcript_ID'] == '').sum()
unknownHugoNaTranscript = (pd.isna(dataMutation_Giannakis[dataMutation_Giannakis['Hugo_Symbol'] == 'Unknown']['Transcript_ID'])).sum()
emptyHugoNaTranscript = (pd.isna(dataMutation_Giannakis[dataMutation_Giannakis['Hugo_Symbol'] == '']['Transcript_ID'])).sum()
naHugoNaTranscript = (pd.isna(dataMutation_Giannakis[dataMutation_Giannakis['Hugo_Symbol'].isna()]['Transcript_ID'])).sum()

unknownHugoEmptyTranscript = (dataMutation_Giannakis[dataMutation_Giannakis['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()

(unknownHugo, emptyHugo, naHugo), (unknownTranscript, emptyTranscript, naTranscript), ((unknownHugoUnknownTranscript, emptyHugoUnknownTranscript, naHugoUnknownTranscript), (unknownHugoEmptyTranscript, emptyHugoEmptyTranscript, naHugoEmptyTranscript), (unknownHugoNaTranscript, emptyHugoNaTranscript, naHugoNaTranscript))

((3734, 0, 0), (0, 0, 96), ((0, 0, 0), (0, 0, 0), (96, 0, 0)))

In [12]:
# remove rows with both Hugo_Symbol == 'Unknown' and Transcript_ID == NA
dataMutation_Giannakis_nona = dataMutation_Giannakis[~((dataMutation_Giannakis['Hugo_Symbol'] == 'Unknown') & pd.isna(dataMutation_Giannakis['Transcript_ID']))]
dataMutation_Giannakis_nona

,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID
0,coadread_dfci_2016_1231,A1BG,19,58862793,58862793,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100
1,coadread_dfci_2016_1231,A1BG,19,58862794,58862794,+,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100
2,coadread_dfci_2016_2269,A1BG,19,58862775,58862775,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.892G>A,p.E298K,298.0,ENST00000263100
3,coadread_dfci_2016_230737,A1BG,19,58858744,58858744,+,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100
4,coadread_dfci_2016_2429,A1BG,19,58862934,58862934,+,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331418,coadread_dfci_2016_430,ZZZ3,1,78098587,78098587,+,Silent,SNP,C,C,T,ENST00000370801.3:c.453G>A,p.V151=,151.0,ENST00000370801
331419,coadread_dfci_2016_4500,ZZZ3,1,78047826,78047827,+,Intron,INS,-,-,A,ENST00000370801.3:c.1645-16dupT,*549*,NaN,ENST00000370801
331420,coadread_dfci_2016_50,ZZZ3,1,78031395,78031395,+,Missense_Mutation,SNP,C,C,G,ENST00000370801.3:c.2642G>C,p.R881T,881.0,ENST00000370801
331421,coadread_dfci_2016_613,ZZZ3,1,78047760,78047760,+,Missense_Mutation,SNP,C,C,T,ENST00000370801.3:c.1696G>A,p.V566I,566.0,ENST00000370801
331422,coadread_dfci_2016_578,HIST2H2AC,1,149858504,149858525,+,5'UTR,DEL,TGTTTAACCTTGATTTCAGTCA,TGTTTAACCTTGATTTCAGTCA,-,NaN,NaN,NaN,ENST00000331380

In [13]:
# Get unique transcript ids
uniqueTranscriptIds = dataMutation_Giannakis_nona['Transcript_ID'].unique()

# Create a dictionary mapping from Transcript_ID to Hugo_Symbol
transcriptIds_HugoSymbol_mapping = {id: ensembl.gene_name_of_transcript_id(id) for id in uniqueTranscriptIds}

transcriptIds_HugoSymbol_mapping

{'ENST00000263100': 'A1BG',
 'ENST00000595302': 'A1BG-AS1',
 'ENST00000373993': 'A1CF',
 'ENST00000373995': 'A1CF',
 'ENST00000318602': 'A2M',
 'ENST00000299698': 'A2ML1',
 'ENST00000442999': 'A3GALT2',
 'ENST00000249005': 'A4GALT',
 'ENST00000236709': 'A4GNT',
 'ENST00000209873': 'AAAS',
 'ENST00000316519': 'AACS',
 'ENST00000503486': 'AACSP1',
 'ENST00000232892': 'AADAC',
 'ENST00000356517': 'AADACL2',
 'ENST00000359318': 'AADACL3',
 'ENST00000376221': 'AADACL4',
 'ENST00000337664': 'AADAT',
 'ENST00000375234': 'AAED1',
 'ENST00000261880': 'AAGAB',
 'ENST00000409085': 'AAK1',
 'ENST00000393427': 'AAMDC',
 'ENST00000248450': 'AAMP',
 'ENST00000392492': 'AANAT',
 'ENST00000320849': 'AAR2',
 'ENST00000378279': 'AARD',
 'ENST00000261772': 'AARS',
 'ENST00000244571': 'AARS2',
 'ENST00000421990': 'PTGES3L-AARSD1',
 'ENST00000205214': 'AASDH',
 'ENST00000278618': 'AASDHPPT',
 'ENST00000393376': 'AASS',
 'ENST00000225402': 'AATF',
 'ENST00000326724': 'AATK',
 'ENST00000268251': 'ABAT',
 'ENST00000374736': 'ABCA1',
 'ENST00000269081': 'ABCA10',
 'ENST00000451020': 'ABCA11P',
 'ENST00000272895': 'ABCA12',
 'ENST00000435803': 'ABCA13',
 'ENST00000469908': 'ABCA17P',
 'ENST00000341511': 'ABCA2',
 'ENST00000301732': 'ABCA3',
 'ENST00000370225': 'ABCA4',
 'ENST00000392676': 'ABCA5',
 'ENST00000284425': 'ABCA6',
 'ENST00000263094': 'ABCA7',
 'ENST00000269080': 'ABCA8',
 'ENST00000340001': 'ABCA9',
 'ENST00000265724': 'ABCB1',
 'ENST00000344517': 'ABCB10',
 'ENST00000263817': 'ABCB11',
 'ENST00000265723': 'ABCB4',
 'ENST00000404938': 'ABCB5',
 'ENST00000265316': 'ABCB6',
 'ENST00000373394': 'ABCB7',
 'ENST00000297504': 'ABCB8',
 'ENST00000280560': 'ABCB9',
 'ENST00000228922': 'OGFOD2',
 'ENST00000399410': 'ABCC1',
 'ENST00000372530': 'ABCC10',
 'ENST00000356608': 'ABCC11',
 'ENST00000311303': 'ABCC12',
 'ENST00000370449': 'ABCC2',
 'ENST00000285238': 'ABCC3',
 'ENST00000376887': 'ABCC4',
 'ENST00000334444': 'ABCC5',
 'ENST00000205557': 'ABCC6',
 'ENST00000546162': 'ABCC6P1',
 'ENST00000389817': 'ABCC8',
 'ENST00000261201': 'ABCC9',
 'ENST00000218104': 'ABCD1',
 'ENST00000308666': 'ABCD2',
 'ENST00000370214': 'ABCD3',
 'ENST00000356924': 'ABCD4',
 'ENST00000296577': 'ABCE1',
 'ENST00000326195': 'ABCF1',
 'ENST00000401282': 'MIR877',
 'ENST00000287844': 'ABCF2',
 'ENST00000429586': 'ABCF3',
 'ENST00000361802': 'ABCG1',
 'ENST00000237612': 'ABCG2',
 'ENST00000307417': 'ABCG4',
 'ENST00000260645': 'ABCG5',
 'ENST00000272286': 'ABCG8',
 'ENST00000316470': 'ABHD1',
 'ENST00000273359': 'ABHD10',
 'ENST00000222800': 'ABHD11',
 'ENST00000339157': 'ABHD12',
 'ENST00000337334': 'ABHD12B',
 'ENST00000375898': 'ABHD13',
 'ENST00000273596': 'ABHD14A',
 'ENST00000361143': 'ABHD14B',
 'ENST00000307201': 'ABHD15',
 'ENST00000395952': 'ABHD16A',
 'ENST00000369916': 'ABHD16B',
 'ENST00000292577': 'ABHD17A',
 'ENST00000333421': 'ABHD17B',
 'ENST00000258884': 'ABHD17C',
 'ENST00000352732': 'ABHD2',
 'ENST00000289119': 'ABHD3',
 'ENST00000408566': 'MIR320C1',
 'ENST00000428304': 'ABHD4',
 'ENST00000458276': 'ABHD5',
 'ENST00000295962': 'ABHD6',
 'ENST00000247706': 'ABHD8',
 'ENST00000376142': 'ABI1',
 'ENST00000295851': 'ABI2',
 'ENST00000225941': 'ABI3',
 'ENST00000284322': 'ABI3BP',
 'ENST00000318560': 'ABL1',
 'ENST00000502732': 'ABL2',
 'ENST00000277895': 'ABLIM1',
 'ENST00000369252': 'ABLIM1',
 'ENST00000341937': 'ABLIM2',
 'ENST00000385072': 'MIR95',
 'ENST00000309868': 'ABLIM3',
 'ENST00000453660': 'ABO',
 'ENST00000302538': 'ABR',
 'ENST00000311955': 'ABRA',
 'ENST00000367660': 'ABRACL',
 'ENST00000274849': 'ABT1',
 'ENST00000232744': 'ABTB1',
 'ENST00000435224': 'ABTB2',
 'ENST00000462238': 'RPL23AP82',
 'ENST00000392351': 'HOMER3',
 'ENST00000393988': 'KRT41P',
 'ENST00000432258': 'AC003958.2',
 'ENST00000261377': 'AC004381.6',
 'ENST00000408452': 'AC004460.1',
 'ENST00000433419': 'CCDC144CP',
 'ENST00000417404': 'LRRC37BP1',
 'ENST00000502505': 'AC005609.1',
 'ENST00000607216': 'AC005754.7',
 'ENST00000379640': 'AC005863.1',
 'ENST00000413439': 'LILRP2',
 'ENST00000586572': 'AC006538.4',
 'ENST00000272438': 'TEX261',
 'ENST00000400027': 'OR7E91P',
 'ENST00000434096': 'AC007238.1',
 'ENST00000602145': 'AC007228.9',
 'ENST00000414296': 'DPY19L2P3',
 'ENST00000233190': 'NDUFS1',
 'ENST00000511549': 'BCRP7',
 'ENST00000563377': 'RP11-252A24.2',
 'ENST00000395384': 'QPRT',
 'ENST00000454750': 'AC009517.2',
 'ENST00000474610': 'MYADML',
 'ENST00000598855': 'AC010327.2',
 'ENST00000306708': 'LRRC8E',
 'ENST00000539278': 'AC010336.1',
 'ENST00000600109': 'AC010441.1',
 'ENST00000288177': 'ZNF19',
 'ENST00000543490': 'AC010731.4',
 'ENST00000586049': 'CYP4F24P',
 'ENST00000426194': 'AC012123.1',
 'ENST00000587132': 'AC015849.16',
 'ENST00000447430': 'AC016831.7',
 'ENST00000394878': 'RPLP0P6',
 'ENST00000417039': 'AC016995.3',
 'ENST00000447438': 'KLF2P1',
 'ENST00000449170': 'FAR2P1',
 'ENST00000383808': 'AC022007.5',
 'ENST00000595757': 'AC022400.2',
 'ENST00000287139': 'NODAL',
 'ENST00000420338': 'AC022532.1',
 'ENST00000417510': 'AC022596.6',
 'ENST00000418868': 'AC024560.3',
 'ENST00000308961': 'NDUFA11',
 'ENST00000326958': 'AC026703.1',
 'ENST00000575889': 'AC027763.2',
 'ENST00000251535': 'ALOX12',
 'ENST00000593646': 'AC040977.1',
 'ENST00000600087': 'AC061992.1',
 'ENST00000395326': 'CRCP',
 'ENST00000304874': 'ASL',
 'ENST00000557387': 'AC068831.12',
 'ENST00000557804': 'AC068831.10',
 'ENST00000607412': 'AC072062.1',
 'ENST00000453982': 'AC073135.3',
 'ENST00000441803': 'AC073321.4',
 'ENST00000600820': 'AC079210.1',
 'ENST00000412425': 'RAB6C-AS1',
 'ENST00000456398': 'AC093642.5',
 'ENST00000543018': 'HTR5A-AS1',
 'ENST00000438378': 'AC093838.4',
 'ENST00000456601': 'AC096574.4',
 'ENST00000430694': 'AC096579.7',
 'ENST00000390238': 'IGKJ5',
 'ENST00000452230': 'AC096579.13',
 'ENST00000390240': 'IGKJ3',
 'ENST00000429417': 'DNAJB1P1',
 'ENST00000428556': 'AC103801.2',
 'ENST00000408214': 'AC126323.1',
 'ENST00000429274': 'hsa-mir-7162',
 'ENST00000399413': 'AC129492.6',
 'ENST00000602923': 'RPL26P30',
 'ENST00000458669': 'PKD1P1',
 'ENST00000313946': 'FAM86EP',
 'ENST00000281228': 'AC226119.5',
 'ENST00000333167': 'ACAA1',
 'ENST00000285093': 'ACAA2',
 'ENST00000353139': 'ACACA',
 'ENST00000338432': 'ACACB',
 'ENST00000313698': 'ACAD10',
 'ENST00000264990': 'ACAD11',
 'ENST00000281182': 'ACAD8',
 'ENST00000308982': 'ACAD9',
 'ENST00000233710': 'ACADL',
 'ENST00000370841': 'ACADM',
 'ENST00000444241': 'RP4-682C21.2',
 'ENST00000242592': 'ACADS',
 'ENST00000358776': 'ACADSB',
 'ENST00000356839': 'ACADVL',
 'ENST00000439576': 'ACAN',
 'ENST00000158762': 'ACAP1',
 'ENST00000326793': 'ACAP2',
 'ENST00000354700': 'ACAP3',
 'ENST00000265838': 'ACAT1',
 'ENST00000367048': 'ACAT2',
 'ENST00000366812': 'ACBD3',
 'ENST00000376955': 'ACBD4',
 'ENST00000375888': 'ACBD5',
 'ENST00000367595': 'ACBD6',
 'ENST00000450197': 'VDAC1P4',
 'ENST00000356189': 'ACBD7',
 'ENST00000263776': 'ACCS',
 'ENST00000378832': 'ACCSL',
 'ENST00000393919': 'ACD',
 'ENST00000290866': 'ACE',
 'ENST00000252519': 'ACE2',
 'ENST00000301452': 'ACER1',
 'ENST00000340967': 'ACER2',
 'ENST00000532485': 'ACER3',
 'ENST00000530190': 'CTD-2547H18.1',
 'ENST00000241069': 'ACHE',
 'ENST00000262710': 'ACIN1',
 'ENST00000273145': 'ACKR2',
 'ENST00000272928': 'ACKR3',
 'ENST00000249887': 'ACKR4',
 'ENST00000399036': 'CCRL2',
 'ENST00000262483': 'PITPNM3',
 'ENST00000352035': 'ACLY',
 'ENST00000356140': 'ACMSD',
 'ENST00000537615': 'CCNT2-AS1',
 'ENST00000432641': 'ACN9',
 'ENST00000309951': 'ACO1',
 'ENST00000216254': 'ACO2',
 'ENST00000311148': 'ACOT1',
 'ENST00000371316': 'ACOT11',
 'ENST00000307624': 'ACOT12',
 'ENST00000230048': 'ACOT13',
 'ENST00000238651': 'ACOT2',
 'ENST00000326303': 'ACOT4',
 'ENST00000381139': 'ACOT6',
 'ENST00000377855': 'ACOT7',
 'ENST00000607670': 'RP1-202O8.3',
 'ENST00000217455': 'ACOT8',
 'ENST00000336430': 'ACOT9',
 'ENST00000301608': 'ACOX1',
 'ENST00000302819': 'ACOX2',
 'ENST00000356406': 'ACOX3',
 'ENST00000389811': 'ACOXL',
 'ENST00000272065': 'ACP1',
 'ENST00000256997': 'ACP2',
 'ENST00000218758': 'ACP5',
 'ENST00000369238': 'ACP6',
 'ENST00000286353': 'ACPL2',
 'ENST00000336375': 'ACPP',
 'ENST00000351273': 'ACPP',
 'ENST00000270593': 'ACPT',
 'ENST00000216139': 'ACR',
 'ENST00000229243': 'ACRBP',
 'ENST00000373695': 'ACRC',
 'ENST00000533904': 'ACRV1',
 'ENST00000258873': 'ACSBG1',
 'ENST00000586696': 'ACSBG2',
 'ENST00000300441': 'ACSF2',
 'ENST00000317447': 'ACSF3',
 'ENST00000562782': 'CTD-2555A7.3',
 'ENST00000281455': 'ACSL1',
 'ENST00000357430': 'ACSL3',
 'ENST00000340800': 'ACSL4',
 'ENST00000354273': 'ACSL5',
 'ENST00000379240': 'ACSL6',
 'ENST00000379264': 'ACSL6',
 'ENST00000307493': 'ACSM1',
 'ENST00000219054': 'ACSM2A',
 'ENST00000329697': 'ACSM2B',
 'ENST00000289416': 'ACSM3',
 'ENST00000399422': 'ACSM4',
 'ENST00000331849': 'ACSM5',
 'ENST00000323482': 'ACSS1',
 'ENST00000360596': 'ACSS2',
 'ENST00000548058': 'ACSS3',
 'ENST00000366684': 'ACTA1',
 'ENST00000224784': 'ACTA2',
 'ENST00000331789': 'ACTB',
 'ENST00000423391': 'ACTBL2',
 'ENST00000290378': 'ACTC1',
 'ENST00000331925': 'ACTG1',
 'ENST00000345517': 'ACTG2',
 'ENST00000330271': 'ACTL10',
 'ENST00000429709': 'ACTL6A',
 'ENST00000160382': 'ACTL6B',
 'ENST00000333999': 'ACTL7A',
 'ENST00000374667': 'ACTL7B',
 'ENST00000375406': 'ACTL8',
 'ENST00000324436': 'ACTL9',
 'ENST00000193403': 'ACTN1',
 'ENST00000555136': 'HMGN1P3',
 'ENST00000366578': 'ACTN2',
 'ENST00000513398': 'ACTN3',
 'ENST00000252699': 'ACTN4',
 'ENST00000254286': 'ACTR10',
 'ENST00000369905': 'ACTR1A',
 'ENST00000289228': 'ACTR1B',
 'ENST00000260641': 'ACTR2',
 'ENST00000263238': 'ACTR3',
 'ENST00000256001': 'ACTR3B',
 'ENST00000252071': 'ACTR3C',
 'ENST00000243903': 'ACTR5',
 'ENST00000188312': 'ACTR6',
 'ENST00000335754': 'ACTR8',
 'ENST00000371124': 'ACTRT1',
 'ENST00000378404': 'ACTRT2',
 'ENST00000330368': 'ACTRT3',
 'ENST00000263640': 'ACVR1',
 'ENST00000257963': 'ACVR1B',
 'ENST00000243349': 'ACVR1C',
 'ENST00000241416': 'ACVR2A',
 'ENST00000352511': 'ACVR2B',
 'ENST00000388922': 'ACVRL1',
 'ENST00000404366': 'ACY1',
 'ENST00000255082': 'ACY3',
 'ENST00000238618': 'ACYP1',
 'ENST00000437242': 'HMGB1P31',
 'ENST00000394666': 'ACYP2',
 'ENST00000372874': 'ADA',
 'ENST00000296513': 'ADAD1',
 'ENST00000315906': 'ADAD2',
 'ENST00000562188': 'ADAL',
 'ENST00000260408': 'ADAM10',
 'ENST00000200557': 'ADAM11',
 'ENST00000368679': 'ADAM12',
 'ENST00000356955': 'ADAM15',
 'ENST00000310823': 'ADAM17',
 'ENST00000265707': 'ADAM18',
 'ENST00000517905': 'ADAM19',
 'ENST00000265708': 'ADAM2',
 'ENST00000256389': 'ADAM20',
 'ENST00000603540': 'ADAM21',
 'ENST00000530196': 'ADAM21P1',
 'ENST00000265727': 'ADAM22',
 'ENST00000264377': 'ADAM23',
 'ENST00000265769': 'ADAM28',
 'ENST00000359240': 'ADAM29',
 'ENST00000369400': 'ADAM30',
 'ENST00000379907': 'ADAM32',
 'ENST00000356518': 'ADAM33',
 'ENST00000175238': 'ADAM7',
 'ENST00000445355': 'ADAM8',
 'ENST00000487273': 'ADAM9',
 'ENST00000256412': 'ADAMDEC1',
 'ENST00000284984': 'ADAMTS1',
 'ENST00000597188': 'ADAMTS10',
 'ENST00000504830': 'ADAMTS12',
 'ENST00000371929': 'ADAMTS13',
 'ENST00000371942': 'REXO4',
 'ENST00000373207': 'ADAMTS14',
 'ENST00000299164': 'ADAMTS15',
 'ENST00000274181': 'ADAMTS16',
 'ENST00000268070': 'ADAMTS17',
 'ENST00000282849': 'ADAMTS18',
 'ENST00000274487': 'ADAMTS19',
 'ENST00000251582': 'ADAMTS2',
 'ENST00000389420': 'ADAMTS20',
 'ENST00000286657': 'ADAMTS3',
 'ENST00000503918': 'RP11-373J21.1',
 'ENST00000367996': 'ADAMTS4',
 'ENST00000284987': 'ADAMTS5',
 'ENST00000381055': 'ADAMTS6',
 'ENST00000388820': 'ADAMTS7',
 'ENST00000257359': 'ADAMTS8',
 'ENST00000498707': 'ADAMTS9',
 'ENST00000380548': 'ADAMTSL1',
 'ENST00000412709': 'RP11-503K16.2',
 'ENST00000354484': 'ADAMTSL2',
 'ENST00000286744': 'ADAMTSL3',
 'ENST00000271643': 'ADAMTSL4',
 'ENST00000330475': 'ADAMTSL5',
 'ENST00000265846': 'ADAP1',
 'ENST00000330889': 'ADAP2',
 'ENST00000368474': 'ADAR',
 'ENST00000292205': 'ADAR',
 'ENST00000360697': 'ADARB1',
 'ENST00000539173': 'ADARB1',
 'ENST00000381312': 'ADARB2',
 'ENST00000421697': 'ADARB2-AS1',
 'ENST00000307921': 'ADAT1',
 'ENST00000237283': 'ADAT2',
 'ENST00000602400': 'ADAT3',
 'ENST00000316097': 'SCAMP4',
 'ENST00000294517': 'ADC',
 'ENST00000238561': 'ADCK1',
 'ENST00000072869': 'ADCK2',
 'ENST00000366777': 'ADCK3',
 'ENST00000324464': 'ADCK4',
 'ENST00000308860': 'ADCK5',
 'ENST00000297323': 'ADCY1',
 'ENST00000367851': 'ADCY10',
 'ENST00000338316': 'ADCY2',
 'ENST00000260600': 'ADCY3',
 'ENST00000310677': 'ADCY4',
 'ENST00000462833': 'ADCY5',
 'ENST00000307885': 'ADCY6',
 'ENST00000254235': 'ADCY7',
 'ENST00000286355': 'ADCY8',
 'ENST00000294016': 'ADCY9',
 'ENST00000450565': 'ADCYAP1',
 'ENST00000304166': 'ADCYAP1R1',
 'ENST00000398129': 'ADD1',
 'ENST00000264436': 'ADD2',
 'ENST00000356080': 'ADD3',
 'ENST00000562413': 'KATNBL1P6',
 'ENST00000209668': 'ADH1A',
 'ENST00000305046': 'ADH1B',
 'ENST00000515683': 'ADH1C',
 'ENST00000265512': 'ADH4',
 'ENST00000296412': 'ADH5',
 'ENST00000237653': 'ADH6',
 'ENST00000209665': 'ADH7',
 'ENST00000396623': 'ADHFE1',
 'ENST00000327435': 'ADI1',
 'ENST00000320741': 'ADIPOQ',
 'ENST00000340990': 'ADIPOR1',
 'ENST00000357103': 'ADIPOR2',
 'ENST00000372013': 'ADIRF',
 'ENST00000286621': 'ADK',
 'ENST00000278175': 'ADM',
 'ENST00000395737': 'ADM2',
 'ENST00000420022': 'ADM5',
 'ENST00000349014': 'ADNP',
 'ENST00000262198': 'ADNP2',
 'ENST00000373783': 'ADO',
 'ENST00000309502': 'ADORA1',
 'ENST00000337539': 'ADORA2A',
 'ENST00000304222': 'ADORA2B',
 'ENST00000241356': 'ADORA3',
 'ENST00000369717': 'ADORA3',
 'ENST00000311669': 'ADPGK',
 'ENST00000357003': 'ADPRH',
 'ENST00000375418': 'ADPRHL1',
 'ENST00000373178': 'ADPRHL2',
 'ENST00000379774': 'ADPRM',
 'ENST00000276393': 'ADRA1A',
 'ENST00000380586': 'ADRA1A',
 'ENST00000306675': 'ADRA1B',
 'ENST00000379453': 'ADRA1D',
 'ENST00000280155': 'ADRA2A',
 'ENST00000409345': 'ADRA2B',
 'ENST00000330055': 'ADRA2C',
 'ENST00000369295': 'ADRB1',
 'ENST00000305988': 'ADRB2',
 'ENST00000345060': 'ADRB3',
 'ENST00000308595': 'ADRBK1',
 'ENST00000324198': 'ADRBK2',
 'ENST00000253003': 'ADRM1',
 'ENST00000414042': 'RP11-157P1.4',
 'ENST00000216194': 'ADSL',
 'ENST00000366535': 'ADSS',
 'ENST00000330877': 'ADSSL1',
 'ENST00000414691': 'ADTRP',
 'ENST00000390477': 'TRDC',
 'ENST00000514473': 'AE000661.37',
 'ENST00000390469': 'TRDV2',
 'ENST00000223357': 'AEBP1',
 'ENST00000398864': 'AEBP2',
 'ENST00000543528': 'RP11-841C19.3',
 'ENST00000332810': 'AEN',
 'ENST00000327141': 'AES',
 'ENST00000380931': 'AF064858.6',
 'ENST00000608442': 'AFAP1-AS1',
 'ENST00000358461': 'AFAP1',
 'ENST00000296721': 'AFAP1L1',
 'ENST00000304129': 'AFAP1L2',
 'ENST00000307808': 'AFF1',
 'ENST00000444365': 'TECRP1',
 'ENST00000370460': 'AFF2',
 'ENST00000409236': 'AFF3',
 'ENST00000265343': 'AFF4',
 'ENST00000269143': 'AFG3L2',
 'ENST00000226355': 'AFM',
 'ENST00000409257': 'AFMID',
 'ENST00000395792': 'AFP',
 'ENST00000238855': 'AFTPH',
 'ENST00000264595': 'AGA',
 'ENST00000304032': 'AGAP1',
 'ENST00000413193': 'AGAP10',
 'ENST00000372011': 'BMS1P3',
 'ENST00000433214': 'RP11-96C23.5',
 'ENST00000547588': 'AGAP2',
 'ENST00000542466': 'AGAP2-AS1',
 'ENST00000397238': 'AGAP3',
 'ENST00000448048': 'AGAP4',
 'ENST00000374094': 'AGAP5',
 'ENST00000374056': 'AGAP6',
 'ENST00000374095': 'AGAP7',
 'ENST00000441037': 'AGBL1',
 'ENST00000525123': 'AGBL2',
 'ENST00000427378': 'AC083862.6',
 'ENST00000371839': 'AGBL4',
 'ENST00000360131': 'AGBL5',
 'ENST00000375076': 'AGER',
 'ENST00000310078': 'AGFG1',
 'ENST00000300176': 'AGFG2',
 'ENST00000312916': 'AGGF1',
 'ENST00000355413': 'AGK',
 'ENST00000294724': 'AGL',
 'ENST00000375826': 'AGMAT',
 'ENST00000342526': 'AGMO',
 'ENST00000373204': 'AGO1',
 'ENST00000220592': 'AGO2',
 'ENST00000373191': 'AGO3',
 'ENST00000479395': 'RP4-665N4.8',
 'ENST00000373210': 'AGO4',
 'ENST00000336984': 'AGPAT1',
 'ENST00000371696': 'AGPAT2',
 'ENST00000291572': 'AGPAT3',
 'ENST00000320285': 'AGPAT4',
 'ENST00000285518': 'AGPAT5',
 'ENST00000396987': 'AGPAT6',
 'ENST00000264409': 'AGPAT9',
 'ENST00000264167': 'AGPS',
 'ENST00000419304': 'AGR2',
 'ENST00000418130': 'RAD17P1',
 'ENST00000310398': 'AGR3',
 'ENST00000379370': 'AGRN',
 'ENST00000290953': 'AGRP',
 'ENST00000366667': 'AGT',
 'ENST00000357081': 'AGTPBP1',
 'ENST00000349243': 'AGTR1',
 'ENST00000371906': 'AGTR2',
 'ENST00000314340': 'AGTRAP',
 'ENST00000307503': 'AGXT',
 'ENST00000231420': 'AGXT2',
 'ENST00000326225': 'AHCTF1',
 'ENST00000217426': 'AHCY',
 'ENST00000369799': 'AHCYL1',
 'ENST00000325006': 'AHCYL2',
 'ENST00000247087': 'AHDC1',
 'ENST00000265602': 'AHI1',
 'ENST00000378024': 'AHNAK',
 'ENST00000257247': 'AHNAK',
 'ENST00000333244': 'AHNAK2',
 'ENST00000242057': 'AHR',
 'ENST00000505113': 'AHRR',
 'ENST00000216479': 'AHSA1',
 'ENST00000394457': 'AHSA2',
 'ENST00000411641': 'AHSG',
 'ENST00000302312': 'AHSP',
 'ENST00000229335': 'AICDA',
 'ENST00000340020': 'AIDA',
 'ENST00000376059': 'AIF1',
 'ENST00000247291': 'AIF1L',
 'ENST00000287295': 'AIFM1',
 'ENST00000307864': 'AIFM2',
 'ENST00000399167': 'AIFM3',
 'ENST00000275235': 'AIG1',
 'ENST00000369066': 'AIM1',
 'ENST00000308182': 'AIM1L',
 'ENST00000368130': 'AIM2',
 'ENST00000358008': 'AIMP1',
 'ENST00000223029': 'AIMP2',
 'ENST00000279146': 'AIP',
 'ENST00000381129': 'AIPL1',
 'ENST00000291582': 'AIRE',
 'ENST00000366390': 'OR1F2P',
 'ENST00000285718': 'AJ271736.10',
 'ENST00000378190': 'AJAP1',
 'ENST00000262713': 'AJUBA',
 'ENST00000373156': 'AK1',
 'ENST00000354858': 'AK2',
 'ENST00000381809': 'AK3',
 'ENST00000327299': 'AK4',
 'ENST00000354567': 'AK5',
 'ENST00000267584': 'AK7',
 'ENST00000298545': 'AK8',
 'ENST00000424296': 'AK9',
 'ENST00000337714': 'AKAP1',
 'ENST00000225737': 'AKAP10',
 'ENST00000025301': 'AKAP11',
 'ENST00000253332': 'AKAP12',
 'ENST00000394518': 'AKAP13',
 'ENST00000371431': 'AKAP14',
 'ENST00000313871': 'AKAP17A',
 'ENST00000259318': 'AKAP2',
 'ENST00000228850': 'AKAP3',
 'ENST00000358526': 'AKAP4',
 'ENST00000320636': 'AKAP5',
 'ENST00000280979': 'AKAP6',
 'ENST00000431975': 'AKAP7',
 'ENST00000269701': 'AKAP8',
 'ENST00000397410': 'AKAP8L',
 'ENST00000356239': 'AKAP9',
 'ENST00000309377': 'AKIP1',
 'ENST00000432648': 'AKIRIN1',
 'ENST00000257787': 'AKIRIN2',
 'ENST00000307564': 'AKNA',
 'ENST00000370001': 'AKNAD1',
 'ENST00000351829': 'AKR1A1',
 'ENST00000285930': 'AKR1B1',
 'ENST00000359579': 'AKR1B10',
 'ENST00000457545': 'AKR1B15',
 'ENST00000380872': 'AKR1C1',
 'ENST00000380753': 'AKR1C2',
 'ENST00000380554': 'AKR1C3',
 'ENST00000263126': 'AKR1C4',
 'ENST00000488756': 'AKR1CL1',
 'ENST00000242375': 'AKR1D1',
 'ENST00000298375': 'AKR1E2',
 'ENST00000235835': 'AKR7A2',
 'ENST00000361640': 'AKR7A3',
 'ENST00000420396': 'AKR7L',
 'ENST00000349310': 'AKT1',
 'ENST00000344175': 'AKT1S1',
 'ENST00000392038': 'AKT2',
 'ENST00000263826': 'AKT3',
 'ENST00000394657': 'AKTIP',
 'ENST00000551765': 'GATC',
 'ENST00000594544': 'AL035406.1',
 'ENST00000362928': 'SNORD114-5',
 'ENST00000423708': 'AL132709.8',
 'ENST00000596306': 'AL133373.1',
 'ENST00000538322': 'AL133481.1',
 'ENST00000453638': 'AL445989.1',
 'ENST00000558378': 'AL583828.1',
 'ENST00000594609': 'AL590714.1',
 'ENST00000492974': 'RP11-475C16.1',
 'ENST00000335083': 'AL603965.1',
 'ENST00000342991': 'CYP21A1P',
 'ENST00000409155': 'ALAD',
 'ENST00000310271': 'ALAS1',
 'ENST00000330807': 'ALAS2',
 'ENST00000295897': 'ALB',
 'ENST00000306107': 'ALCAM',
 'ENST00000293350': 'ALDH16A1',
 'ENST00000371224': 'ALDH18A1',
 'ENST00000297785': 'ALDH1A1',
 'ENST00000249750': 'ALDH1A2',
 'ENST00000329841': 'ALDH1A3',
 'ENST00000377698': 'ALDH1B1',
 'ENST00000393434': 'ALDH1L1',
 'ENST00000258494': 'ALDH1L2',
 'ENST00000261733': 'ALDH2',
 'ENST00000225740': 'ALDH3A1',
 'ENST00000176643': 'ALDH3A2',
 'ENST00000342456': 'ALDH3B1',
 'ENST00000349015': 'ALDH3B2',
 'ENST00000290597': 'ALDH4A1',
 'ENST00000357578': 'ALDH5A1',
 'ENST00000394009': 'CCDC176',
 'ENST00000553458': 'ALDH6A1',
 'ENST00000409134': 'ALDH7A1',
 'ENST00000265605': 'ALDH8A1',
 'ENST00000354775': 'ALDH9A1',
 'ENST00000338110': 'ALDOA',
 'ENST00000374855': 'ALDOB',
 'ENST00000226253': 'ALDOC',

In [14]:
# add Ensembl Hugo_Symbol
dataMutation_Giannakis_cleaned = dataMutation_Giannakis_nona.copy()
dataMutation_Giannakis_cleaned.rename(columns={'Hugo_Symbol': 'original_Hugo_Symbol'}, inplace=True)
dataMutation_Giannakis_cleaned.insert(1, 'Hugo_Symbol', '')
dataMutation_Giannakis_cleaned.loc[:,'Hugo_Symbol'] = dataMutation_Giannakis_cleaned['Transcript_ID'].map(transcriptIds_HugoSymbol_mapping)

In [15]:
dataMutation_Giannakis_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID
0,coadread_dfci_2016_1231,A1BG,A1BG,19,58862793,58862793,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100
1,coadread_dfci_2016_1231,A1BG,A1BG,19,58862794,58862794,+,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100
2,coadread_dfci_2016_2269,A1BG,A1BG,19,58862775,58862775,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.892G>A,p.E298K,298.0,ENST00000263100
3,coadread_dfci_2016_230737,A1BG,A1BG,19,58858744,58858744,+,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100
4,coadread_dfci_2016_2429,A1BG,A1BG,19,58862934,58862934,+,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331418,coadread_dfci_2016_430,ZZZ3,ZZZ3,1,78098587,78098587,+,Silent,SNP,C,C,T,ENST00000370801.3:c.453G>A,p.V151=,151.0,ENST00000370801
331419,coadread_dfci_2016_4500,ZZZ3,ZZZ3,1,78047826,78047827,+,Intron,INS,-,-,A,ENST00000370801.3:c.1645-16dupT,*549*,NaN,ENST00000370801
331420,coadread_dfci_2016_50,ZZZ3,ZZZ3,1,78031395,78031395,+,Missense_Mutation,SNP,C,C,G,ENST00000370801.3:c.2642G>C,p.R881T,881.0,ENST00000370801
331421,coadread_dfci_2016_613,ZZZ3,ZZZ3,1,78047760,78047760,+,Missense_Mutation,SNP,C,C,T,ENST00000370801.3:c.1696G>A,p.V566I,566.0,ENST00000370801
331422,coadread_dfci_2016_578,HIST2H2AC,HIST2H2AC,1,149858504,149858525,+,5'UTR,DEL,TGTTTAACCTTGATTTCAGTCA,TGTTTAACCTTGATTTCAGTCA,-,NaN,NaN,NaN,ENST00000331380

In [16]:
# show rows where Hugo_Symbol and original_Hugo_Symbol are different
dataMutation_Giannakis_cleaned.loc[dataMutation_Giannakis_cleaned['Hugo_Symbol'] != dataMutation_Giannakis_cleaned['original_Hugo_Symbol'], ['Transcript_ID', 'Hugo_Symbol', 'original_Hugo_Symbol']]

          Transcript_ID     Hugo_Symbol original_Hugo_Symbol
8       ENST00000595302        A1BG-AS1                 A1BG
374     ENST00000421990  PTGES3L-AARSD1               AARSD1
1507    ENST00000228922          OGFOD2                ABCB9
2177    ENST00000401282          MIR877                ABCF1
2179    ENST00000401282          MIR877                ABCF1
...                 ...             ...                  ...
330472  ENST00000462773           HLA-J            ZNRD1-AS1
330473  ENST00000462773           HLA-J            ZNRD1-AS1
330474  ENST00000462773           HLA-J            ZNRD1-AS1
330480  ENST00000385037        MIR550A1                ZNRF2
330690  ENST00000426999      ZRANB2-AS1               ZRANB2

[8860 rows x 3 columns]

In [17]:
# add gene length
dataMutation_Giannakis_cleaned['Gene_Length'] = dataMutation_Giannakis_cleaned['Hugo_Symbol'].apply(lambda x: ensembl.genes_by_name(x)[0].length)

In [18]:
dataMutation_Giannakis_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length
0,coadread_dfci_2016_1231,A1BG,A1BG,19,58862793,58862793,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100,8322
1,coadread_dfci_2016_1231,A1BG,A1BG,19,58862794,58862794,+,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100,8322
2,coadread_dfci_2016_2269,A1BG,A1BG,19,58862775,58862775,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.892G>A,p.E298K,298.0,ENST00000263100,8322
3,coadread_dfci_2016_230737,A1BG,A1BG,19,58858744,58858744,+,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100,8322
4,coadread_dfci_2016_2429,A1BG,A1BG,19,58862934,58862934,+,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100,8322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331418,coadread_dfci_2016_430,ZZZ3,ZZZ3,1,78098587,78098587,+,Silent,SNP,C,C,T,ENST00000370801.3:c.453G>A,p.V151=,151.0,ENST00000370801,121004
331419,coadread_dfci_2016_4500,ZZZ3,ZZZ3,1,78047826,78047827,+,Intron,INS,-,-,A,ENST00000370801.3:c.1645-16dupT,*549*,NaN,ENST00000370801,121004
331420,coadread_dfci_2016_50,ZZZ3,ZZZ3,1,78031395,78031395,+,Missense_Mutation,SNP,C,C,G,ENST00000370801.3:c.2642G>C,p.R881T,881.0,ENST00000370801,121004
331421,coadread_dfci_2016_613,ZZZ3,ZZZ3,1,78047760,78047760,+,Missense_Mutation,SNP,C,C,T,ENST00000370801.3:c.1696G>A,p.V566I,566.0,ENST00000370801,121004
331422,coadread_dfci_2016_578,HIST2H2AC,HIST2H2AC,1,149858504,149858525,+,5'UTR,DEL,TGTTTAACCTTGATTTCAGTCA,TGTTTAACCTTGATTTCAGTCA,-,NaN,NaN,NaN,ENST00000331380,437

In [19]:
uniqueHugo = dataMutation_Giannakis_cleaned['Hugo_Symbol'].nunique(dropna=False)
uniqueTranscript = dataMutation_Giannakis_cleaned['Transcript_ID'].nunique(dropna=False)
uniqueHugo, uniqueTranscript

(20738, 21023)

In [20]:
unknownHugo = (dataMutation_Giannakis_cleaned['Hugo_Symbol'] == 'Unknown').sum()
emptyHugo = (dataMutation_Giannakis_cleaned['Hugo_Symbol'] == '').sum()
naHugo = pd.isna(dataMutation_Giannakis_cleaned['Hugo_Symbol']).sum()

unknownTranscript = (dataMutation_Giannakis_cleaned['Transcript_ID'] == 'Unknown').sum()
emptyTranscript = (dataMutation_Giannakis_cleaned['Transcript_ID'] == '').sum()
naTranscript = pd.isna(dataMutation_Giannakis_cleaned['Transcript_ID']).sum()

unknownHugoUnknownTranscript = (dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == 'Unknown').sum()
emptyHugoUnknownTranscript = (dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Hugo_Symbol'] == '']['Transcript_ID'] == 'Unknown').sum()
naHugoUnknownTranscript = (dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Hugo_Symbol'].isna()]['Transcript_ID'] == 'Unknown').sum()
unknownHugoEmptyTranscript = (dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()
emptyHugoEmptyTranscript = (dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Hugo_Symbol'] == '']['Transcript_ID'] == '').sum()
naHugoEmptyTranscript = (dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Hugo_Symbol'].isna()]['Transcript_ID'] == '').sum()
unknownHugoNaTranscript = (pd.isna(dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'])).sum()
emptyHugoNaTranscript = (pd.isna(dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Hugo_Symbol'] == '']['Transcript_ID'])).sum()
naHugoNaTranscript = (pd.isna(dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Hugo_Symbol'].isna()]['Transcript_ID'])).sum()

unknownHugoEmptyTranscript = (dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()

(unknownHugo, emptyHugo, naHugo), (unknownTranscript, emptyTranscript, naTranscript), ((unknownHugoUnknownTranscript, emptyHugoUnknownTranscript, naHugoUnknownTranscript), (unknownHugoEmptyTranscript, emptyHugoEmptyTranscript, naHugoEmptyTranscript), (unknownHugoNaTranscript, emptyHugoNaTranscript, naHugoNaTranscript))

((0, 0, 0), (0, 0, 0), ((0, 0, 0), (0, 0, 0), (0, 0, 0)))

In [21]:
dataMutation_Giannakis_cleaned['Mutation_Length'] = dataMutation_Giannakis_cleaned['End_Position'] - dataMutation_Giannakis_cleaned['Start_Position'] + 1
dataMutation_Giannakis_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length
0,coadread_dfci_2016_1231,A1BG,A1BG,19,58862793,58862793,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100,8322,1
1,coadread_dfci_2016_1231,A1BG,A1BG,19,58862794,58862794,+,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100,8322,1
2,coadread_dfci_2016_2269,A1BG,A1BG,19,58862775,58862775,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.892G>A,p.E298K,298.0,ENST00000263100,8322,1
3,coadread_dfci_2016_230737,A1BG,A1BG,19,58858744,58858744,+,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100,8322,1
4,coadread_dfci_2016_2429,A1BG,A1BG,19,58862934,58862934,+,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100,8322,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331418,coadread_dfci_2016_430,ZZZ3,ZZZ3,1,78098587,78098587,+,Silent,SNP,C,C,T,ENST00000370801.3:c.453G>A,p.V151=,151.0,ENST00000370801,121004,1
331419,coadread_dfci_2016_4500,ZZZ3,ZZZ3,1,78047826,78047827,+,Intron,INS,-,-,A,ENST00000370801.3:c.1645-16dupT,*549*,NaN,ENST00000370801,121004,2
331420,coadread_dfci_2016_50,ZZZ3,ZZZ3,1,78031395,78031395,+,Missense_Mutation,SNP,C,C,G,ENST00000370801.3:c.2642G>C,p.R881T,881.0,ENST00000370801,121004,1
331421,coadread_dfci_2016_613,ZZZ3,ZZZ3,1,78047760,78047760,+,Missense_Mutation,SNP,C,C,T,ENST00000370801.3:c.1696G>A,p.V566I,566.0,ENST00000370801,121004,1
331422,coadread_dfci_2016_578,HIST2H2AC,HIST2H2AC,1,149858504,149858525,+,5'UTR,DEL,TGTTTAACCTTGATTTCAGTCA,TGTTTAACCTTGATTTCAGTCA,-,NaN,NaN,NaN,ENST00000331380,437,22

In [22]:
### TODO: what to do with missing protein positions? For now, removing them
dataMutation_Giannakis_cleaned = dataMutation_Giannakis_cleaned[~dataMutation_Giannakis_cleaned['Protein_position'].isna()].copy()
dataMutation_Giannakis_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length
0,coadread_dfci_2016_1231,A1BG,A1BG,19,58862793,58862793,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100,8322,1
1,coadread_dfci_2016_1231,A1BG,A1BG,19,58862794,58862794,+,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100,8322,1
2,coadread_dfci_2016_2269,A1BG,A1BG,19,58862775,58862775,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.892G>A,p.E298K,298.0,ENST00000263100,8322,1
3,coadread_dfci_2016_230737,A1BG,A1BG,19,58858744,58858744,+,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100,8322,1
4,coadread_dfci_2016_2429,A1BG,A1BG,19,58862934,58862934,+,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100,8322,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331415,coadread_dfci_2016_3263,ZZZ3,ZZZ3,1,78097977,78097977,+,Missense_Mutation,SNP,A,A,G,ENST00000370801.3:c.1063T>C,p.S355P,355.0,ENST00000370801,121004,1
331416,coadread_dfci_2016_335135,ZZZ3,ZZZ3,1,78098938,78098938,+,Silent,SNP,C,C,T,ENST00000370801.3:c.102G>A,p.A34=,34.0,ENST00000370801,121004,1
331418,coadread_dfci_2016_430,ZZZ3,ZZZ3,1,78098587,78098587,+,Silent,SNP,C,C,T,ENST00000370801.3:c.453G>A,p.V151=,151.0,ENST00000370801,121004,1
331420,coadread_dfci_2016_50,ZZZ3,ZZZ3,1,78031395,78031395,+,Missense_Mutation,SNP,C,C,G,ENST00000370801.3:c.2642G>C,p.R881T,881.0,ENST00000370801,121004,1
331421,coadread_dfci_2016_613,ZZZ3,ZZZ3,1,78047760,78047760,+,Missense_Mutation,SNP,C,C,T,ENST00000370801.3:c.1696G>A,p.V566I,566.0,ENST00000370801,121004,1

In [23]:
### TODO: Is this correct?
transcriptIds_proteinIds_mapping = {tid: (len(ensembl.transcript_by_id(tid).protein_sequence) if ensembl.transcript_by_id(tid).protein_sequence is not None else np.nan) for tid in dataMutation_Giannakis_cleaned['Transcript_ID'].unique()}
transcriptIds_proteinIds_mapping

INFO:pyensembl.sequence_data:Loaded sequence dictionary from /home/axel/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.pep.all.fa.gz.pickle

{'ENST00000263100': 495,
 'ENST00000373993': 594,
 'ENST00000373995': 594,
 'ENST00000318602': 1474,
 'ENST00000299698': 1454,
 'ENST00000442999': 340,
 'ENST00000249005': 353,
 'ENST00000236709': 340,
 'ENST00000209873': 546,
 'ENST00000316519': 672,
 'ENST00000232892': 399,
 'ENST00000356517': 401,
 'ENST00000359318': 350,
 'ENST00000376221': 407,
 'ENST00000337664': 425,
 'ENST00000375234': 226,
 'ENST00000261880': 315,
 'ENST00000409085': 961,
 'ENST00000393427': 122,
 'ENST00000248450': 434,
 'ENST00000392492': 207,
 'ENST00000320849': 384,
 'ENST00000378279': 155,
 'ENST00000261772': 968,
 'ENST00000244571': 985,
 'ENST00000205214': 1098,
 'ENST00000278618': 309,
 'ENST00000393376': 926,
 'ENST00000225402': 560,
 'ENST00000326724': 1374,
 'ENST00000268251': 500,
 'ENST00000374736': 2261,
 'ENST00000269081': 1543,
 'ENST00000272895': 2595,
 'ENST00000435803': 5058,
 'ENST00000341511': 2436,
 'ENST00000301732': 1704,
 'ENST00000370225': 2273,
 'ENST00000392676': 1642,
 'ENST00000284425': 1617,
 'ENST00000263094': 2146,
 'ENST00000269080': 1581,
 'ENST00000340001': 1624,
 'ENST00000265724': 1280,
 'ENST00000344517': 738,
 'ENST00000263817': 1321,
 'ENST00000265723': 1286,
 'ENST00000404938': 1257,
 'ENST00000265316': 842,
 'ENST00000373394': 752,
 'ENST00000297504': 735,
 'ENST00000280560': 766,
 'ENST00000399410': 1531,
 'ENST00000372530': 1492,
 'ENST00000356608': 1382,
 'ENST00000311303': 1359,
 'ENST00000370449': 1545,
 'ENST00000285238': 1527,
 'ENST00000376887': 1325,
 'ENST00000334444': 1437,
 'ENST00000205557': 1503,
 'ENST00000389817': 1581,
 'ENST00000261201': 1549,
 'ENST00000218104': 745,
 'ENST00000308666': 740,
 'ENST00000370214': 659,
 'ENST00000356924': 606,
 'ENST00000296577': 599,
 'ENST00000326195': 845,
 'ENST00000287844': 623,
 'ENST00000429586': 709,
 'ENST00000361802': 678,
 'ENST00000237612': 655,
 'ENST00000307417': 646,
 'ENST00000260645': 651,
 'ENST00000272286': 673,
 'ENST00000316470': 405,
 'ENST00000273359': 306,
 'ENST00000222800': 315,
 'ENST00000339157': 398,
 'ENST00000337334': 362,
 'ENST00000375898': 337,
 'ENST00000273596': 271,
 'ENST00000361143': 210,
 'ENST00000307201': 468,
 'ENST00000395952': 558,
 'ENST00000369916': 469,
 'ENST00000292577': 310,
 'ENST00000333421': 288,
 'ENST00000258884': 329,
 'ENST00000352732': 425,
 'ENST00000289119': 409,
 'ENST00000428304': 342,
 'ENST00000458276': 349,
 'ENST00000295962': 337,
 'ENST00000247706': 439,
 'ENST00000376142': 508,
 'ENST00000295851': 513,
 'ENST00000225941': 366,
 'ENST00000284322': 1075,
 'ENST00000318560': 1130,
 'ENST00000502732': 1182,
 'ENST00000277895': 778,
 'ENST00000369252': 718,
 'ENST00000341937': 611,
 'ENST00000309868': 683,
 'ENST00000302538': 859,
 'ENST00000311955': 381,
 'ENST00000367660': 81,
 'ENST00000274849': 272,
 'ENST00000232744': 478,
 'ENST00000435224': 1025,
 'ENST00000392351': 361,
 'ENST00000261377': 774,
 'ENST00000502505': 192,
 'ENST00000586572': 105,
 'ENST00000272438': 196,
 'ENST00000395384': 297,
 'ENST00000598855': 271,
 'ENST00000306708': 796,
 'ENST00000539278': 243,
 'ENST00000600109': 135,
 'ENST00000288177': 458,
 'ENST00000426194': 188,
 'ENST00000595757': 147,
 'ENST00000287139': 347,
 'ENST00000420338': 157,
 'ENST00000308961': 141,
 'ENST00000326958': 121,
 'ENST00000575889': 106,
 'ENST00000593646': 174,
 'ENST00000600087': 141,
 'ENST00000395326': 148,
 'ENST00000304874': 464,
 'ENST00000600820': 131,
 'ENST00000543018': 150,
 'ENST00000390238': 13,
 'ENST00000390240': 13,
 'ENST00000428556': 20,
 'ENST00000399413': 164,
 'ENST00000333167': 424,
 'ENST00000285093': 397,
 'ENST00000353139': 2383,
 'ENST00000338432': 2458,
 'ENST00000313698': 1059,
 'ENST00000264990': 780,
 'ENST00000281182': 415,
 'ENST00000308982': 621,
 'ENST00000233710': 430,
 'ENST00000370841': 421,
 'ENST00000242592': 412,
 'ENST00000358776': 432,
 'ENST00000356839': 655,
 'ENST00000439576': 2530,
 'ENST00000158762': 740,
 'ENST00000326793': 778,
 'ENST00000354700': 834,
 'ENST00000265838': 427,
 'ENST00000367048': 397,
 'ENST00000366812': 528,
 'ENST00000376955': 268,
 'ENST00000375888': 534,
 'ENST00000367595': 282,
 'ENST00000356189': 88,
 'ENST00000263776': 501,
 'ENST00000378832': 568,
 'ENST00000393919': 544,
 'ENST00000290866': 1306,
 'ENST00000252519': 805,
 'ENST00000301452': 264,
 'ENST00000340967': 275,
 'ENST00000532485': 267,
 'ENST00000241069': 614,
 'ENST00000262710': 1341,
 'ENST00000273145': 384,
 'ENST00000272928': 362,
 'ENST00000249887': 350,
 'ENST00000399036': 344,
 'ENST00000262483': 974,
 'ENST00000352035': 1101,
 'ENST00000356140': 336,
 'ENST00000432641': 125,
 'ENST00000309951': 889,
 'ENST00000216254': 780,
 'ENST00000311148': 421,
 'ENST00000371316': 607,
 'ENST00000307624': 555,
 'ENST00000230048': 140,
 'ENST00000238651': 483,
 'ENST00000326303': 421,
 'ENST00000381139': 207,
 'ENST00000377855': 380,
 'ENST00000217455': 319,
 'ENST00000336430': 439,
 'ENST00000301608': 660,
 'ENST00000302819': 681,
 'ENST00000356406': 700,
 'ENST00000389811': 547,
 'ENST00000272065': 158,
 'ENST00000256997': 423,
 'ENST00000218758': 325,
 'ENST00000369238': 428,
 'ENST00000286353': 480,
 'ENST00000336375': 386,
 'ENST00000351273': 418,
 'ENST00000270593': 426,
 'ENST00000216139': 421,
 'ENST00000229243': 543,
 'ENST00000373695': 691,
 'ENST00000533904': 265,
 'ENST00000258873': 724,
 'ENST00000586696': 666,
 'ENST00000300441': 615,
 'ENST00000317447': 576,
 'ENST00000281455': 698,
 'ENST00000357430': 720,
 'ENST00000340800': 711,
 'ENST00000354273': 683,
 'ENST00000379240': 697,
 'ENST00000379264': 722,
 'ENST00000307493': 577,
 'ENST00000219054': 577,
 'ENST00000329697': 577,
 'ENST00000289416': 586,
 'ENST00000399422': 580,
 'ENST00000331849': 579,
 'ENST00000323482': 689,
 'ENST00000360596': 701,
 'ENST00000548058': 686,
 'ENST00000366684': 377,
 'ENST00000224784': 377,
 'ENST00000331789': 375,
 'ENST00000423391': 376,
 'ENST00000290378': 377,
 'ENST00000331925': 375,
 'ENST00000345517': 376,
 'ENST00000330271': 245,
 'ENST00000429709': 429,
 'ENST00000160382': 426,
 'ENST00000333999': 435,
 'ENST00000374667': 415,
 'ENST00000375406': 366,
 'ENST00000324436': 416,
 'ENST00000193403': 892,
 'ENST00000366578': 894,
 'ENST00000513398': 901,
 'ENST00000252699': 911,
 'ENST00000254286': 417,
 'ENST00000369905': 376,
 'ENST00000289228': 376,
 'ENST00000260641': 394,
 'ENST00000263238': 418,
 'ENST00000256001': 418,
 'ENST00000252071': 210,
 'ENST00000243903': 607,
 'ENST00000188312': 396,
 'ENST00000335754': 624,
 'ENST00000371124': 376,
 'ENST00000378404': 377,
 'ENST00000330368': 372,
 'ENST00000263640': 509,
 'ENST00000257963': 505,
 'ENST00000243349': 493,
 'ENST00000241416': 513,
 'ENST00000352511': 512,
 'ENST00000388922': 503,
 'ENST00000404366': 408,
 'ENST00000255082': 319,
 'ENST00000238618': 99,
 'ENST00000394666': 99,
 'ENST00000372874': 363,
 'ENST00000296513': 576,
 'ENST00000315906': 583,
 'ENST00000562188': 355,
 'ENST00000260408': 748,
 'ENST00000200557': 769,
 'ENST00000368679': 909,
 'ENST00000356955': 863,
 'ENST00000310823': 824,
 'ENST00000265707': 739,
 'ENST00000517905': 955,
 'ENST00000265708': 735,
 'ENST00000256389': 776,
 'ENST00000603540': 722,
 'ENST00000265727': 906,
 'ENST00000264377': 832,
 'ENST00000265769': 775,
 'ENST00000359240': 820,
 'ENST00000369400': 790,
 'ENST00000379907': 787,
 'ENST00000356518': 813,
 'ENST00000175238': 754,
 'ENST00000445355': 824,
 'ENST00000487273': 819,
 'ENST00000256412': 470,
 'ENST00000284984': 967,
 'ENST00000597188': 1103,
 'ENST00000504830': 1594,
 'ENST00000371929': 1427,
 'ENST00000373207': 1223,
 'ENST00000299164': 950,
 'ENST00000274181': 1224,
 'ENST00000268070': 1095,
 'ENST00000282849': 1221,
 'ENST00000274487': 1207,
 'ENST00000251582': 1211,
 'ENST00000389420': 1910,
 'ENST00000286657': 1205,
 'ENST00000367996': 837,
 'ENST00000284987': 930,
 'ENST00000381055': 1117,
 'ENST00000388820': 1686,
 'ENST00000257359': 889,
 'ENST00000498707': 1935,
 'ENST00000380548': 1762,
 'ENST00000354484': 951,
 'ENST00000286744': 1691,
 'ENST00000271643': 1074,
 'ENST00000330475': 471,
 'ENST00000265846': 374,
 'ENST00000330889': 381,
 'ENST00000368474': 1226,
 'ENST00000292205': 1269,
 'ENST00000360697': 741,
 'ENST00000381312': 739,
 'ENST00000307921': 502,
 'ENST00000237283': 191,
 'ENST00000602400': 351,
 'ENST00000294517': 460,
 'ENST00000238561': 523,
 'ENST00000072869': 626,
 'ENST00000366777': 647,
 'ENST00000324464': 544,
 'ENST00000308860': 580,
 'ENST00000297323': 1119,
 'ENST00000367851': 1610,
 'ENST00000338316': 1091,
 'ENST00000260600': 1144,
 'ENST00000310677': 1077,
 'ENST00000462833': 1261,
 'ENST00000307885': 1168,
 'ENST00000254235': 1080,
 'ENST00000286355': 1251,
 'ENST00000294016': 1353,
 'ENST00000450565': 176,
 'ENST00000304166': 468,
 'ENST00000398129': 737,
 'ENST00000264436': 726,
 'ENST00000356080': 706,
 'ENST00000209668': 375,
 'ENST00000305046': 375,
 'ENST00000515683': 375,
 'ENST00000265512': 380,
 'ENST00000296412': 374,
 'ENST00000237653': 368,
 'ENST00000209665': 386,
 'ENST00000396623': 467,
 'ENST00000327435': 179,
 'ENST00000320741': 244,
 'ENST00000340990': 375,
 'ENST00000357103': 386,
 'ENST00000372013': 76,
 'ENST00000286621': 362,
 'ENST00000278175': 185,
 'ENST00000395737': 148,
 'ENST00000420022': 153,
 'ENST00000349014': 1102,
 'ENST00000262198': 1131,
 'ENST00000373783': 270,
 'ENST00000309502': 326,
 'ENST00000337539': 412,
 'ENST00000304222': 332,
 'ENST00000241356': 318,
 'ENST00000369717': 266,
 'ENST00000311669': 496,
 'ENST00000357003': 357,
 'ENST00000375418': 354,
 'ENST00000373178': 363,
 'ENST00000379774': 342,
 'ENST00000276393': 466,
 'ENST00000306675': 520,
 'ENST00000379453': 572,
 'ENST00000280155': 465,
 'ENST00000409345': 447,
 'ENST00000330055': 462,
 'ENST00000369295': 477,
 'ENST00000305988': 413,
 'ENST00000345060': 408,
 'ENST00000308595': 689,
 'ENST00000324198': 688,
 'ENST00000253003': 407,
 'ENST00000216194': 484,
 'ENST00000366535': 456,
 'ENST00000330877': 457,
 'ENST00000414691': 230,
 'ENST00000390477': 154,
 'ENST00000390469': 115,
 'ENST00000223357': 1158,
 'ENST00000398864': 517,
 'ENST00000332810': 325,
 'ENST00000327141': 197,
 'ENST00000358461': 730,
 'ENST00000296721': 768,
 'ENST00000304129': 818,
 'ENST00000307808': 1210,
 'ENST00000370460': 1311,
 'ENST00000409236': 1226,
 'ENST00000265343': 1163,
 'ENST00000269143': 797,
 'ENST00000226355': 599,
 'ENST00000409257': 303,
 'ENST00000395792': 609,
 'ENST00000238855': 936,
 'ENST00000264595': 346,
 'ENST00000304032': 857,
 'ENST00000413193': 703,
 'ENST00000547588': 1192,
 'ENST00000542466': 268,
 'ENST00000397238': 911,
 'ENST00000448048': 663,
 'ENST00000374094': 686,
 'ENST00000374056': 663,
 'ENST00000374095': 663,
 'ENST00000441037': 1066,
 'ENST00000525123': 902,
 'ENST00000371839': 503,
 'ENST00000360131': 886,
 'ENST00000375076': 404,
 'ENST00000310078': 562,
 'ENST00000300176': 481,
 'ENST00000312916': 714,
 'ENST00000355413': 422,
 'ENST00000294724': 1532,
 'ENST00000375826': 352,
 'ENST00000342526': 445,
 'ENST00000373204': 857,
 'ENST00000220592': 859,
 'ENST00000373191': 860,
 'ENST00000373210': 861,
 'ENST00000336984': 283,
 'ENST00000371696': 278,
 'ENST00000291572': 376,
 'ENST00000320285': 378,
 'ENST00000285518': 364,
 'ENST00000396987': 456,
 'ENST00000264409': 434,
 'ENST00000264167': 658,
 'ENST00000419304': 175,
 'ENST00000310398': 166,
 'ENST00000379370': 2045,
 'ENST00000290953': 132,
 'ENST00000366667': 485,
 'ENST00000357081': 1226,
 'ENST00000349243': 359,
 'ENST00000371906': 363,
 'ENST00000314340': 159,
 'ENST00000307503': 392,
 'ENST00000231420': 514,
 'ENST00000326225': 2275,
 'ENST00000217426': 432,
 'ENST00000369799': 530,
 'ENST00000325006': 611,
 'ENST00000247087': 1603,
 'ENST00000265602': 1196,
 'ENST00000378024': 5890,
 'ENST00000333244': 5795,
 'ENST00000242057': 848,
 'ENST00000505113': 701,
 'ENST00000216479': 338,
 'ENST00000411641': 367,
 'ENST00000302312': 102,
 'ENST00000229335': 198,
 'ENST00000340020': 306,
 'ENST00000376059': 147,
 'ENST00000247291': 150,
 'ENST00000287295': 613,
 'ENST00000307864': 373,
 'ENST00000399167': 605,
 'ENST00000275235': 245,
 'ENST00000369066': 1723,
 'ENST00000308182': 616,
 'ENST00000368130': 343,
 'ENST00000358008': 312,
 'ENST00000223029': 320,
 'ENST00000279146': 330,
 'ENST00000381129': 384,
 'ENST00000291582': 545,
 'ENST00000378190': 411,
 'ENST00000262713': 538,
 'ENST00000373156': 194,
 'ENST00000354858': 239,
 'ENST00000381809': 227,
 'ENST00000327299': 223,
 'ENST00000354567': 562,
 'ENST00000267584': 723,
 'ENST00000298545': 479,
 'ENST00000424296': 1911,
 'ENST00000337714': 903,
 'ENST00000225737': 662,
 'ENST00000025301': 1901,
 'ENST00000253332': 1782,
 'ENST00000394518': 2813,
 'ENST00000371431': 197,
 'ENST00000313871': 695,
 'ENST00000259318': 859,
 'ENST00000228850': 853,
 'ENST00000358526': 854,
 'ENST00000320636': 427,
 'ENST00000280979': 2319,
 'ENST00000431975': 348,
 'ENST00000269701': 692,
 'ENST00000397410': 646,
 'ENST00000356239': 3907,
 'ENST00000432648': 192,
 'ENST00000257787': 203,
 'ENST00000307564': 1439,
 'ENST00000370001': 836,
 'ENST00000351829': 325,
 'ENST00000285930': 316,
 'ENST00000359579': 316,
 'ENST00000457545': 344,
 'ENST00000380872': 323,
 'ENST00000380753': 323,
 'ENST00000380554': 323,
 'ENST00000263126': 323,
 'ENST00000488756': 152,
 'ENST00000242375': 326,
 'ENST00000298375': 320,
 'ENST00000235835': 359,
 'ENST00000361640': 331,
 'ENST00000420396': 153,
 'ENST00000349310': 480,
 'ENST00000344175': 256,
 'ENST00000392038': 481,
 'ENST00000263826': 479,
 'ENST00000394657': 292,
 'ENST00000594544': 27,
 'ENST00000596306': 148,
 'ENST00000538322': 375,
 'ENST00000453638': 129,
 'ENST00000558378': 136,
 'ENST00000594609': 76,
 'ENST00000409155': 330,
 'ENST00000310271': 640,
 'ENST00000330807': 587,
 'ENST00000295897': 609,
 'ENST00000306107': 583,
 'ENST00000293350': 802,
 'ENST00000371224': 795,
 'ENST00000297785': 501,
 'ENST00000249750': 518,
 'ENST00000329841': 512,
 'ENST00000377698': 517,
 'ENST00000393434': 902,
 'ENST00000258494': 923,
 'ENST00000261733': 517,
 'ENST00000225740': 453,
 'ENST00000176643': 485,
 'ENST00000342456': 429,
 'ENST00000349015': 385,
 'ENST00000290597': 563,
 'ENST00000357578': 535,
 'ENST00000553458': 535,
 'ENST00000409134': 539,
 'ENST00000265605': 487,
 'ENST00000354775': 518,
 'ENST00000338110': 364,
 'ENST00000374855': 364,
 'ENST00000226253': 364,
 'ENST00000262374': 464,
 'ENST00000266483': 473,
 'ENST00000308742': 473,
 'ENST00000521508': 492,
 'ENST00000330817': 488,
 'ENST00000394780': 1137,
 'ENST00000370205': 216,
 'ENST00000340333': 187,
 'ENST00000476832': 416,
 'ENST00000397676': 438,
 'ENST00000239891': 324,
 'ENST00000371108': 507,
 'ENST00000299626': 526,
 'ENST00000531154': 447,
 'ENST00000260257': 624,
 'ENST00000389048': 1620,
 'ENST00000216489': 389,
 'ENST00000343075': 261,
 'ENST00000302708': 286,
 'ENST00000292566': 302,
 'ENST00000399138': 394,
 'ENST00000252984': 238,
 'ENST00000245812': 221,
 'ENST00000389568': 664,
 'ENST00000252505': 391,
 'ENST00000264448': 4167,
 'ENST00000251535': 663,
 'ENST00000319144': 701,
 'ENST00000293761': 662,
 'ENST00000380183': 676,
 'ENST00000374391': 674,
 'ENST00000380490': 161,
 'ENST00000448843': 711,
 'ENST00000295463': 528,
 'ENST00000177648': 1244,
 'ENST00000361673': 2170,
 'ENST00000258888': 1907,
 'ENST00000374832': 524,
 'ENST00000392027': 535,
 'ENST00000295453': 532,
 'ENST00000264276': 1657,
 'ENST00000318962': 953,
 'ENST00000286195': 623,
 'ENST00000286190': 445,
 'ENST00000316824': 326,
 'ENST00000369792': 343,
 'ENST00000329255': 411,
 'ENST00000331204': 257,
 'ENST00000335606': 382,
 'ENST00000322937': 447,
 'ENST00000265132': 352,
 'ENST00000458649': 1298,
 'ENST00000368885': 334,
 'ENST00000266736': 426,
 'ENST00000293971': 409,
 'ENST00000567119': 247,
 'ENST00000380714': 191,
 'ENST00000383036': 206,
 'ENST00000330258': 1135,
 'ENST00000515384': 671,
 'ENST00000321420': 861,
 'ENST00000290649': 643,
 'ENST00000221496': 560,
 'ENST00000257863': 573,
 'ENST00000356289': 394,
 'ENST00000369862': 493,
 'ENST00000266581': 522,
 'ENST00000320431': 504,
 'ENST00000262844': 333,
 'ENST00000272647': 310,
 'ENST00000299155': 453,
 'ENST00000281471': 258,
 'ENST00000371959': 1084,
 'ENST00000433060': 956,
 'ENST00000422605': 779,
 'ENST00000520113': 780,
 'ENST00000256578': 879,
 'ENST00000396553': 767,
 'ENST00000356264': 695,
 'ENST00000273588': 403,
 'ENST00000370079': 511,
 'ENST00000414303': 511,
 'ENST00000361355': 511,
 'ENST00000312371': 498,
 'ENST00000359904': 360,
 'ENST00000341068': 1944,
 'ENST00000309439': 185,
 'ENST00000344877': 84,
 'ENST00000354910': 74,
 'ENST00000227618': 121,
 'ENST00000299381': 110,
 'ENST00000323927': 822,
 'ENST00000315368': 808,
 'ENST00000261819': 755,
 'ENST00000455511': 599,
 'ENST00000336811': 147,
 'ENST00000251089': 670,
 'ENST00000366962': 544,
 'ENST00000517746': 498,
 'ENST00000325203': 496,
 'ENST00000381922': 503,
 'ENST00000234816': 491,
 'ENST00000373425': 493,
 'ENST00000371129': 460,
 'ENST00000301455': 406,
 'ENST00000334289': 388,
 'ENST00000253109': 470,
 'ENST00000376819': 346,
 'ENST00000347528': 1881,
 'ENST00000265709': 1897,
 'ENST00000357077': 3957,
 'ENST00000280772': 4377,
 'ENST00000313581': 1434,
 'ENST00000380230': 522,
 'ENST00000378380': 776,
 'ENST00000318698': 763,
 'ENST00000341657': 1169,
 'ENST00000284268': 492,
 'ENST00000360839': 2542,
 'ENST00000297183': 2617,
 'ENST00000265742': 1089,
 'ENST00000303941': 765,
 'ENST00000394458': 615,
 'ENST00000357997': 938,
 'ENST00000272972': 941,
 'ENST00000306999': 441,
 'ENST00000296785': 313,
 'ENST00000371697': 319,
 'ENST00000267339': 420,
 'ENST00000301030': 2663,
 'ENST00000262126': 2062,
 'ENST00000261739': 590,
 'ENST00000394859': 626,
 'ENST00000370944': 541,
 'ENST00000308440': 518,
 'ENST00000380092': 361,
 'ENST00000358602': 2603,
 'ENST00000399703': 992,
 'ENST00000307518': 360,
 'ENST00000377477': 823,
 'ENST00000377601': 823,
 'ENST00000357336': 823,
 'ENST00000371930': 191,
 'ENST00000318357': 305,
 'ENST00000318934': 1146,
 'ENST00000376087': 1710,
 'ENST00000306065': 1050,
 'ENST00000399451': 1053,
 'ENST00000592179': 301,
 'ENST00000361713': 1341,
 'ENST00000358984': 1392,
 'ENST00000265140': 1058,
 'ENST00000340970': 272,
 'ENST00000323397': 496,
 'ENST00000338682': 514,
 'ENST00000355594': 1001,
 'ENST00000420699': 1941,
 'ENST00000456556': 1778,
 'ENST00000335174': 158,
 'ENST00000393537': 183,
 'ENST00000285243': 368,
 'ENST00000393392': 389,
 'ENST00000282272': 985,
 'ENST00000333279': 266,
 'ENST00000520552': 232,
 'ENST00000302755': 239,
 'ENST00000504087': 1429,
 'ENST00000267116': 1076,
 'ENST00000360589': 530,
 'ENST00000215941': 300,
 'ENST00000341048': 614,
 'ENST00000339746': 727,
 'ENST00000265224': 254,
 'ENST00000286918': 317,
 'ENST00000360359': 1134,
 'ENST00000547776': 1248,
 'ENST00000304283': 656,
 'ENST00000311620': 417,
 'ENST00000353234': 871,
 'ENST00000323348': 726,
 'ENST00000265748': 1124,
 'ENST00000355303': 986,
 'ENST00000292246': 660,
 'ENST00000356134': 999,
 'ENST00000256737': 981,
 'ENST00000392977': 955,
 'ENST00000324559': 913,
 'ENST00000320560': 910,
 'ENST00000274979': 933,
 'ENST00000159087': 1232,
 'ENST00000332826': 782,
 'ENST00000465139': 249,
 'ENST00000339399': 251,
 'ENST00000266594': 131,
 'ENST00000314136': 268,
 'ENST00000300060': 967,
 'ENST00000303714': 564,
 'ENST00000307333': 489,
 'ENST00000257497': 346,
 'ENST00000359299': 324,
 'ENST00000372231': 505,
 'ENST00000419625': 316,
 'ENST00000396024': 339,
 'ENST00000314890': 193,
 'ENST00000264908': 323,
 'ENST00000394295': 321,
 'ENST00000296511': 320,
 'ENST00000354546': 673,
 'ENST00000372919': 488,
 'ENST00000374277': 327,
 'ENST00000368947': 345,
 'ENST00000258749': 575,
 'ENST00000360937': 751,
 'ENST00000253799': 756,
 'ENST00000308423': 763,
 'ENST00000374700': 1338,
 'ENST00000342136': 515,
 'ENST00000600612': 127,
 'ENST00000274000': 302,
 'ENST00000405198': 949,
 'ENST00000299980': 822,
 'ENST00000308724': 785,
 'ENST00000291439': 423,
 'ENST00000250244': 423,
 'ENST00000337619': 158,
 'ENST00000329235': 157,

In [24]:
dataMutation_Giannakis_cleaned['Protein_Length'] = dataMutation_Giannakis_cleaned['Transcript_ID'].map(transcriptIds_proteinIds_mapping)
dataMutation_Giannakis_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,coadread_dfci_2016_1231,A1BG,A1BG,19,58862793,58862793,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100,8322,1,495
1,coadread_dfci_2016_1231,A1BG,A1BG,19,58862794,58862794,+,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100,8322,1,495
2,coadread_dfci_2016_2269,A1BG,A1BG,19,58862775,58862775,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.892G>A,p.E298K,298.0,ENST00000263100,8322,1,495
3,coadread_dfci_2016_230737,A1BG,A1BG,19,58858744,58858744,+,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100,8322,1,495
4,coadread_dfci_2016_2429,A1BG,A1BG,19,58862934,58862934,+,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100,8322,1,495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331415,coadread_dfci_2016_3263,ZZZ3,ZZZ3,1,78097977,78097977,+,Missense_Mutation,SNP,A,A,G,ENST00000370801.3:c.1063T>C,p.S355P,355.0,ENST00000370801,121004,1,903
331416,coadread_dfci_2016_335135,ZZZ3,ZZZ3,1,78098938,78098938,+,Silent,SNP,C,C,T,ENST00000370801.3:c.102G>A,p.A34=,34.0,ENST00000370801,121004,1,903
331418,coadread_dfci_2016_430,ZZZ3,ZZZ3,1,78098587,78098587,+,Silent,SNP,C,C,T,ENST00000370801.3:c.453G>A,p.V151=,151.0,ENST00000370801,121004,1,903
331420,coadread_dfci_2016_50,ZZZ3,ZZZ3,1,78031395,78031395,+,Missense_Mutation,SNP,C,C,G,ENST00000370801.3:c.2642G>C,p.R881T,881.0,ENST00000370801,121004,1,903
331421,coadread_dfci_2016_613,ZZZ3,ZZZ3,1,78047760,78047760,+,Missense_Mutation,SNP,C,C,T,ENST00000370801.3:c.1696G>A,p.V566I,566.0,ENST00000370801,121004,1,903

In [25]:
dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Protein_Length'].isna()]

Empty DataFrame
Columns: [Tumor_Sample_Barcode, Hugo_Symbol, original_Hugo_Symbol, Chromosome, Start_Position, End_Position, Strand, Variant_Classification, Variant_Type, Reference_Allele, Tumor_Seq_Allele1, Tumor_Seq_Allele2, HGVSc, HGVSp_Short, Protein_position, Transcript_ID, Gene_Length, Mutation_Length, Protein_Length]
Index: []

In [26]:
### TODO: What to do with nan protein length? for now remove
dataMutation_Giannakis_cleaned = dataMutation_Giannakis_cleaned[~dataMutation_Giannakis_cleaned['Protein_Length'].isna()]

In [27]:
dataMutation_Giannakis_cleaned[dataMutation_Giannakis_cleaned['Protein_Length'].isna()]

Empty DataFrame
Columns: [Tumor_Sample_Barcode, Hugo_Symbol, original_Hugo_Symbol, Chromosome, Start_Position, End_Position, Strand, Variant_Classification, Variant_Type, Reference_Allele, Tumor_Seq_Allele1, Tumor_Seq_Allele2, HGVSc, HGVSp_Short, Protein_position, Transcript_ID, Gene_Length, Mutation_Length, Protein_Length]
Index: []

In [28]:
#save cleaned data
dataMutation_Giannakis_cleaned.to_csv(data['Giannakis_all___mutations'], sep="\t", index=False)

In [29]:
# clean memory
del dataMutation_Giannakis, dataMutation_Giannakis_nona, dataMutation_Giannakis_cleaned

### Clinical Samples

In [30]:
dataClinicalSample_Giannakis = pd.read_csv(data['original___Giannakis___samples'], sep='\t', engine='python', comment='#')

In [31]:
dataClinicalSample_Giannakis

,SAMPLE_ID,PATIENT_ID,TUMOR_STAGE,TUMOR_PURITY,PRIMARY_TUMOR_GRADE,MSI_STATUS,CIMP_CATEGORY,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS
0,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
1,coadread_dfci_2016_593,coadread_dfci_2016_593,II,NaN,Well-Moderate,NaN,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
2,coadread_dfci_2016_2269,coadread_dfci_2016_2269,I,60.0,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
3,coadread_dfci_2016_578,coadread_dfci_2016_578,II,NaN,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
4,coadread_dfci_2016_3021,coadread_dfci_2016_3021,III,NaN,Well-Moderate,MSI-high,CIMP-high,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
...,...,...,...,...,...,...,...,...,...,...,...
614,coadread_dfci_2016_283,coadread_dfci_2016_283,NaN,NaN,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
615,coadread_dfci_2016_3242,coadread_dfci_2016_3242,III,33.0,Well-Moderate,NaN,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
616,coadread_dfci_2016_2262,coadread_dfci_2016_2262,NaN,20.0,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
617,coadread_dfci_2016_3512,coadread_dfci_2016_3512,III,33.0,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
618,coadread_dfci_2016_2997,coadread_dfci_2016_2997,II,55.0,Well-Moderate,MSS,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched

In [32]:
dataClinicalSample_Giannakis.to_csv(data['Giannakis_all___samples'], sep='\t', index=False)

In [33]:
del dataClinicalSample_Giannakis

## Seshagiri

### Mutation

In [34]:
dataMutation_Seshagiri = pd.read_csv(data['original___Seshagiri___mutations'], sep='\t', engine='python', comment='#')

In [35]:
dataMutation_Seshagiri

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,dbSNP_RS,dbSNP_Val_Status,Tumor_Sample_Barcode,Matched_Norm_Sample_Barcode,Match_Norm_Seq_Allele1,Match_Norm_Seq_Allele2,Tumor_Validation_Allele1,Tumor_Validation_Allele2,Match_Norm_Validation_Allele1,Match_Norm_Validation_Allele2,Verification_Status,Validation_Status,Mutation_Status,Sequencing_Phase,Sequence_Source,Validation_Method,Score,BAM_File,Sequencer,t_ref_count,t_alt_count,n_ref_count,n_alt_count,HGVSc,HGVSp,HGVSp_Short,Transcript_ID,RefSeq,Protein_position,Codons,Hotspot,ALLELE_NUM,PICK,UNIPARC,n_depth,ONCOTATOR_TRANSCRIPT_CHANGE_BEST_EFFECT,MA:link.PDB,Feature,CLIN_SIG,ONCOTATOR_DBSNP_RS,Gene,HGNC_ID,ExAC_AF_AMR,t_depth,MA:FIS,ONCOTATOR_REFSEQ_MRNA_ID_BEST_EFFECT,ONCOTATOR_CODON_CHANGE_BEST_EFFECT,DISTANCE,SYMBOL_SOURCE,ONCOTATOR_PROTEIN_POS_END,Existing_variation,SYMBOL,ExAC_AF_SAS,VARIANT_CLASS,AA_MAF,HIGH_INF_POS,GENE_PHENO,ExAC_AF_AFR,ASN_MAF,PHENO,ONCOTATOR_VARIANT_CLASSIFICATION,BIOTYPE,MA:link.var,AFR_MAF,DOMAINS,MOTIF_SCORE_CHANGE,ONCOTATOR_UNIPROT_ENTRY_NAME,ONCOTATOR_TRANSCRIPT_CHANGE,Amino_acids,ONCOTATOR_REFSEQ_PROT_ID_BEST_EFFECT,EA_MAF,Allele,MA:FImpact,cDNA_position,ExAC_AF_NFE,ONCOTATOR_PROTEIN_POS_END_BEST_EFFECT,ONCOTATOR_PROTEIN_CHANGE_BEST_EFFECT,MA:link.MSA,SIFT,ONCOTATOR_GENE_SYMBOL_BEST_EFFECT,INTRON,ONCOTATOR_EXON_AFFECTED,TREMBL,AMR_MAF,sequence_by,ONCOTATOR_UNIPROT_ACCESSION_BEST_EFFECT,EAS_MAF,ONCOTATOR_PROTEIN_POS_START,CANONICAL,all_effects,ExAC_AF_EAS,GMAF,MOTIF_NAME,TSL,SOMATIC,MOTIF_POS,IMPACT,CDS_position,ONCOTATOR_DBSNP_VAL_STATUS,MA:protein.change,ONCOTATOR_COSMIC_OVERLAPPING,ONCOTATOR_REFSEQ_MRNA_ID,ONCOTATOR_CODON_CHANGE,ONCOTATOR_PROTEIN_CHANGE,ONCOTATOR_VARIANT_CLASSIFICATION_BEST_EFFECT,ONCOTATOR_EXON_AFFECTED_BEST_EFFECT,ONCOTATOR_GENE_SYMBOL,SWISSPROT,ExAC_AF_FIN,EUR_MAF,Feature_type,HGVS_OFFSET,PolyPhen,FILTER,Protein_Change,ONCOTATOR_UNIPROT_ENTRY_NAME_BEST_EFFECT,ENSP,ExAC_AF,ONCOTATOR_REFSEQ_PROT_ID,CCDS,protein_change,EXON,ExAC_AF_OTH,SAS_MAF,ONCOTATOR_PROTEIN_POS_START_BEST_EFFECT,Exon_Number,MINIMISED,ONCOTATOR_UNIPROT_ACCESSION,PUBMED,Sequence_By
0,A1CF,0,Genentech,GRCh37,10,52573792,52573792,+,missense_variant,Missense_Mutation,SNP,G,G,A,NaN,NaN,587220,NORMAL,G,G,NaN,NaN,NaN,NaN,NaN,VALIDATED,NaN,NaN,NaN,RNASeq,NaN,NaN,NaN,.,.,.,.,ENST00000373993.1:c.1172C>T,p.Ala391Val,p.A391V,ENST00000373993,NaN,391.0,gCg/gTg,0,1,NaN,UPI0000071BDE,0,NaN,NaN,ENST00000373993,NaN,NaN,ENSG00000148584,24086.0,NaN,0,2.005,NaN,NaN,NaN,HGNC,NaN,"rs757450367,COSM1181106,COSM1181105",A1CF,0.000121,SNV,NaN,NaN,NaN,NaN,NaN,"0,1,1",NaN,protein_coding,"getma.org/?cm=var&var=hg19,10,52573792,G,A&fts...",NaN,"hmmpanther:PTHR24012,hmmpanther:PTHR24012:SF31...",NaN,NaN,NaN,A/V,NaN,NaN,A,medium,1217/1997,0.000015,NaN,NaN,getma.org/?cm=msa&ty=f&p=A1CF_HUMAN&rb=298&re=...,deleterious(0.01),NaN,NaN,NaN,"Q7Z2U9_HUMAN,Q5T0W7_HUMAN",NaN,NaN,NaN,NaN,NaN,NaN,"A1CF,missense_variant,p.Ala383Val,ENST00000374...",0.000350,NaN,NaN,NaN,"0,1,1",NaN,MODERATE,1172/1785,NaN,A391V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A1CF_HUMAN,NaN,NaN,Transcript,NaN,probably_damaging(0.974),.,A391V,NaN,ENSP00000363105,0.000049,NaN,CCDS7242.1,A391V,8/11,NaN,NaN,NaN,8/11,1,NaN,NaN,NaN
1,A4GALT,0,Genentech,GRCh37,22,43089044,43089044,+,missense_variant,Missense_Mutation,SNP,G,G,A,NaN,NaN,587220,NORMAL,G,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.,.,.,.,ENST00000249005.2:c.914C>T,p.Pro305Leu,p.P305L,ENST00000249005,NM_017436.4,305.0,cCg/cTg,0,1,NaN,UPI000003FF92,0,NaN,NaN,ENST00000249005,NaN,NaN,ENSG00000128274,18149.0,0.000087,0,-0.345,NaN,NaN,NaN,HGNC,NaN,"rs138153636,COSM1181127",A4GALT,NaN,SNV,A:0.0009,NaN,1.0,0.000968,NaN,"0,1",NaN,protein_coding,"getma.org/?cm=var&var=hg19,22,43089044,G,A&fts...",A:0.0008,"Superfamily_domains:SSF53448,Pfam_domain:PF045...",NaN,NaN,NaN,P/L,NaN,A:0,A,neutral,1103/2020,0.000106,NaN,NaN,getma.org/?cm=msa&ty=f&p=A4GAT_HUMAN&rb=221&re...,tolerated(0.3),NaN,NaN,NaN,"S6CQT5_HUMAN,S6CPX2_HUMAN,M1KVK7_HUMAN,Q7Z2I1_...",A:0,NaN,NaN,A:0,NaN,NaN,"A4GALT,missense_variant,p.Pro305Leu,ENST000004...",0.000116,A:0.0002,NaN,NaN,"0,1",NaN,MODERATE,914/1062,NaN,P305L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A4GAT_HUMAN,NaN,A:0,Transcript,NaN,benign(0.051),common_variant,P305L,NaN,ENSP00000249005,0.000157,NaN,CCDS14041.1,P305L,2/2,NaN,A:0,NaN,2/2,1,NaN,NaN,NaN
2,AARS2,0,Genentech,GRCh37,6,44272932,44272932,+,missense_variant,Missense_Mutation,SNP,G,G,A,NaN,NaN,587220,NORMAL,G,G,NaN,NaN,NaN,NaN,NaN,VALIDATED,NaN,NaN,NaN,RNASeq,NaN,NaN,NaN,.,.,.,.,ENST00000244571.4:c.1438C>T,p.Arg480Trp,p.R480W,ENST00000244571,NM_020745.3,480.0,Cgg/Tgg,0,1,1.0,UPI00001C1E5A,0,NaN,getma.org/pdb.php?prot=SYAM_HUMAN&from=41&to=6...,ENST00000244571,NaN,NaN,ENSG00000124608,21022.0,NaN,0,3.460,NaN,NaN,NaN,HGNC,NaN,"rs201164609,COSM1181158",AARS2,NaN,SNV,A:0,NaN,1.0,NaN,NaN,"0,1",NaN,protein_coding,"getma.org/?cm=var&var=hg19,6,44272932,G,A&fts=all",NaN,"Superfamily_domains:0049182,HAMAP:MF_00036_B,P...",NaN,NaN,NaN,R/W,NaN,A:0.0002,A,medium,1441/3854,0.000706,NaN,NaN,getma.org/?cm=msa&ty=f&p=SYAM_HUMAN&rb=41&re=6...,deleterious(0.01),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YES,"AARS2,missense_variant,p.Arg480Trp,ENST0000024...",NaN,NaN,NaN,NaN,"0,1",NaN,MODERATE,1438/2958,NaN,R480W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYAM_HUMAN,0.000303,NaN,Transcript,NaN,probably_damaging(0.912),common_variant,R480W,NaN,ENSP00000244571,0.000412,NaN,CCDS34464.1,R480W,11/22,NaN,NaN,NaN,11/22,1,NaN,NaN,NaN
3,ABCA1,0,Genentech,GRCh37,9,107620834,107620834,+,missense_variant,Missense_Mutation,SNP,C,C,T,NaN,NaN,587220,NORMAL,C,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.,.,.,.,ENST00000374736.3:c.689G>A,p.Arg230His,p.R230H,ENST00000374736,NM_005502.3,230.0,cGt/cAt,0,1,1.0,UPI000013E441,0,NaN,NaN,ENST00000374736,NaN,NaN,ENSG00000165029,29.0,NaN,0,1.790,NaN,NaN,NaN,HGNC,NaN,"rs767710036,COSM1181183",ABCA1,0.000061,SNV,NaN,NaN,1.0,0.000096,NaN,"0,1",NaN,protein_coding,"getma.org/?cm=var&var=hg19,9,107620834,C,T&fts...",NaN,"hmmpanther:PTHR19229:SF34,hmmpanther:PTHR19229",NaN,NaN,NaN,R/H,NaN,NaN,T,low,1084/10494,0.000015,NaN,NaN,getma.org/?cm=msa&ty=f&p=ABCA1_HUMAN&rb=201&re...,tolerated(0.18),NaN,NaN,NaN,"Q9NS76_HUMAN,Q9NP93_HUMAN,Q9H002_HUMAN",NaN,NaN,NaN,NaN,NaN,YES,"ABCA1,missense_variant,p.Arg230His,ENST0000037...",NaN,NaN,NaN,NaN,"0,1",NaN,MODERATE,689/6786,NaN,R230H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABCA1_HUMAN,NaN,NaN,Transcript,NaN,benign(0),.,R230H,NaN,ENSP00000363868,0.000025,NaN,CCDS6762.1,R230H,7/50,NaN,NaN,NaN,7/50,1,NaN,NaN,NaN
4,ABCA12,0,Genentech,GRCh37,2,215840638,215840638,+,missense_variant,Missense_Mutation,SNP,A,A,G,NaN,NaN,587220,NORMAL,A,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.,.,.,.,ENST00000272895.7:c.5252T>C,p.Val1751Ala,p.V1751A,ENST00000272895,NM_173076.2,1751.0,gTt/gCt,0,1,1.0,UPI000019AB7A,0,NaN,NaN,ENST00000272895,NaN,NaN,ENSG00000144452,14637.0,NaN,0,2.045,NaN,NaN,NaN,HGNC,NaN,COSM1181203,ABCA12,NaN,SNV,NaN,NaN,1.0,NaN,NaN,1,NaN,protein_coding,"getma.org/?cm=var&var=hg19,2,215840638,A,G&fts...",NaN,"Pfam_domain:PF12698,hmmpanther:PTHR19229:SF29,...",NaN,NaN,NaN,V/A,NaN,NaN,G,medium,5472/9100,NaN,NaN,NaN,getma.org/?cm=msa&ty=f&p=ABCAC_HUMAN&rb=1744&r...,deleterious(0),NaN,NaN,NaN,A0SYP7_HUMAN,NaN,NaN,NaN,NaN,NaN,YES,"ABCA12,missense_variant,p.Val1751Ala,ENST00000...",NaN,NaN,NaN,NaN,1,NaN,MODERATE,5252/7788,NaN,V1751A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABCAC_HUMAN,NaN,NaN,Transcript,NaN,possibly_damaging(0.626),.,V1753A,NaN,ENSP00000272895,NaN,NaN,CCDS33372.1,V1753A,34/53,NaN,NaN,NaN,34/53,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36266,WRNIP1,0,Genentech,GRCh37,6,2766302,2766302,+,missense_variant,Missense_Mutation,SNP,C,C,A,NaN,NaN,587400,NORMAL,C,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.,.,.,.,ENST00000380773.4:c.446C>A,p.Ala149Glu,p.A149E,ENST00000380773,NM_020135.2,149.0,gCg/gAg,0,1,1.0,UPI000004A506,0,NaN,NaN,ENST00000380773,NaN,NaN,ENSG00000124535,20876.0,NaN,0,0.345,NaN,NaN,NaN,HGNC,NaN,COSM1232856,WRNIP1,NaN,SNV,NaN,NaN,NaN,NaN,NaN,1,NaN,protein_coding,"getma.org/?cm=var&var=hg19,6,2766302,C,A&fts=all",NaN,"Low_complexity_(Seg):seg,hmmpanther:PTHR13779:...",NaN,NaN,NaN,A/E,NaN,NaN,A,neutral,655/2670,NaN,NaN,NaN,getma.org/?cm=msa&ty=f&p=WRIP1_HUMAN&rb=1&re=2...,tolerated_low_confidence(0.26),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YES,"WRNIP1,missense_variant,p.Ala149Glu,ENST000003...",NaN,NaN,NaN,NaN,1,NaN,MODERATE,446/1998,NaN,A149E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WRIP1_HUMAN,NaN,NaN,Transcript,NaN,possibly_damaging(0.726),.,A149E,NaN,ENSP00000370150,NaN,NaN,CCDS4475.1,A149E,1/7,NaN,NaN,NaN,1/7,1,NaN,NaN,NaN
36267,XKRX,0,Genentech,GRCh37,X,100183004,100183004,+,missense_variant,Missense_Mutation,SNP,G,G,A,NaN,NaN,587400,NORMAL,G,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.,.,.,.,ENST00000372956.2:c.290C>T,p.Pro97Leu,p.P97L,ENST00000372956,NaN,97.0,cCg/cTg,0,1,1.0,UPI00001A7F30,0,NaN,NaN,ENST00000372956,NaN,NaN,ENSG00000182489,29845.0,NaN,0,2.110,NaN,NaN,NaN,HGNC,NaN,COSM1232945,XKRX,NaN,SNV,NaN,NaN,NaN,NaN,NaN,1,NaN,protein_coding,"getma.org/?cm=var&var=hg19,X,100183004,G,A&fts...",NaN,"Transmembrane_helices:TMhelix,hmmpanther:PTHR1...",NaN,NaN,NaN,P/L,NaN,NaN,A,medium,895/2848,NaN,NaN,NaN,getma.org/?cm=msa&ty=f&p=XKR2_HUMAN&rb=33&re=4...,deleterious(0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YES,"XKRX,missense_variant,p.Pro110Leu,ENST00000328...",NaN,NaN,NaN,NaN,1,NaN,MODERATE,290/1350,NaN,P97L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,XKR2_HUMAN,NaN,NaN,Transcript,NaN,probably_damaging(0.999),.,P110L,NaN,ENSP00000362047,NaN,NaN,CCDS14476.2,P110L,1/3,NaN,NaN,NaN,1/3,1,NaN,NaN,NaN
36268,ZNF256,0,Genentech,GRCh37,19,58452579,58452579,+,missense_variant,Missense_Mutation,SNP,T,T,G,NaN,NaN,587400,NORMAL,T,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.,.,.,.,ENST00000282308.3:c.1597A>C,p.Ser533Arg,p.S533R,ENST00000282308,NM_005773.2,533.0,Agc/Cgc,0,1,1.0,UPI00001D69EC,0,NaN,getma.org/pdb.php?prot=ZN256_HUMAN&from=533&to...,ENST00000282308,NaN,NaN,ENSG00000152454,13049.0,NaN,0,0.715,NaN,NaN,NaN,HGNC,NaN,"COSM1233768,COSM1233769",ZNF256,NaN,SNV,NaN,NaN,NaN,NaN,NaN,"1,1",NaN,protein_coding,"getma.org/?cm=var&var=hg19,19,58452579,T,G&fts...",NaN,"PROSITE_profiles:PS50157,hmmpanther:PTHR24387,...",NaN,NaN,NaN,S/R,NaN,NaN,G,neutral,1794/2172,NaN,NaN,NaN,getma.org/?cm=msa&ty=f&p=ZN256_HUMAN&rb=513&re...,tolerated(0.31),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YES,"ZNF256,missense_variant,p.Ser533Arg,ENST000002...",NaN,NaN,NaN,NaN,"1,1",NaN,MODERATE,1597/1884,NaN,S533R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZN256_HUMAN,NaN,NaN,Transcript,NaN,possibly_damaging(0.776),.,S533R,NaN,ENSP00000282308,NaN,NaN,CCDS12966.1,S533R,3/3,NaN,NaN,NaN,3/3,1,NaN,NaN,NaN
36269,ZNF300,0,Genentech,GRCh37,5,150275726,150275726,+,missense_variant,Missense_Mutation,SNP,C,C,T,NaN,NaN,587400,NORMAL,C,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.,.,.,.,ENST00000274599.5:c.1075G>A,p.Gly359Arg,p.G359R,ENST00000274599,NM_052860.2,359.0,Ggg/Agg,0,1,NaN,UPI000013C350,0,NaN,getma.org/pdb.php?prot=ZN300_HUMAN&from=339&to...,ENST00000274599,NaN,NaN,ENSG00000145908,13091.0,NaN,0,2.660,NaN,NaN,NaN,HGNC,NaN,"rs746103177,COSM1233867",ZNF300,0.000061,SNV,NaN,NaN,NaN,NaN,NaN,"0,1",NaN,protein_coding,"getma.org/?cm=var&var=hg19,5,150275726,C,T&fts...",NaN,"Gene3D:3.30.160.60,Pfam_domain:PF13465,PROSITE...",NaN,NaN,NaN,G/R,NaN,NaN,T,medium,1496/3268,0.000015,NaN,NaN,getma.org/?cm=msa&ty=f&p=ZN300_HUMAN&rb=319&re...,deleterious(0.04),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ZNF300,missense_variant,p.Gly375Arg,ENST000004...",0.000116,NaN,NaN,NaN,"0,1",NaN,MODERATE,1075/1815,NaN,G359R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZN300_HUMAN,NaN,NaN,Transcript,NaN,probably_damaging(1),.,G375R,NaN,ENSP00000274599,0.000025,NaN,CCDS4311.2,G375R,6/6,NaN,NaN,NaN,6/6,1,NaN,NaN,NaN
36270,ZSWIM4,0,Genentech,GRCh37,19,13923841,13923841,+,missense_variant,Missense_Mutation,SNP,C,C,T,NaN,NaN,587400,NORMAL,C,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.,.,.,.,ENST00000254323.2:c.1043C>T,p.Pro348Leu,p.P348L,ENST00000254323,NM_023072.2,348.0,cCc/cTc,0,1,1.0,UPI00001C2005,0,NaN,NaN,ENST00000254323,NaN,NaN,ENSG00000132003,25704.0,NaN,0,2.290,NaN,NaN,NaN,HGNC,NaN,"rs377659254,COSM1234841",ZSWIM4,NaN,SNV,NaN,NaN,NaN,NaN,NaN,"0,1",NaN,protein_coding,"getma.org/?cm=var&var=hg19,19,13923841,C,T&fts...",NaN,"hmmpanther:PTHR22619,hmmpanther:PTHR22619:SF4",NaN,NaN,NaN,P/L,NaN,NaN,T,medium,1232/4339,NaN,NaN,NaN,getma.org/?cm=msa&ty=f&p=ZSWM4_HUMAN&rb=201&re...,deleterious(0.01),NaN,NaN,NaN,Q9HA55_HUMAN,NaN,NaN,NaN,NaN,NaN,YES,"ZSWIM4,missense_variant,p.Pro348Leu,ENST000002...",NaN,NaN,NaN,NaN,"0,1",NaN,MODERATE,1043/2970,NaN,P348L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZSWM4_HUMAN,NaN,NaN,Transcript,NaN,possibly_damaging(0.851),.,P348L,NaN,ENSP00000254323,NaN,NaN,CCDS32924.1,P348L,6/13,NaN,NaN,NaN,6/13,1,NaN,NaN,NaN

In [36]:
dataMutation_Seshagiri = dataMutation_Seshagiri[['Tumor_Sample_Barcode', 'Hugo_Symbol', 'Chromosome', 'Start_Position', 'End_Position', 'Strand', 'Variant_Classification', 'Variant_Type', 'Reference_Allele', 'Tumor_Seq_Allele1', 'Tumor_Seq_Allele2', 'HGVSc', 'HGVSp_Short', 'Protein_position', 'Transcript_ID']]

In [37]:
dataMutation_Seshagiri

,Tumor_Sample_Barcode,Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID
0,587220,A1CF,10,52573792,52573792,+,Missense_Mutation,SNP,G,G,A,ENST00000373993.1:c.1172C>T,p.A391V,391.0,ENST00000373993
1,587220,A4GALT,22,43089044,43089044,+,Missense_Mutation,SNP,G,G,A,ENST00000249005.2:c.914C>T,p.P305L,305.0,ENST00000249005
2,587220,AARS2,6,44272932,44272932,+,Missense_Mutation,SNP,G,G,A,ENST00000244571.4:c.1438C>T,p.R480W,480.0,ENST00000244571
3,587220,ABCA1,9,107620834,107620834,+,Missense_Mutation,SNP,C,C,T,ENST00000374736.3:c.689G>A,p.R230H,230.0,ENST00000374736
4,587220,ABCA12,2,215840638,215840638,+,Missense_Mutation,SNP,A,A,G,ENST00000272895.7:c.5252T>C,p.V1751A,1751.0,ENST00000272895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36266,587400,WRNIP1,6,2766302,2766302,+,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.446C>A,p.A149E,149.0,ENST00000380773
36267,587400,XKRX,X,100183004,100183004,+,Missense_Mutation,SNP,G,G,A,ENST00000372956.2:c.290C>T,p.P97L,97.0,ENST00000372956
36268,587400,ZNF256,19,58452579,58452579,+,Missense_Mutation,SNP,T,T,G,ENST00000282308.3:c.1597A>C,p.S533R,533.0,ENST00000282308
36269,587400,ZNF300,5,150275726,150275726,+,Missense_Mutation,SNP,C,C,T,ENST00000274599.5:c.1075G>A,p.G359R,359.0,ENST00000274599
36270,587400,ZSWIM4,19,13923841,13923841,+,Missense_Mutation,SNP,C,C,T,ENST00000254323.2:c.1043C>T,p.P348L,348.0,ENST00000254323

In [38]:
uniqueHugo = dataMutation_Seshagiri['Hugo_Symbol'].nunique()
uniqueTranscript = dataMutation_Seshagiri['Transcript_ID'].nunique()
uniqueHugo, uniqueTranscript

(13026, 13099)

In [39]:
unknownHugo = (dataMutation_Seshagiri['Hugo_Symbol'] == 'Unknown').sum()
emptyHugo = (dataMutation_Seshagiri['Hugo_Symbol'] == '').sum()
naHugo = pd.isna(dataMutation_Seshagiri['Hugo_Symbol']).sum()

unknownTranscript = (dataMutation_Seshagiri['Transcript_ID'] == 'Unknown').sum()
emptyTranscript = (dataMutation_Seshagiri['Transcript_ID'] == '').sum()
naTranscript = pd.isna(dataMutation_Seshagiri['Transcript_ID']).sum()

unknownHugoUnknownTranscript = (dataMutation_Seshagiri[dataMutation_Seshagiri['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == 'Unknown').sum()
emptyHugoUnknownTranscript = (dataMutation_Seshagiri[dataMutation_Seshagiri['Hugo_Symbol'] == '']['Transcript_ID'] == 'Unknown').sum()
naHugoUnknownTranscript = (dataMutation_Seshagiri[dataMutation_Seshagiri['Hugo_Symbol'].isna()]['Transcript_ID'] == 'Unknown').sum()
unknownHugoEmptyTranscript = (dataMutation_Seshagiri[dataMutation_Seshagiri['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()
emptyHugoEmptyTranscript = (dataMutation_Seshagiri[dataMutation_Seshagiri['Hugo_Symbol'] == '']['Transcript_ID'] == '').sum()
naHugoEmptyTranscript = (dataMutation_Seshagiri[dataMutation_Seshagiri['Hugo_Symbol'].isna()]['Transcript_ID'] == '').sum()
unknownHugoNaTranscript = (pd.isna(dataMutation_Seshagiri[dataMutation_Seshagiri['Hugo_Symbol'] == 'Unknown']['Transcript_ID'])).sum()
emptyHugoNaTranscript = (pd.isna(dataMutation_Seshagiri[dataMutation_Seshagiri['Hugo_Symbol'] == '']['Transcript_ID'])).sum()
naHugoNaTranscript = (pd.isna(dataMutation_Seshagiri[dataMutation_Seshagiri['Hugo_Symbol'].isna()]['Transcript_ID'])).sum()

unknownHugoEmptyTranscript = (dataMutation_Seshagiri[dataMutation_Seshagiri['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()

(unknownHugo, emptyHugo, naHugo), (unknownTranscript, emptyTranscript, naTranscript), ((unknownHugoUnknownTranscript, emptyHugoUnknownTranscript, naHugoUnknownTranscript), (unknownHugoEmptyTranscript, emptyHugoEmptyTranscript, naHugoEmptyTranscript), (unknownHugoNaTranscript, emptyHugoNaTranscript, naHugoNaTranscript))

((0, 0, 0), (0, 0, 0), ((0, 0, 0), (0, 0, 0), (0, 0, 0)))

In [40]:
# Get unique transcript ids
uniqueTranscriptIds = dataMutation_Seshagiri['Transcript_ID'].unique()

# Create a dictionary mapping from Transcript_ID to Hugo_Symbol
transcriptIds_HugoSymbol_mapping = {id: ensembl.gene_name_of_transcript_id(id) for id in uniqueTranscriptIds}

transcriptIds_HugoSymbol_mapping

{'ENST00000373993': 'A1CF',
 'ENST00000249005': 'A4GALT',
 'ENST00000244571': 'AARS2',
 'ENST00000374736': 'ABCA1',
 'ENST00000272895': 'ABCA12',
 'ENST00000370225': 'ABCA4',
 'ENST00000261201': 'ABCC9',
 'ENST00000370214': 'ABCD3',
 'ENST00000337334': 'ABHD12B',
 'ENST00000458276': 'ABHD5',
 'ENST00000318560': 'ABL1',
 'ENST00000232744': 'ABTB1',
 'ENST00000338432': 'ACACB',
 'ENST00000265838': 'ACAT1',
 'ENST00000349064': 'ASIC3',
 'ENST00000256997': 'ACP2',
 'ENST00000281455': 'ACSL1',
 'ENST00000375406': 'ACTL8',
 'ENST00000352511': 'ACVR2B',
 'ENST00000487273': 'ADAM9',
 'ENST00000251582': 'ADAMTS2',
 'ENST00000389420': 'ADAMTS20',
 'ENST00000367996': 'ADAMTS4',
 'ENST00000388820': 'ADAMTS7',
 'ENST00000450565': 'ADCYAP1',
 'ENST00000356080': 'ADD3',
 'ENST00000308595': 'ADRBK1',
 'ENST00000358461': 'AFAP1',
 'ENST00000395792': 'AFP',
 'ENST00000238855': 'AFTPH',
 'ENST00000397238': 'AGAP3',
 'ENST00000371696': 'AGPAT2',
 'ENST00000396987': 'AGPAT6',
 'ENST00000378024': 'AHNAK',
 'ENST00000279146': 'AIP',
 'ENST00000354567': 'AK5',
 'ENST00000025301': 'AKAP11',
 'ENST00000306107': 'ALCAM',
 'ENST00000393434': 'ALDH1L1',
 'ENST00000176643': 'ALDH3A2',
 'ENST00000265605': 'ALDH8A1',
 'ENST00000262374': 'ALG1',
 'ENST00000399138': 'ALKBH5',
 'ENST00000295463': 'ALPI',
 'ENST00000177648': 'ALPK1',
 'ENST00000361673': 'ALPK2',
 'ENST00000256578': 'AMPD2',
 'ENST00000396553': 'AMPD3',
 'ENST00000341068': 'ANAPC1',
 'ENST00000373425': 'ANGPTL2',
 'ENST00000376819': 'ANGPTL7',
 'ENST00000357077': 'ANK2',
 'ENST00000318698': 'ANKFN1',
 'ENST00000301030': 'ANKRD11',
 'ENST00000285243': 'ANKRD40',
 'ENST00000356134': 'ANO2',
 'ENST00000419625': 'ANXA13',
 'ENST00000354546': 'ANXA6',
 'ENST00000308423': 'AOC3',
 'ENST00000261842': 'AP4E1',
 'ENST00000265381': 'APBA1',
 'ENST00000257430': 'APC',
 'ENST00000296456': 'APEH',
 'ENST00000216099': 'APOBEC3D',
 'ENST00000308521': 'APOBEC3F',
 'ENST00000397278': 'APOL1',
 'ENST00000219660': 'AQP8',
 'ENST00000370283': 'ARFGAP1',
 'ENST00000336498': 'ARHGAP10',
 'ENST00000295095': 'ARHGAP15',
 'ENST00000428638': 'ARHGAP27',
 'ENST00000383472': 'ARHGAP28',
 'ENST00000310343': 'ARHGAP32',
 'ENST00000393791': 'ARHGAP9',
 'ENST00000354532': 'ARHGEF1',
 'ENST00000361221': 'ARHGEF10L',
 'ENST00000378378': 'ARHGEF16',
 'ENST00000333677': 'ARHGEF37',
 'ENST00000326016': 'ARHGEF4',
 'ENST00000279873': 'ARID5B',
 'ENST00000263634': 'GPR75-ASB3',
 'ENST00000531618': 'ASCL3',
 'ENST00000379454': 'ASPH',
 'ENST00000320256': 'ASPRV1',
 'ENST00000361833': 'ASTN1',
 'ENST00000375687': 'ASXL1',
 'ENST00000238789': 'ATAD2B',
 'ENST00000321990': 'ATAD5',
 'ENST00000392017': 'ATG16L1',
 'ENST00000356654': 'ATN1',
 'ENST00000306279': 'ATOH8',
 'ENST00000357681': 'ATP2B4',
 'ENST00000234396': 'ATP6V1B1',
 'ENST00000242839': 'ATP7B',
 'ENST00000381655': 'ATP8A2',
 'ENST00000368489': 'ATP8B2',
 'ENST00000310127': 'ATP8B3',
 'ENST00000338821': 'ATP9A',
 'ENST00000355044': 'ATRNL1',
 'ENST00000585124': 'AURKB',
 'ENST00000533140': 'B3GNT6',
 'ENST00000307745': 'RP11-1055B8.7',
 'ENST00000286122': 'BANP',
 'ENST00000345358': 'BAX',
 'ENST00000358791': 'BCAS4',
 'ENST00000278100': 'BCCIP',
 'ENST00000269980': 'BCKDHA',
 'ENST00000335712': 'BCL11A',
 'ENST00000378043': 'BEST1',
 'ENST00000302334': 'BFSP2',
 'ENST00000399774': 'BID',
 'ENST00000374518': 'BMS1',
 'ENST00000321892': 'BPTF',
 'ENST00000259008': 'BRIP1',
 'ENST00000280758': 'BTBD11',
 'ENST00000481247': 'BTBD9',
 'ENST00000302759': 'BUB1',
 'ENST00000368821': 'TEX36',
 'ENST00000373279': 'C10orf35',
 'ENST00000310799': 'C11orf45',
 'ENST00000301896': 'C11orf85',
 'ENST00000261191': 'ASUN',
 'ENST00000358906': 'FAM222A',
 'ENST00000253233': 'C12orf65',
 'ENST00000354366': 'NRDE2',
 'ENST00000348520': 'KLC1',
 'ENST00000267485': 'C14orf37',
 'ENST00000380069': 'EXOC3L4',
 'ENST00000559313': 'C15orf52',
 'ENST00000219281': 'USB1',
 'ENST00000381920': 'METTL22',
 'ENST00000389005': 'C17orf85',
 'ENST00000221899': 'CACTIN',
 'ENST00000359435': 'BABAM1',
 'ENST00000367618': 'AXDND1',
 'ENST00000377320': 'C1orf200',
 'ENST00000234827': 'TCEANC2',
 'ENST00000371201': 'C1orf87',
 'ENST00000358293': 'FAM217B',
 'ENST00000357348': 'RTFDC1',
 'ENST00000378106': 'NDUFAF5',
 'ENST00000317749': 'C22orf43',
 'ENST00000295079': 'C2orf47',
 'ENST00000290536': 'M1AP',
 'ENST00000329615': 'C2orf70',
 'ENST00000326085': 'EFCAB12',
 'ENST00000392452': 'MB21D2',
 'ENST00000295268': 'STPG2',
 'ENST00000381937': 'NADK2',
 'ENST00000513200': 'KIAA0825',
 'ENST00000341865': 'C6orf132',
 'ENST00000311381': 'C6orf203',
 'ENST00000336600': 'C6orf223',
 'ENST00000313164': 'C7',
 'ENST00000292330': 'PPP1R35',
 'ENST00000332375': 'C7orf61',
 'ENST00000297203': 'C7orf62',
 'ENST00000331434': 'C8orf33',
 'ENST00000314330': 'C9orf139',
 'ENST00000316948': 'CACFD1',
 'ENST00000380701': 'CCDC171',
 'ENST00000263119': 'CABIN1',
 'ENST00000360228': 'CACNA1A',
 'ENST00000371372': 'CACNA1B',
 'ENST00000350061': 'CACNA1D',
 'ENST00000348261': 'CACNA1H',
 'ENST00000362061': 'CACNA1S',
 'ENST00000324631': 'CACNB2',
 'ENST00000348335': 'CAMKK1',
 'ENST00000279247': 'CAPN1',
 'ENST00000403897': 'CAPN14',
 'ENST00000361183': 'CAPZA2',
 'ENST00000396946': 'CARD11',
 'ENST00000310447': 'CASP2',
 'ENST00000432109': 'CASP8',
 'ENST00000261448': 'CASQ2',
 'ENST00000312106': 'CATSPER1',
 'ENST00000269397': 'CBX4',
 'ENST00000424120': 'CC2D2A',
 'ENST00000349456': 'CCDC104',
 'ENST00000292574': 'CCDC105',
 'ENST00000373053': 'MCU',
 'ENST00000389176': 'CCDC154',
 'ENST00000352312': 'CCDC37',
 'ENST00000328434': 'COA3',
 'ENST00000327554': 'CCDC60',
 'ENST00000298050': 'CCDC67',
 'ENST00000436346': 'CCDC88A',
 'ENST00000356786': 'CCDC88B',
 'ENST00000335119': 'CCIN',
 'ENST00000334619': 'CCKBR',
 'ENST00000361115': 'CCL28',
 'ENST00000292301': 'CCR2',
 'ENST00000258091': 'CCT7',
 'ENST00000256447': 'CD180',
 'ENST00000289429': 'CD1A',
 'ENST00000245903': 'CD70',
 'ENST00000310955': 'CDC20',
 'ENST00000249014': 'CDC42EP1',
 'ENST00000301200': 'CDC42EP5',
 'ENST00000367435': 'CDC73',
 'ENST00000299752': 'CDH16',
 'ENST00000372262': 'CDH22',
 'ENST00000231021': 'CDH9',
 'ENST00000506784': 'CDK18',
 'ENST00000325303': 'CDK20',
 'ENST00000304494': 'CDKN2A',
 'ENST00000301019': 'CDT1',
 'ENST00000292672': 'CELF5',
 'ENST00000397527': 'CEP250',
 'ENST00000377990': 'CEP68',
 'ENST00000369582': 'CGA',
 'ENST00000314103': 'CHAF1B',
 'ENST00000330494': 'CHD3',
 'ENST00000399982': 'CHD8',
 'ENST00000255409': 'CHI3L1',
 'ENST00000320658': 'CHRM2',
 'ENST00000370263': 'CHRNA4',
 'ENST00000332272': 'CHST6',
 'ENST00000258930': 'CIB2',
 'ENST00000261833': 'CIT',
 'ENST00000265593': 'CLCN2',
 'ENST00000513761': 'CLCN3',
 'ENST00000328796': 'CLDN6',
 'ENST00000325617': 'CLGN',
 'ENST00000368361': 'CLK2',
 'ENST00000337392': 'CLPTM1',
 'ENST00000324262': 'CNDP2',
 'ENST00000329903': 'CNGA2',
 'ENST00000305510': 'CNNM3',
 'ENST00000221232': 'CNOT3',
 'ENST00000397461': 'CNTN4',
 'ENST00000265136': 'COBL',
 'ENST00000299886': 'COG1',
 'ENST00000347053': 'COG5',
 'ENST00000307149': 'COG7',
 'ENST00000370096': 'COL11A1',
 'ENST00000322507': 'COL12A1',
 'ENST00000359759': 'COL18A1',
 'ENST00000380518': 'COL2A1',
 'ENST00000304636': 'COL3A1',
 'ENST00000360467': 'COL4A2',
 'ENST00000372216': 'COL4A6',
 'ENST00000334571': 'COQ6',
 'ENST00000262428': 'COTL1',
 'ENST00000016171': 'COX15',
 'ENST00000389912': 'COX16',
 'ENST00000268720': 'CPNE7',
 'ENST00000383811': 'CRELD1',
 'ENST00000354336': 'CRKL',
 'ENST00000378863': 'CRLS1',
 'ENST00000397890': 'CRMP1',
 'ENST00000320954': 'CRTAP',
 'ENST00000354760': 'CRYBA4',
 'ENST00000215855': 'CRYBB3',
 'ENST00000374466': 'CSGALNACT2',
 'ENST00000297405': 'CSMD3',
 'ENST00000312134': 'CST6',
 'ENST00000361367': 'CTR9',
 'ENST00000216336': 'CTSG',
 'ENST00000160373': 'CTTNBP2',
 'ENST00000296026': 'CXCL3',
 'ENST00000295683': 'CXCR1',
 'ENST00000285106': 'CXXC1',
 'ENST00000318911': 'CYC1',
 'ENST00000369887': 'CYP17A1',
 'ENST00000285949': 'CYP26C1',
 'ENST00000301146': 'CYP2A7',
 'ENST00000285979': 'CYP2C18',
 'ENST00000334636': 'CYP2R1',
 'ENST00000589787': 'CYP4F8',
 'ENST00000366795': 'DACT2',
 'ENST00000332700': 'DBX2',
 'ENST00000319675': 'DCAF4L2',
 'ENST00000332395': 'DDX28',
 'ENST00000371148': 'DEFB110',
 'ENST00000382209': 'DEFB136',
 'ENST00000454345': 'DGKZ',
 'ENST00000445061': 'DHX30',
 'ENST00000496811': 'DHX36',
 'ENST00000268482': 'DHX38',
 'ENST00000457308': 'DHX57',
 'ENST00000367549': 'DHX9',
 'ENST00000400324': 'DIAPH3',
 'ENST00000343455': 'DICER1',
 'ENST00000266070': 'DIDO1',
 'ENST00000339266': 'DLGAP4',
 'ENST00000375847': 'DNAJC16',
 'ENST00000341772': 'DNER',
 'ENST00000254579': 'DNHD1',
 'ENST00000355305': 'DNM3',
 'ENST00000343572': 'DOC2B',
 'ENST00000266037': 'DOCK3',
 'ENST00000437633': 'DOCK4',
 'ENST00000340370': 'DOCK7',
 'ENST00000432829': 'DOCK8',
 'ENST00000376460': 'DOCK9',
 'ENST00000398665': 'DOT1L',
 'ENST00000404039': 'DPP6',
 'ENST00000371579': 'DPP7',
 'ENST00000414645': 'DPY19L4',
 'ENST00000338492': 'DPYSL4',
 'ENST00000331677': 'DSE',
 'ENST00000257189': 'DSG3',
 'ENST00000379802': 'DSP',
 'ENST00000367162': 'DSTYK',
 'ENST00000296161': 'DTX3L',
 'ENST00000298573': 'DUSP16',
 'ENST00000331588': 'DUSP8',
 'ENST00000360184': 'DYNC1H1',
 'ENST00000323039': 'DYRK1B',
 'ENST00000258104': 'DYSF',
 'ENST00000355311': 'EBF3',
 'ENST00000402825': 'ECE2',
 'ENST00000367682': 'ECT2L',
 'ENST00000374492': 'EDEM2',
 'ENST00000337938': 'EDN3',
 'ENST00000307998': 'EFEMP2',
 'ENST00000426333': 'EFTUD2',
 'ENST00000275493': 'EGFR',
 'ENST00000303961': 'EGLN2',
 'ENST00000220325': 'EHD4',
 'ENST00000216190': 'EIF3D',
 'ENST00000290246': 'ELMO2',
 'ENST00000393997': 'ELMO3',
 'ENST00000254528': 'EMILIN2',
 'ENST00000394773': 'EML3',
 'ENST00000297375': 'EN2',
 'ENST00000357639': 'ENPP3',
 'ENST00000263253': 'EP300',
 'ENST00000389561': 'EP400',
 'ENST00000343067': 'EPB41',
 'ENST00000337057': 'EPB41L2',
 'ENST00000374566': 'EPB41L4B',
 'ENST00000263713': 'EPB41L5',
 'ENST00000330394': 'EPHB3',
 'ENST00000248070': 'EPS15L1',
 'ENST00000361965': 'EPS8L3',
 'ENST00000254928': 'ERAL1',
 'ENST00000342788': 'ERBB4',
 'ENST00000288221': 'ERC2',
 'ENST00000262109': 'ERICH1',
 'ENST00000410096': 'ERMN',
 'ENST00000377828': 'ESPN',
 'ENST00000265843': 'EXPH5',
 'ENST00000373871': 'EYA3',
 'ENST00000460911': 'EZH2',
 'ENST00000367797': 'F5',
 'ENST00000321420': 'AMER3',
 'ENST00000037869': 'FAM136A',
 'ENST00000378116': 'FAM171A1',
 'ENST00000409072': 'FAM183B',
 'ENST00000265299': 'FAM188B',
 'ENST00000257515': 'FAM189A2',
 'ENST00000313766': 'FAM20C',
 'ENST00000329759': 'FAM43A',
 'ENST00000361539': 'BRINP2',
 'ENST00000367462': 'BRINP3',
 'ENST00000370310': 'FAM69A',
 'ENST00000358369': 'FAM73B',
 'ENST00000283357': 'FAM81B',
 'ENST00000297532': 'FASTK',
 'ENST00000298047': 'FAT3',
 'ENST00000394329': 'FAT4',
 'ENST00000484457': 'FBXL2',
 'ENST00000331272': 'FBXW4',
 'ENST00000252771': 'FCHO1',
 'ENST00000217289': 'FERMT1',
 'ENST00000341590': 'FERMT2',
 'ENST00000168712': 'FGF4',
 'ENST00000264748': 'FGFRL1',
 'ENST00000230124': 'FIG4',
 'ENST00000325888': 'FLNC',
 'ENST00000335154': 'FMNL3',
 'ENST00000297267': 'FNDC1',
 'ENST00000509018': 'RAPGEF6',
 'ENST00000312562': 'FOSL1',
 'ENST00000396057': 'FOXB1',
 'ENST00000376708': 'FOXB2',
 'ENST00000313071': 'FOXG1',
 'ENST00000329798': 'FREM3',
 'ENST00000357447': 'FRMD4A',
 'ENST00000317568': 'FRMD8',
 'ENST00000358350': 'FRYL',
 'ENST00000427159': 'FTSJ3',
 'ENST00000310160': 'FUT1',
 'ENST00000313777': 'FUZ',
 'ENST00000357559': 'FXR1',
 'ENST00000286201': 'FZD7',
 'ENST00000393564': 'G6PD',
 'ENST00000259455': 'GABBR2',
 'ENST00000311550': 'GABRB3',
 'ENST00000192314': 'GAL3ST2',
 'ENST00000392701': 'GALNT3',
 'ENST00000249041': 'GALR3',
 'ENST00000356638': 'GANAB',
 'ENST00000266754': 'GAS2L3',
 'ENST00000341105': 'GATA2',
 'ENST00000370466': 'GBP2',
 'ENST00000370459': 'GBP5',
 'ENST00000329913': 'GDF3',
 'ENST00000309859': 'GGA2',
 'ENST00000574154': 'GGT6',
 'ENST00000278765': 'GGTLC1',
 'ENST00000275732': 'GIGYF1',
 'ENST00000225394': 'GIT1',
 'ENST00000378695': 'GLIPR1L1',
 'ENST00000324333': 'GLIS3',
 'ENST00000262958': 'GNA15',
 'ENST00000303210': 'GNB2',
 'ENST00000163416': 'GOLGA5',
 'ENST00000265070': 'GOLPH3',
 'ENST00000401815': 'GP5',
 'ENST00000170564': 'GPATCH1',
 'ENST00000377067': 'GPC5',
 'ENST00000310454': 'GPD2',
 'ENST00000370652': 'GPR112',
 'ENST00000315843': 'GPR156',
 'ENST00000309180': 'GPR171',
 'ENST00000342292': 'GPR179',
 'ENST00000332262': 'GPRASP2',
 'ENST00000234142': 'GREB1',
 'ENST00000318158': 'GRHPR',
 'ENST00000392870': 'GRK5',
 'ENST00000355472': 'GRK6',
 'ENST00000404338': 'ARHGAP35',
 'ENST00000538487': 'GRM4',
 'ENST00000276708': 'GSDMC',
 'ENST00000338595': 'GSTO2',
 'ENST00000553612': 'GTF2A1',
 'ENST00000394456': 'GTF2F1',
 'ENST00000265755': 'GTF2IRD1',
 'ENST00000264424': 'GUCY1B3',
 'ENST00000254854': 'GUCY2D',
 'ENST00000304895': 'GUSB',
 'ENST00000264553': 'GZMM',
 'ENST00000373255': 'H2AFY2',
 'ENST00000380649': 'HADHA',
 'ENST00000231121': 'HAND1',
 'ENST00000306560': 'HAS3',
 'ENST00000534862': 'HCK',
 'ENST00000303230': 'HCN1',
 'ENST00000345617': 'HDAC4',
 'ENST00000391975': 'HDLBP',
 'ENST00000184956': 'HEATR6',
 'ENST00000395891': 'HECW1',
 'ENST00000315765': 'HEPHL1',
 'ENST00000261609': 'HERC2',
 'ENST00000377670': 'HIF3A',
 'ENST00000321331': 'HIGD1A',
 'ENST00000336926': 'HIP1',
 'ENST00000263208': 'HIRA',
 'ENST00000303910': 'HIST1H2AE',
 'ENST00000292432': 'HK3',
 'ENST00000354624': 'HKDC1',
 'ENST00000336648': 'HLCS',
 'ENST00000357878': 'HMX3',
 'ENST00000409753': 'HN1',
 'ENST00000351839': 'HNRNPK',
 'ENST00000343060': 'HOXA1',
 'ENST00000317201': 'HOXA3',
 'ENST00000222726': 'HOXA5',
 'ENST00000406506': 'HOXD12',
 'ENST00000262626': 'HPN',
 'ENST00000304031': 'HS1BP3',
 'ENST00000334701': 'HSP90AA1',
 'ENST00000369209': 'HSPA12A',
 'ENST00000309758': 'HSPA6',
 'ENST00000262854': 'HUWE1',
 'ENST00000336307': 'HYAL3',
 'ENST00000306270': 'IBTK',
 'ENST00000372491': 'IER5L',
 'ENST00000295809': 'IFI16',
 'ENST00000426508': 'IFT140',
 'ENST00000352385': 'IGDCC4',
 'ENST00000321016': 'IGSF9B',
 'ENST00000295981': 'IL17RC',
 'ENST00000296318': 'IL17RD',
 'ENST00000264260': 'IL18RAP',
 'ENST00000270800': 'IL22RA1',
 'ENST00000391826': 'IL4I1',
 'ENST00000344209': 'ILDR1',
 'ENST00000271417': 'ILDR2',
 'ENST00000331762': 'IMMP2L',
 'ENST00000403263': 'INO80D',
 'ENST00000331075': 'INPP5J',
 'ENST00000310227': 'INSM1',
 'ENST00000404767': 'INTS1',
 'ENST00000523731': 'INTS8',
 'ENST00000402050': 'IQCE',
 'ENST00000268182': 'IQGAP1',
 'ENST00000256458': 'IRAK2',
 'ENST00000231357': 'IRX4',
 'ENST00000342219': 'ISM2',
 'ENST00000266041': 'ITIH4',
 'ENST00000439118': 'ITPRIPL1',
 'ENST00000381318': 'ITSN1',
 'ENST00000295321': 'IWS1',
 'ENST00000341776': 'JARID2',
 'ENST00000261247': 'JKAMP',
 'ENST00000399262': 'JMJD1C',
 'ENST00000284262': 'JPH3',
 'ENST00000584173': 'AC080008.1',
 'ENST00000225916': 'KAT2A',
 'ENST00000356157': 'KATNAL2',
 'ENST00000432196': 'KBTBD13',
 'ENST00000379485': 'KBTBD6',
 'ENST00000369771': 'KCNA10',
 'ENST00000369769': 'KCNA3',
 'ENST00000303790': 'KCNAB3',
 'ENST00000371741': 'KCNB1',
 'ENST00000379472': 'KCNC1',
 'ENST00000477616': 'KCNC3',
 'ENST00000240662': 'KCNJ8',
 'ENST00000340700': 'KCNK10',
 'ENST00000303015': 'KCNK9',
 'ENST00000347132': 'KCNQ4',
 'ENST00000382082': 'KCNV2',
 'ENST00000159111': 'KDM4B',
 'ENST00000414716': 'CEP170B',
 'ENST00000338205': 'KIAA0368',
 'ENST00000348624': 'AP5Z1',
 'ENST00000297063': 'KIAA0895',
 'ENST00000296564': 'KIAA0947',
 'ENST00000393151': 'UNC79',
 'ENST00000398130': 'KIAA1468',
 'ENST00000160298': 'CAMSAP3',
 'ENST00000422774': 'KIAA1549',
 'ENST00000325212': 'KIAA1731',
 'ENST00000338005': 'CCDC183',
 'ENST00000376572': 'KIAA2013',
 'ENST00000326047': 'KIF15',
 'ENST00000247986': 'KIF17',
 'ENST00000320389': 'KIF1A',
 'ENST00000422435': 'KIF21B',
 'ENST00000379166': 'KIF24',
 'ENST00000407071': 'KIF26B',
 'ENST00000288135': 'KIT',
 'ENST00000296233': 'KLF15',
 'ENST00000309755': 'KLHL3',
 'ENST00000594768': 'KLK11',
 'ENST00000391807': 'KLK7',
 'ENST00000251643': 'KRT12',
 'ENST00000167586': 'KRT14',
 'ENST00000417996': 'KRT3',
 'ENST00000393989': 'KRT35',
 'ENST00000293774': 'KRT4',
 'ENST00000252245': 'KRT75',
 'ENST00000399889': 'KRTAP13-2',
 'ENST00000427442': 'L3MBTL1',
 'ENST00000389658': 'LAMA1',
 'ENST00000356082': 'LAMB3',
 'ENST00000361069': 'LAMC3',
 'ENST00000336314': 'LARP1',
 'ENST00000398473': 'LARP4',
 'ENST00000305641': 'LCMT2',
 'ENST00000323076': 'LCP1',
 'ENST00000215909': 'LGALS1',
 'ENST00000341872': 'LGALS8',
 'ENST00000263274': 'LIG1',
 'ENST00000391736': 'LILRB4',
 'ENST00000449561': 'LILRB5',
 'ENST00000336180': 'LIMK1',
 'ENST00000368820': 'LINGO4',
 'ENST00000244289': 'LIPE',
 'ENST00000316843': 'LLGL1',
 'ENST00000294816': 'LMX1A',
 'ENST00000389484': 'LRP1B',
 'ENST00000263816': 'LRP2',
 'ENST00000313838': 'LRRC48',
 'ENST00000367175': 'LRRN2',
 'ENST00000378858': 'LRRN4',
 'ENST00000265245': 'LSG1',
 'ENST00000356396': 'LSS',
 'ENST00000301873': 'LTBP3',
 'ENST00000231751': 'LTF',
 'ENST00000367576': 'LTV1',
 'ENST00000266718': 'LUM',
 'ENST00000372915': 'MACF1',
 'ENST00000265854': 'MAD1L1',
 'ENST00000402939': 'MAGI1',
 'ENST00000371589': 'MAN1B1',
 'ENST00000374332': 'MAN1C1',
 'ENST00000261483': 'MAN2A1',
 'ENST00000360468': 'MAN2A2',
 'ENST00000285599': 'MAN2B2',
 'ENST00000300231': 'MAP1A',
 'ENST00000353533': 'MAP2K4',
 'ENST00000397979': 'MAP2K7',
 'ENST00000267079': 'MAP3K12',
 'ENST00000392142': 'MAP3K4',
 'ENST00000359221': 'MAPK10',
 'ENST00000308406': 'MAPK7',
 'ENST00000262410': 'MAPT',
 'ENST00000251472': 'MAST1',
 'ENST00000262811': 'MAST3',
 'ENST00000403625': 'MAST4',
 'ENST00000407073': 'MBD5',
 'ENST00000555147': 'MC1R',
 'ENST00000265056': 'MCM2',
 'ENST00000264156': 'MCM6',
 'ENST00000281928': 'MED13L',
 'ENST00000276282': 'MFHAS1',
 'ENST00000281416': 'MFSD6',
 'ENST00000261537': 'MIB1',
 'ENST00000505820': 'MIB2',
 'ENST00000301067': 'KMT2D',
 'ENST00000246912': 'MLX',
 'ENST00000219271': 'MMP15',
 'ENST00000246186': 'MMP24',
 'ENST00000260229': 'MMP27',
 'ENST00000302326': 'MN1',
 'ENST00000252971': 'MNX1',
 'ENST00000357066': 'MOB3A',
 'ENST00000223114': 'MOGAT3',
 'ENST00000397641': 'MORC2',
 'ENST00000225275': 'MPO',
 'ENST00000463290': 'MPZ',
 'ENST00000278937': 'MPZL2',
 'ENST00000303375': 'MRC2',
 'ENST00000276585': 'MRPS28',
 'ENST00000442466': 'MSLNL',
 'ENST00000296003': 'MTMR14',
 'ENST00000338779': 'MTSS1L',
 'ENST00000441003': 'MUC2',
 'ENST00000344663': 'MUM1',
 'ENST00000522677': 'MYBL1',
 'ENST00000226207': 'MYH1',
 'ENST00000252172': 'MYH13',
 'ENST00000376970': 'MYH14',
 'ENST00000394809': 'MYLK3',
 'ENST00000300119': 'MYO1A',
 'ENST00000318217': 'MYO1D',
 'ENST00000265944': 'MYO3A',
 'ENST00000285039': 'MYO5B',
 'ENST00000409709': 'MYO7A',
 'ENST00000594824': 'MYO9B',
 'ENST00000359263': 'MYOF',
 'ENST00000262113': 'MYOM2',
 'ENST00000374434': 'MYOM3',
 'ENST00000358913': 'MYPN',
 'ENST00000328439': 'MYT1',
 'ENST00000300131': 'NAB2',
 'ENST00000251127': 'NALCN',
 'ENST00000261520': 'NARG2',
 'ENST00000205194': 'NAT14',
 'ENST00000272425': 'NAT8',
 'ENST00000367296': 'NAV1',
 'ENST00000449802': 'NBEAL1',
 'ENST00000315579': 'NCAPD2',
 'ENST00000251496': 'NCAPG',
 'ENST00000290231': 'NCOA5',
 'ENST00000396355': 'NDE1',
 'ENST00000260361': 'NDUFAF1',
 'ENST00000313468': 'NDUFS8',
 'ENST00000172853': 'NEB',
 'ENST00000310624': 'NEFH',
 'ENST00000221169': 'NEFL',
 'ENST00000429845': 'NEK10',
 'ENST00000357134': 'NELL1',
 'ENST00000391969': 'NEU4',
 'ENST00000339876': 'NFASC',
 'ENST00000427363': 'NFATC1',
 'ENST00000374092': 'NFS1',
 'ENST00000302101': 'NHLH1',
 'ENST00000427025': 'NHSL1',
 'ENST00000264187': 'NID1',
 'ENST00000278886': 'NINL',
 'ENST00000374762': 'NIPSNAP3B',
 'ENST00000295886': 'NKX6-1',
 'ENST00000301295': 'NLRP4',
 'ENST00000378165': 'NMT2',
 'ENST00000287139': 'NODAL',
 'ENST00000377705': 'NOL9',
 'ENST00000275820': 'NOM1',
 'ENST00000317775': 'NOS1',
 'ENST00000277541': 'NOTCH1',
 'ENST00000263388': 'NOTCH3',
 'ENST00000311034': 'NPAS4',
 'ENST00000269228': 'NPC1',

In [41]:
# add Ensembl Hugo_Symbol
dataMutation_Seshagiri_cleaned = dataMutation_Seshagiri.copy()
dataMutation_Seshagiri_cleaned.rename(columns={'Hugo_Symbol': 'original_Hugo_Symbol'}, inplace=True)
dataMutation_Seshagiri_cleaned.insert(1, 'Hugo_Symbol', '')
dataMutation_Seshagiri_cleaned.loc[:,'Hugo_Symbol'] = dataMutation_Seshagiri_cleaned['Transcript_ID'].map(transcriptIds_HugoSymbol_mapping)

In [42]:
# show rows where Hugo_Symbol and original_Hugo_Symbol are different
dataMutation_Seshagiri_cleaned.loc[dataMutation_Seshagiri_cleaned['Hugo_Symbol'] != dataMutation_Seshagiri_cleaned['original_Hugo_Symbol'], ['Transcript_ID', 'Hugo_Symbol', 'original_Hugo_Symbol']]

         Transcript_ID   Hugo_Symbol original_Hugo_Symbol
708    ENST00000221169          NEFL        CTD-2168K21.2
885    ENST00000352766  PRR5-ARHGAP8              ARHGAP8
2881   ENST00000389774       ARHGAP8         PRR5-ARHGAP8
2951   ENST00000525031       RBMS2P1               CCDC41
3168   ENST00000310358         SPON1         RP11-21L19.1
...                ...           ...                  ...
34427  ENST00000377540         TTC25                  CNP
34561  ENST00000411859        UBTFL2        RP11-313I2.11
34562  ENST00000411859        UBTFL2        RP11-313I2.11
34942  ENST00000480336    RP1-27O5.3               ZBTB8B
35903  ENST00000374127         PGBD3          ERCC6-PGBD3

[88 rows x 3 columns]

In [43]:
# add gene length
dataMutation_Seshagiri_cleaned['Gene_Length'] = dataMutation_Seshagiri_cleaned['Hugo_Symbol'].apply(lambda x: ensembl.genes_by_name(x)[0].length)

In [44]:
dataMutation_Seshagiri_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length
0,587220,A1CF,A1CF,10,52573792,52573792,+,Missense_Mutation,SNP,G,G,A,ENST00000373993.1:c.1172C>T,p.A391V,391.0,ENST00000373993,86267
1,587220,A4GALT,A4GALT,22,43089044,43089044,+,Missense_Mutation,SNP,G,G,A,ENST00000249005.2:c.914C>T,p.P305L,305.0,ENST00000249005,29178
2,587220,AARS2,AARS2,6,44272932,44272932,+,Missense_Mutation,SNP,G,G,A,ENST00000244571.4:c.1438C>T,p.R480W,480.0,ENST00000244571,13673
3,587220,ABCA1,ABCA1,9,107620834,107620834,+,Missense_Mutation,SNP,C,C,T,ENST00000374736.3:c.689G>A,p.R230H,230.0,ENST00000374736,147236
4,587220,ABCA12,ABCA12,2,215840638,215840638,+,Missense_Mutation,SNP,A,A,G,ENST00000272895.7:c.5252T>C,p.V1751A,1751.0,ENST00000272895,206886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36266,587400,WRNIP1,WRNIP1,6,2766302,2766302,+,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.446C>A,p.A149E,149.0,ENST00000380773,21539
36267,587400,XKRX,XKRX,X,100183004,100183004,+,Missense_Mutation,SNP,G,G,A,ENST00000372956.2:c.290C>T,p.P97L,97.0,ENST00000372956,15992
36268,587400,ZNF256,ZNF256,19,58452579,58452579,+,Missense_Mutation,SNP,T,T,G,ENST00000282308.3:c.1597A>C,p.S533R,533.0,ENST00000282308,6843
36269,587400,ZNF300,ZNF300,5,150275726,150275726,+,Missense_Mutation,SNP,C,C,T,ENST00000274599.5:c.1075G>A,p.G359R,359.0,ENST00000274599,10592
36270,587400,ZSWIM4,ZSWIM4,19,13923841,13923841,+,Missense_Mutation,SNP,C,C,T,ENST00000254323.2:c.1043C>T,p.P348L,348.0,ENST00000254323,36771

In [45]:
uniqueHugo = dataMutation_Seshagiri_cleaned['Hugo_Symbol'].nunique(dropna=False)
uniqueTranscript = dataMutation_Seshagiri_cleaned['Transcript_ID'].nunique(dropna=False)
uniqueHugo, uniqueTranscript

(13033, 13099)

In [46]:
unknownHugo = (dataMutation_Seshagiri_cleaned['Hugo_Symbol'] == 'Unknown').sum()
emptyHugo = (dataMutation_Seshagiri_cleaned['Hugo_Symbol'] == '').sum()
naHugo = pd.isna(dataMutation_Seshagiri_cleaned['Hugo_Symbol']).sum()

unknownTranscript = (dataMutation_Seshagiri_cleaned['Transcript_ID'] == 'Unknown').sum()
emptyTranscript = (dataMutation_Seshagiri_cleaned['Transcript_ID'] == '').sum()
naTranscript = pd.isna(dataMutation_Seshagiri_cleaned['Transcript_ID']).sum()

unknownHugoUnknownTranscript = (dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == 'Unknown').sum()
emptyHugoUnknownTranscript = (dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Hugo_Symbol'] == '']['Transcript_ID'] == 'Unknown').sum()
naHugoUnknownTranscript = (dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Hugo_Symbol'].isna()]['Transcript_ID'] == 'Unknown').sum()
unknownHugoEmptyTranscript = (dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()
emptyHugoEmptyTranscript = (dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Hugo_Symbol'] == '']['Transcript_ID'] == '').sum()
naHugoEmptyTranscript = (dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Hugo_Symbol'].isna()]['Transcript_ID'] == '').sum()
unknownHugoNaTranscript = (pd.isna(dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'])).sum()
emptyHugoNaTranscript = (pd.isna(dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Hugo_Symbol'] == '']['Transcript_ID'])).sum()
naHugoNaTranscript = (pd.isna(dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Hugo_Symbol'].isna()]['Transcript_ID'])).sum()

unknownHugoEmptyTranscript = (dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()

(unknownHugo, emptyHugo, naHugo), (unknownTranscript, emptyTranscript, naTranscript), ((unknownHugoUnknownTranscript, emptyHugoUnknownTranscript, naHugoUnknownTranscript), (unknownHugoEmptyTranscript, emptyHugoEmptyTranscript, naHugoEmptyTranscript), (unknownHugoNaTranscript, emptyHugoNaTranscript, naHugoNaTranscript))

((0, 0, 0), (0, 0, 0), ((0, 0, 0), (0, 0, 0), (0, 0, 0)))

In [47]:
dataMutation_Seshagiri_cleaned['Mutation_Length'] = dataMutation_Seshagiri_cleaned['End_Position'] - dataMutation_Seshagiri_cleaned['Start_Position'] + 1
dataMutation_Seshagiri_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length
0,587220,A1CF,A1CF,10,52573792,52573792,+,Missense_Mutation,SNP,G,G,A,ENST00000373993.1:c.1172C>T,p.A391V,391.0,ENST00000373993,86267,1
1,587220,A4GALT,A4GALT,22,43089044,43089044,+,Missense_Mutation,SNP,G,G,A,ENST00000249005.2:c.914C>T,p.P305L,305.0,ENST00000249005,29178,1
2,587220,AARS2,AARS2,6,44272932,44272932,+,Missense_Mutation,SNP,G,G,A,ENST00000244571.4:c.1438C>T,p.R480W,480.0,ENST00000244571,13673,1
3,587220,ABCA1,ABCA1,9,107620834,107620834,+,Missense_Mutation,SNP,C,C,T,ENST00000374736.3:c.689G>A,p.R230H,230.0,ENST00000374736,147236,1
4,587220,ABCA12,ABCA12,2,215840638,215840638,+,Missense_Mutation,SNP,A,A,G,ENST00000272895.7:c.5252T>C,p.V1751A,1751.0,ENST00000272895,206886,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36266,587400,WRNIP1,WRNIP1,6,2766302,2766302,+,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.446C>A,p.A149E,149.0,ENST00000380773,21539,1
36267,587400,XKRX,XKRX,X,100183004,100183004,+,Missense_Mutation,SNP,G,G,A,ENST00000372956.2:c.290C>T,p.P97L,97.0,ENST00000372956,15992,1
36268,587400,ZNF256,ZNF256,19,58452579,58452579,+,Missense_Mutation,SNP,T,T,G,ENST00000282308.3:c.1597A>C,p.S533R,533.0,ENST00000282308,6843,1
36269,587400,ZNF300,ZNF300,5,150275726,150275726,+,Missense_Mutation,SNP,C,C,T,ENST00000274599.5:c.1075G>A,p.G359R,359.0,ENST00000274599,10592,1
36270,587400,ZSWIM4,ZSWIM4,19,13923841,13923841,+,Missense_Mutation,SNP,C,C,T,ENST00000254323.2:c.1043C>T,p.P348L,348.0,ENST00000254323,36771,1

In [48]:
### TODO: what to do with missing protein positions? For now, removing them
dataMutation_Seshagiri_cleaned = dataMutation_Seshagiri_cleaned[~dataMutation_Seshagiri_cleaned['Protein_position'].isna()].copy()
dataMutation_Seshagiri_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length
0,587220,A1CF,A1CF,10,52573792,52573792,+,Missense_Mutation,SNP,G,G,A,ENST00000373993.1:c.1172C>T,p.A391V,391.0,ENST00000373993,86267,1
1,587220,A4GALT,A4GALT,22,43089044,43089044,+,Missense_Mutation,SNP,G,G,A,ENST00000249005.2:c.914C>T,p.P305L,305.0,ENST00000249005,29178,1
2,587220,AARS2,AARS2,6,44272932,44272932,+,Missense_Mutation,SNP,G,G,A,ENST00000244571.4:c.1438C>T,p.R480W,480.0,ENST00000244571,13673,1
3,587220,ABCA1,ABCA1,9,107620834,107620834,+,Missense_Mutation,SNP,C,C,T,ENST00000374736.3:c.689G>A,p.R230H,230.0,ENST00000374736,147236,1
4,587220,ABCA12,ABCA12,2,215840638,215840638,+,Missense_Mutation,SNP,A,A,G,ENST00000272895.7:c.5252T>C,p.V1751A,1751.0,ENST00000272895,206886,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36266,587400,WRNIP1,WRNIP1,6,2766302,2766302,+,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.446C>A,p.A149E,149.0,ENST00000380773,21539,1
36267,587400,XKRX,XKRX,X,100183004,100183004,+,Missense_Mutation,SNP,G,G,A,ENST00000372956.2:c.290C>T,p.P97L,97.0,ENST00000372956,15992,1
36268,587400,ZNF256,ZNF256,19,58452579,58452579,+,Missense_Mutation,SNP,T,T,G,ENST00000282308.3:c.1597A>C,p.S533R,533.0,ENST00000282308,6843,1
36269,587400,ZNF300,ZNF300,5,150275726,150275726,+,Missense_Mutation,SNP,C,C,T,ENST00000274599.5:c.1075G>A,p.G359R,359.0,ENST00000274599,10592,1
36270,587400,ZSWIM4,ZSWIM4,19,13923841,13923841,+,Missense_Mutation,SNP,C,C,T,ENST00000254323.2:c.1043C>T,p.P348L,348.0,ENST00000254323,36771,1

In [49]:
### TODO: Is this correct?
transcriptIds_proteinIds_mapping = {tid: (len(ensembl.transcript_by_id(tid).protein_sequence) if ensembl.transcript_by_id(tid).protein_sequence is not None else np.nan) for tid in dataMutation_Seshagiri_cleaned['Transcript_ID'].unique()}
transcriptIds_proteinIds_mapping

{'ENST00000373993': 594,
 'ENST00000249005': 353,
 'ENST00000244571': 985,
 'ENST00000374736': 2261,
 'ENST00000272895': 2595,
 'ENST00000370225': 2273,
 'ENST00000261201': 1549,
 'ENST00000370214': 659,
 'ENST00000337334': 362,
 'ENST00000458276': 349,
 'ENST00000318560': 1130,
 'ENST00000232744': 478,
 'ENST00000338432': 2458,
 'ENST00000265838': 427,
 'ENST00000349064': 531,
 'ENST00000256997': 423,
 'ENST00000281455': 698,
 'ENST00000375406': 366,
 'ENST00000352511': 512,
 'ENST00000251582': 1211,
 'ENST00000389420': 1910,
 'ENST00000367996': 837,
 'ENST00000388820': 1686,
 'ENST00000450565': 176,
 'ENST00000356080': 706,
 'ENST00000358461': 730,
 'ENST00000395792': 609,
 'ENST00000238855': 936,
 'ENST00000397238': 911,
 'ENST00000371696': 278,
 'ENST00000396987': 456,
 'ENST00000378024': 5890,
 'ENST00000279146': 330,
 'ENST00000354567': 562,
 'ENST00000025301': 1901,
 'ENST00000306107': 583,
 'ENST00000393434': 902,
 'ENST00000176643': 485,
 'ENST00000265605': 487,
 'ENST00000262374': 464,
 'ENST00000399138': 394,
 'ENST00000295463': 528,
 'ENST00000177648': 1244,
 'ENST00000361673': 2170,
 'ENST00000256578': 879,
 'ENST00000396553': 767,
 'ENST00000341068': 1944,
 'ENST00000373425': 493,
 'ENST00000376819': 346,
 'ENST00000357077': 3957,
 'ENST00000318698': 763,
 'ENST00000301030': 2663,
 'ENST00000285243': 368,
 'ENST00000356134': 999,
 'ENST00000419625': 316,
 'ENST00000354546': 673,
 'ENST00000308423': 763,
 'ENST00000261842': 1137,
 'ENST00000265381': 837,
 'ENST00000257430': 2843,
 'ENST00000296456': 732,
 'ENST00000216099': 386,
 'ENST00000308521': 373,
 'ENST00000397278': 398,
 'ENST00000219660': 261,
 'ENST00000370283': 406,
 'ENST00000336498': 786,
 'ENST00000295095': 475,
 'ENST00000428638': 889,
 'ENST00000383472': 729,
 'ENST00000310343': 2087,
 'ENST00000393791': 731,
 'ENST00000361221': 1279,
 'ENST00000378378': 709,
 'ENST00000333677': 675,
 'ENST00000326016': 690,
 'ENST00000279873': 1188,
 'ENST00000263634': 518,
 'ENST00000531618': 181,
 'ENST00000379454': 758,
 'ENST00000320256': 343,
 'ENST00000361833': 1294,
 'ENST00000375687': 1541,
 'ENST00000238789': 1458,
 'ENST00000392017': 607,
 'ENST00000356654': 1190,
 'ENST00000306279': 321,
 'ENST00000357681': 1205,
 'ENST00000234396': 513,
 'ENST00000242839': 1465,
 'ENST00000381655': 1188,
 'ENST00000368489': 1223,
 'ENST00000310127': 1300,
 'ENST00000338821': 1047,
 'ENST00000355044': 1379,
 'ENST00000585124': 344,
 'ENST00000533140': 385,
 'ENST00000307745': 2608,
 'ENST00000286122': 519,
 'ENST00000345358': 192,
 'ENST00000358791': 211,
 'ENST00000278100': 314,
 'ENST00000269980': 445,
 'ENST00000335712': 835,
 'ENST00000378043': 585,
 'ENST00000302334': 415,
 'ENST00000399774': 195,
 'ENST00000374518': 1282,
 'ENST00000321892': 3046,
 'ENST00000259008': 1249,
 'ENST00000280758': 1104,
 'ENST00000481247': 612,
 'ENST00000302759': 1085,
 'ENST00000368821': 186,
 'ENST00000373279': 121,
 'ENST00000310799': 145,
 'ENST00000301896': 216,
 'ENST00000261191': 706,
 'ENST00000358906': 452,
 'ENST00000253233': 166,
 'ENST00000354366': 1164,
 'ENST00000348520': 573,
 'ENST00000267485': 774,
 'ENST00000380069': 722,
 'ENST00000559313': 534,
 'ENST00000219281': 265,
 'ENST00000381920': 404,
 'ENST00000389005': 620,
 'ENST00000221899': 867,
 'ENST00000359435': 329,
 'ENST00000367618': 1012,
 'ENST00000377320': 167,
 'ENST00000234827': 208,
 'ENST00000371201': 546,
 'ENST00000358293': 383,
 'ENST00000357348': 336,
 'ENST00000378106': 345,
 'ENST00000295079': 291,
 'ENST00000290536': 530,
 'ENST00000329615': 201,
 'ENST00000326085': 572,
 'ENST00000392452': 491,
 'ENST00000295268': 459,
 'ENST00000381937': 442,
 'ENST00000513200': 1275,
 'ENST00000341865': 1188,
 'ENST00000311381': 240,
 'ENST00000336600': 242,
 'ENST00000313164': 843,
 'ENST00000292330': 253,
 'ENST00000332375': 206,
 'ENST00000297203': 253,
 'ENST00000331434': 229,
 'ENST00000314330': 190,
 'ENST00000316948': 172,
 'ENST00000380701': 1326,
 'ENST00000263119': 2220,
 'ENST00000371372': 2339,
 'ENST00000350061': 2161,
 'ENST00000348261': 2353,
 'ENST00000362061': 1873,
 'ENST00000324631': 660,
 'ENST00000348335': 505,
 'ENST00000279247': 714,
 'ENST00000403897': 684,
 'ENST00000361183': 286,
 'ENST00000396946': 1154,
 'ENST00000310447': 452,
 'ENST00000432109': 479,
 'ENST00000261448': 399,
 'ENST00000312106': 780,
 'ENST00000269397': 560,
 'ENST00000424120': 1620,
 'ENST00000349456': 342,
 'ENST00000292574': 499,
 'ENST00000373053': 351,
 'ENST00000389176': 674,
 'ENST00000352312': 611,
 'ENST00000328434': 106,
 'ENST00000327554': 550,
 'ENST00000298050': 604,
 'ENST00000436346': 1871,
 'ENST00000356786': 1476,
 'ENST00000335119': 588,
 'ENST00000334619': 447,
 'ENST00000361115': 127,
 'ENST00000292301': 374,
 'ENST00000258091': 543,
 'ENST00000256447': 661,
 'ENST00000289429': 327,
 'ENST00000245903': 193,
 'ENST00000310955': 499,
 'ENST00000249014': 391,
 'ENST00000301200': 148,
 'ENST00000367435': 531,
 'ENST00000299752': 829,
 'ENST00000372262': 828,
 'ENST00000506784': 504,
 'ENST00000325303': 346,
 'ENST00000304494': 156,
 'ENST00000301019': 546,
 'ENST00000292672': 485,
 'ENST00000397527': 2442,
 'ENST00000377990': 757,
 'ENST00000369582': 116,
 'ENST00000314103': 559,
 'ENST00000330494': 2000,
 'ENST00000399982': 2581,
 'ENST00000255409': 383,
 'ENST00000320658': 466,
 'ENST00000370263': 627,
 'ENST00000332272': 395,
 'ENST00000258930': 187,
 'ENST00000261833': 2027,
 'ENST00000265593': 898,
 'ENST00000513761': 818,
 'ENST00000328796': 220,
 'ENST00000325617': 610,
 'ENST00000368361': 499,
 'ENST00000337392': 669,
 'ENST00000324262': 475,
 'ENST00000329903': 664,
 'ENST00000305510': 707,
 'ENST00000221232': 753,
 'ENST00000265136': 1261,
 'ENST00000299886': 980,
 'ENST00000347053': 839,
 'ENST00000307149': 770,
 'ENST00000370096': 1806,
 'ENST00000322507': 3063,
 'ENST00000359759': 1754,
 'ENST00000380518': 1487,
 'ENST00000304636': 1466,
 'ENST00000360467': 1712,
 'ENST00000372216': 1691,
 'ENST00000334571': 468,
 'ENST00000262428': 142,
 'ENST00000016171': 410,
 'ENST00000389912': 106,
 'ENST00000268720': 633,
 'ENST00000383811': 420,
 'ENST00000354336': 303,
 'ENST00000378863': 301,
 'ENST00000397890': 572,
 'ENST00000320954': 401,
 'ENST00000354760': 196,
 'ENST00000215855': 211,
 'ENST00000374466': 542,
 'ENST00000297405': 3707,
 'ENST00000312134': 149,
 'ENST00000361367': 1173,
 'ENST00000216336': 255,
 'ENST00000160373': 1663,
 'ENST00000296026': 107,
 'ENST00000295683': 350,
 'ENST00000285106': 656,
 'ENST00000318911': 325,
 'ENST00000369887': 508,
 'ENST00000285949': 522,
 'ENST00000301146': 494,
 'ENST00000285979': 490,
 'ENST00000334636': 501,
 'ENST00000366795': 774,
 'ENST00000332700': 339,
 'ENST00000319675': 395,
 'ENST00000332395': 540,
 'ENST00000371148': 67,
 'ENST00000382209': 78,
 'ENST00000454345': 1117,
 'ENST00000445061': 1194,
 'ENST00000496811': 1008,
 'ENST00000268482': 1227,
 'ENST00000457308': 472,
 'ENST00000367549': 1270,
 'ENST00000400324': 1193,
 'ENST00000343455': 1922,
 'ENST00000266070': 2240,
 'ENST00000339266': 992,
 'ENST00000375847': 782,
 'ENST00000341772': 737,
 'ENST00000254579': 4753,
 'ENST00000355305': 869,
 'ENST00000343572': 308,
 'ENST00000266037': 2030,
 'ENST00000437633': 1966,
 'ENST00000340370': 2109,
 'ENST00000432829': 2031,
 'ENST00000376460': 2068,
 'ENST00000398665': 1537,
 'ENST00000404039': 801,
 'ENST00000371579': 492,
 'ENST00000414645': 723,
 'ENST00000338492': 572,
 'ENST00000331677': 958,
 'ENST00000257189': 999,
 'ENST00000379802': 2871,
 'ENST00000367162': 929,
 'ENST00000296161': 740,
 'ENST00000298573': 143,
 'ENST00000331588': 625,
 'ENST00000360184': 4646,
 'ENST00000323039': 629,
 'ENST00000258104': 2080,
 'ENST00000355311': 596,
 'ENST00000402825': 883,
 'ENST00000367682': 904,
 'ENST00000374492': 578,
 'ENST00000337938': 238,
 'ENST00000307998': 443,
 'ENST00000426333': 972,
 'ENST00000275493': 1210,
 'ENST00000303961': 407,
 'ENST00000220325': 541,
 'ENST00000216190': 548,
 'ENST00000290246': 720,
 'ENST00000393997': 773,
 'ENST00000254528': 1053,
 'ENST00000394773': 896,
 'ENST00000297375': 333,
 'ENST00000357639': 875,
 'ENST00000263253': 2414,
 'ENST00000389561': 3123,
 'ENST00000337057': 1005,
 'ENST00000374566': 900,
 'ENST00000263713': 733,
 'ENST00000330394': 998,
 'ENST00000248070': 864,
 'ENST00000361965': 593,
 'ENST00000254928': 437,
 'ENST00000342788': 1308,
 'ENST00000288221': 957,
 'ENST00000262109': 443,
 'ENST00000377828': 854,
 'ENST00000265843': 1989,
 'ENST00000367797': 2224,
 'ENST00000321420': 861,
 'ENST00000378116': 890,
 'ENST00000409072': 135,
 'ENST00000265299': 757,
 'ENST00000257515': 450,
 'ENST00000313766': 584,
 'ENST00000329759': 423,
 'ENST00000361539': 783,
 'ENST00000367462': 766,
 'ENST00000370310': 428,
 'ENST00000358369': 593,
 'ENST00000283357': 452,
 'ENST00000297532': 549,
 'ENST00000298047': 4589,
 'ENST00000394329': 4981,
 'ENST00000484457': 423,
 'ENST00000331272': 412,
 'ENST00000252771': 889,
 'ENST00000217289': 677,
 'ENST00000341590': 680,
 'ENST00000168712': 206,
 'ENST00000264748': 504,
 'ENST00000230124': 907,
 'ENST00000325888': 2725,
 'ENST00000335154': 1027,
 'ENST00000297267': 1894,
 'ENST00000509018': 1601,
 'ENST00000312562': 271,
 'ENST00000396057': 325,
 'ENST00000376708': 432,
 'ENST00000313071': 489,
 'ENST00000329798': 2139,
 'ENST00000357447': 1039,
 'ENST00000317568': 464,
 'ENST00000358350': 3013,
 'ENST00000427159': 847,
 'ENST00000310160': 365,
 'ENST00000313777': 418,
 'ENST00000357559': 621,
 'ENST00000286201': 574,
 'ENST00000393564': 515,
 'ENST00000259455': 941,
 'ENST00000311550': 473,
 'ENST00000192314': 398,
 'ENST00000392701': 633,
 'ENST00000249041': 368,
 'ENST00000356638': 944,
 'ENST00000266754': 694,
 'ENST00000341105': 480,
 'ENST00000370466': 591,
 'ENST00000370459': 586,
 'ENST00000329913': 364,
 'ENST00000309859': 613,
 'ENST00000574154': 493,
 'ENST00000278765': 225,
 'ENST00000275732': 1035,
 'ENST00000225394': 761,
 'ENST00000378695': 242,
 'ENST00000324333': 775,
 'ENST00000262958': 374,
 'ENST00000303210': 340,
 'ENST00000163416': 731,
 'ENST00000265070': 298,
 'ENST00000401815': 560,
 'ENST00000170564': 931,
 'ENST00000377067': 572,
 'ENST00000310454': 727,
 'ENST00000370652': 3080,
 'ENST00000315843': 814,
 'ENST00000309180': 319,
 'ENST00000342292': 2367,
 'ENST00000332262': 838,
 'ENST00000234142': 1949,
 'ENST00000392870': 590,
 'ENST00000355472': 576,
 'ENST00000404338': 1499,
 'ENST00000538487': 912,
 'ENST00000276708': 508,
 'ENST00000338595': 243,
 'ENST00000553612': 376,
 'ENST00000394456': 517,
 'ENST00000265755': 959,
 'ENST00000264424': 619,
 'ENST00000254854': 1103,
 'ENST00000304895': 651,
 'ENST00000264553': 257,
 'ENST00000373255': 372,
 'ENST00000380649': 763,
 'ENST00000231121': 215,
 'ENST00000306560': 553,
 'ENST00000534862': 506,
 'ENST00000303230': 890,
 'ENST00000345617': 1084,
 'ENST00000391975': 1268,
 'ENST00000184956': 1181,
 'ENST00000395891': 1606,
 'ENST00000315765': 1159,
 'ENST00000261609': 4834,
 'ENST00000377670': 669,
 'ENST00000321331': 93,
 'ENST00000336926': 1037,
 'ENST00000263208': 1017,
 'ENST00000303910': 130,
 'ENST00000292432': 923,
 'ENST00000354624': 917,
 'ENST00000336648': 726,
 'ENST00000357878': 357,
 'ENST00000351839': 463,
 'ENST00000343060': 335,
 'ENST00000317201': 443,
 'ENST00000222726': 270,
 'ENST00000406506': 270,
 'ENST00000262626': 417,
 'ENST00000304031': 392,
 'ENST00000334701': 854,
 'ENST00000369209': 675,
 'ENST00000309758': 643,
 'ENST00000262854': 4374,
 'ENST00000336307': 417,
 'ENST00000306270': 1353,
 'ENST00000372491': 404,
 'ENST00000295809': 785,
 'ENST00000426508': 1462,
 'ENST00000352385': 1250,
 'ENST00000321016': 1349,
 'ENST00000295981': 791,
 'ENST00000264260': 599,
 'ENST00000270800': 574,
 'ENST00000391826': 567,
 'ENST00000344209': 546,
 'ENST00000271417': 639,
 'ENST00000331762': 175,
 'ENST00000403263': 1027,
 'ENST00000331075': 1006,
 'ENST00000310227': 510,
 'ENST00000523731': 995,
 'ENST00000402050': 695,
 'ENST00000268182': 1657,
 'ENST00000256458': 625,
 'ENST00000231357': 519,
 'ENST00000342219': 571,
 'ENST00000266041': 930,
 'ENST00000439118': 555,
 'ENST00000381318': 1721,
 'ENST00000295321': 819,
 'ENST00000341776': 1246,
 'ENST00000261247': 311,
 'ENST00000399262': 2540,
 'ENST00000284262': 748,
 'ENST00000225916': 837,
 'ENST00000356157': 538,
 'ENST00000432196': 458,
 'ENST00000379485': 674,
 'ENST00000369771': 511,
 'ENST00000369769': 575,
 'ENST00000303790': 404,
 'ENST00000371741': 858,
 'ENST00000379472': 511,
 'ENST00000477616': 757,
 'ENST00000240662': 424,
 'ENST00000340700': 538,
 'ENST00000303015': 374,
 'ENST00000382082': 545,
 'ENST00000159111': 1096,
 'ENST00000414716': 1554,
 'ENST00000338205': 1839,
 'ENST00000348624': 807,
 'ENST00000297063': 520,
 'ENST00000296564': 2266,
 'ENST00000393151': 2635,
 'ENST00000398130': 1216,
 'ENST00000160298': 1249,
 'ENST00000422774': 1950,
 'ENST00000325212': 2601,
 'ENST00000338005': 534,
 'ENST00000376572': 634,
 'ENST00000326047': 1388,
 'ENST00000247986': 1029,
 'ENST00000320389': 1690,
 'ENST00000422435': 1637,
 'ENST00000379166': 1368,
 'ENST00000407071': 2108,
 'ENST00000288135': 976,
 'ENST00000296233': 416,
 'ENST00000309755': 587,
 'ENST00000594768': 282,
 'ENST00000391807': 253,
 'ENST00000251643': 494,
 'ENST00000167586': 472,
 'ENST00000417996': 628,
 'ENST00000393989': 455,
 'ENST00000293774': 594,
 'ENST00000252245': 551,
 'ENST00000399889': 175,
 'ENST00000427442': 840,
 'ENST00000389658': 3075,
 'ENST00000356082': 1172,
 'ENST00000361069': 1575,
 'ENST00000305641': 686,
 'ENST00000323076': 627,
 'ENST00000215909': 135,
 'ENST00000341872': 317,
 'ENST00000263274': 919,
 'ENST00000391736': 448,
 'ENST00000449561': 591,
 'ENST00000336180': 647,
 'ENST00000368820': 593,
 'ENST00000244289': 1076,
 'ENST00000316843': 1064,
 'ENST00000294816': 382,
 'ENST00000389484': 4599,
 'ENST00000263816': 4655,
 'ENST00000313838': 523,
 'ENST00000367175': 713,
 'ENST00000378858': 740,
 'ENST00000265245': 658,
 'ENST00000356396': 732,
 'ENST00000301873': 1303,
 'ENST00000231751': 710,
 'ENST00000367576': 475,
 'ENST00000266718': 338,
 'ENST00000372915': 7388,
 'ENST00000265854': 718,
 'ENST00000402939': 1462,
 'ENST00000371589': 699,
 'ENST00000374332': 630,
 'ENST00000261483': 1144,
 'ENST00000285599': 1009,
 'ENST00000300231': 2803,
 'ENST00000267079': 859,
 'ENST00000392142': 1608,
 'ENST00000359221': 464,
 'ENST00000308406': 816,
 'ENST00000262410': 758,
 'ENST00000251472': 1570,
 'ENST00000262811': 1309,
 'ENST00000403625': 2623,
 'ENST00000407073': 1494,
 'ENST00000555147': 317,
 'ENST00000265056': 904,
 'ENST00000264156': 821,
 'ENST00000281928': 2210,
 'ENST00000276282': 1052,
 'ENST00000281416': 791,
 'ENST00000261537': 1006,
 'ENST00000505820': 1070,
 'ENST00000301067': 5537,
 'ENST00000246912': 298,
 'ENST00000219271': 669,
 'ENST00000246186': 645,
 'ENST00000260229': 513,
 'ENST00000302326': 1320,
 'ENST00000252971': 401,
 'ENST00000357066': 217,
 'ENST00000223114': 341,
 'ENST00000397641': 1032,
 'ENST00000225275': 745,
 'ENST00000463290': 248,
 'ENST00000278937': 215,
 'ENST00000303375': 1479,
 'ENST00000276585': 187,
 'ENST00000442466': 702,
 'ENST00000296003': 650,
 'ENST00000338779': 747,
 'ENST00000441003': 2817,
 'ENST00000344663': 711,
 'ENST00000522677': 752,
 'ENST00000226207': 1939,
 'ENST00000252172': 1938,
 'ENST00000376970': 2028,
 'ENST00000394809': 819,
 'ENST00000300119': 1043,
 'ENST00000318217': 1006,
 'ENST00000265944': 1616,
 'ENST00000409709': 2215,
 'ENST00000594824': 2157,
 'ENST00000262113': 1465,
 'ENST00000374434': 1437,
 'ENST00000358913': 1320,
 'ENST00000328439': 1121,
 'ENST00000300131': 525,
 'ENST00000251127': 1738,
 'ENST00000261520': 982,
 'ENST00000205194': 206,
 'ENST00000272425': 227,
 'ENST00000367296': 1877,
 'ENST00000449802': 2694,
 'ENST00000315579': 1401,
 'ENST00000251496': 1015,
 'ENST00000290231': 579,
 'ENST00000396355': 335,
 'ENST00000260361': 327,
 'ENST00000313468': 210,
 'ENST00000172853': 6669,
 'ENST00000310624': 1020,
 'ENST00000429845': 1172,
 'ENST00000357134': 810,
 'ENST00000391969': 484,
 'ENST00000339876': 1240,
 'ENST00000427363': 943,
 'ENST00000374092': 457,
 'ENST00000302101': 133,
 'ENST00000427025': 1610,
 'ENST00000264187': 1247,
 'ENST00000278886': 1382,
 'ENST00000374762': 247,
 'ENST00000295886': 367,
 'ENST00000301295': 994,
 'ENST00000378165': 498,
 'ENST00000287139': 347,
 'ENST00000377705': 702,
 'ENST00000275820': 860,
 'ENST00000317775': 1434,
 'ENST00000277541': 2555,
 'ENST00000263388': 2321,
 'ENST00000311034': 802,
 'ENST00000269228': 1278,
 'ENST00000379987': 565,
 'ENST00000342694': 1047,
 'ENST00000399953': 568,
 'ENST00000393716': 434,
 'ENST00000393102': 596,
 'ENST00000406316': 1477,
 'ENST00000296802': 260,
 'ENST00000264670': 767,
 'ENST00000270235': 489,
 'ENST00000306928': 410,
 'ENST00000392568': 222,
 'ENST00000231498': 1391,
 'ENST00000285968': 2012,
 'ENST00000368559': 1888,
 'ENST00000552788': 1564,
 'ENST00000368845': 439,
 'ENST00000422127': 7968,
 'ENST00000404537': 1896,
 'ENST00000215061': 264,
 'ENST00000434106': 829,
 'ENST00000518659': 2774,
 'ENST00000374103': 1010,
 'ENST00000344629': 345,
 'ENST00000373580': 652,
 'ENST00000491143': 504,
 'ENST00000426825': 1288,
 'ENST00000318763': 346,
 'ENST00000359688': 307,
 'ENST00000259466': 311,
 'ENST00000408898': 310,
 'ENST00000343414': 316,
 'ENST00000355728': 308,
 'ENST00000309562': 309,
 'ENST00000302572': 314,
 'ENST00000279791': 310,
 'ENST00000303059': 340,
 'ENST00000368146': 331,
 'ENST00000248073': 320,
 'ENST00000308682': 312,
 'ENST00000303039': 316,
 'ENST00000263650': 879,
 'ENST00000331427': 562,
 'ENST00000203664': 234,
 'ENST00000338352': 288,
 'ENST00000196371': 520,
 'ENST00000442977': 874,
 'ENST00000220597': 432,
 'ENST00000358301': 591,
 'ENST00000353224': 719,
 'ENST00000395842': 677,
 'ENST00000554301': 1278,
 'ENST00000404991': 636,
 'ENST00000367662': 1791,
 'ENST00000234040': 1323,
 'ENST00000231484': 1184,
 'ENST00000377918': 1159,
 'ENST00000344876': 1135,
 'ENST00000398631': 941,
 'ENST00000526136': 948,
 'ENST00000231137': 793,
 'ENST00000394576': 932,
 'ENST00000398604': 932,
 'ENST00000319441': 622,
 'ENST00000333891': 5142,
 'ENST00000325083': 2024,
 'ENST00000367384': 286,
 'ENST00000360540': 357,
 'ENST00000359568': 3336,
 'ENST00000355703': 2034,
 'ENST00000300954': 755,
 'ENST00000320934': 785,
 'ENST00000302118': 692,
 'ENST00000379144': 369,
 'ENST00000438447': 2839,
 'ENST00000370215': 517,
 'ENST00000380118': 394,
 'ENST00000254657': 1255,
 'ENST00000300056': 247,
 'ENST00000467460': 626,
 'ENST00000318471': 323,
 'ENST00000498926': 289,
 'ENST00000300658': 320,
 'ENST00000359650': 373,
 'ENST00000396396': 567,
 'ENST00000359246': 1096,
 'ENST00000361417': 1377,
 'ENST00000243924': 117,
 'ENST00000255882': 2102,
 'ENST00000344529': 297,
 'ENST00000078527': 493,
 'ENST00000262265': 290,
 'ENST00000367187': 1634,
 'ENST00000263967': 1068,
 'ENST00000521381': 724,
 'ENST00000388747': 394,
 'ENST00000361189': 708,
 'ENST00000289672': 2849,
 'ENST00000371117': 4074,
 'ENST00000262300': 499,
 'ENST00000290472': 818,
 'ENST00000246229': 496,
 'ENST00000340093': 335,
 'ENST00000378486': 1416,
 'ENST00000418129': 1001,
 'ENST00000322810': 4684,
 'ENST00000263265': 779,
 'ENST00000394691': 1219,
 'ENST00000329153': 1364,
 'ENST00000591022': 793,
 'ENST00000300093': 603,
 'ENST00000321063': 1894,
 'ENST00000359337': 1838,
 'ENST00000361971': 1909,
 'ENST00000371717': 525,
 'ENST00000313683': 439,
 'ENST00000414982': 1375,
 'ENST00000277531': 1317,
 'ENST00000312553': 661,
 'ENST00000271715': 1410,
 'ENST00000252115': 421,
 'ENST00000371984': 660,
 'ENST00000465342': 359,
 'ENST00000549396': 1257,
 'ENST00000334186': 1194,
 'ENST00000447715': 1185,
 'ENST00000345988': 1756,
 'ENST00000608933': 372,
 'ENST00000202556': 1090,
 'ENST00000299824': 567,
 'ENST00000340694': 1098,
 'ENST00000375153': 291,
 'ENST00000270722': 1276,
 'ENST00000340385': 224,
 'ENST00000370689': 351,
 'ENST00000360274': 381,
 'ENST00000306156': 737,
 'ENST00000317620': 834,
 'ENST00000266079': 941,

In [50]:
dataMutation_Seshagiri_cleaned['Protein_Length'] = dataMutation_Seshagiri_cleaned['Transcript_ID'].map(transcriptIds_proteinIds_mapping)
dataMutation_Seshagiri_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,587220,A1CF,A1CF,10,52573792,52573792,+,Missense_Mutation,SNP,G,G,A,ENST00000373993.1:c.1172C>T,p.A391V,391.0,ENST00000373993,86267,1,594
1,587220,A4GALT,A4GALT,22,43089044,43089044,+,Missense_Mutation,SNP,G,G,A,ENST00000249005.2:c.914C>T,p.P305L,305.0,ENST00000249005,29178,1,353
2,587220,AARS2,AARS2,6,44272932,44272932,+,Missense_Mutation,SNP,G,G,A,ENST00000244571.4:c.1438C>T,p.R480W,480.0,ENST00000244571,13673,1,985
3,587220,ABCA1,ABCA1,9,107620834,107620834,+,Missense_Mutation,SNP,C,C,T,ENST00000374736.3:c.689G>A,p.R230H,230.0,ENST00000374736,147236,1,2261
4,587220,ABCA12,ABCA12,2,215840638,215840638,+,Missense_Mutation,SNP,A,A,G,ENST00000272895.7:c.5252T>C,p.V1751A,1751.0,ENST00000272895,206886,1,2595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36266,587400,WRNIP1,WRNIP1,6,2766302,2766302,+,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.446C>A,p.A149E,149.0,ENST00000380773,21539,1,665
36267,587400,XKRX,XKRX,X,100183004,100183004,+,Missense_Mutation,SNP,G,G,A,ENST00000372956.2:c.290C>T,p.P97L,97.0,ENST00000372956,15992,1,449
36268,587400,ZNF256,ZNF256,19,58452579,58452579,+,Missense_Mutation,SNP,T,T,G,ENST00000282308.3:c.1597A>C,p.S533R,533.0,ENST00000282308,6843,1,627
36269,587400,ZNF300,ZNF300,5,150275726,150275726,+,Missense_Mutation,SNP,C,C,T,ENST00000274599.5:c.1075G>A,p.G359R,359.0,ENST00000274599,10592,1,604
36270,587400,ZSWIM4,ZSWIM4,19,13923841,13923841,+,Missense_Mutation,SNP,C,C,T,ENST00000254323.2:c.1043C>T,p.P348L,348.0,ENST00000254323,36771,1,989

In [51]:
dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Protein_Length'].isna()]

Empty DataFrame
Columns: [Tumor_Sample_Barcode, Hugo_Symbol, original_Hugo_Symbol, Chromosome, Start_Position, End_Position, Strand, Variant_Classification, Variant_Type, Reference_Allele, Tumor_Seq_Allele1, Tumor_Seq_Allele2, HGVSc, HGVSp_Short, Protein_position, Transcript_ID, Gene_Length, Mutation_Length, Protein_Length]
Index: []

In [52]:
### TODO: What to do with nan protein length? for now remove
dataMutation_Seshagiri_cleaned = dataMutation_Seshagiri_cleaned[~dataMutation_Seshagiri_cleaned['Protein_Length'].isna()]

In [53]:
dataMutation_Seshagiri_cleaned[dataMutation_Seshagiri_cleaned['Protein_Length'].isna()]

Empty DataFrame
Columns: [Tumor_Sample_Barcode, Hugo_Symbol, original_Hugo_Symbol, Chromosome, Start_Position, End_Position, Strand, Variant_Classification, Variant_Type, Reference_Allele, Tumor_Seq_Allele1, Tumor_Seq_Allele2, HGVSc, HGVSp_Short, Protein_position, Transcript_ID, Gene_Length, Mutation_Length, Protein_Length]
Index: []

In [54]:
#save cleaned data
dataMutation_Seshagiri_cleaned.to_csv(data['Seshagiri_all___mutations'], sep="\t", index=False)

In [55]:
# clean memory
del dataMutation_Seshagiri, dataMutation_Seshagiri_cleaned

### Clinical Samples

In [56]:
dataClinicalSample_Seshagiri = pd.read_csv(data['original___Seshagiri___samples'], sep='\t', engine='python', comment='#')

In [57]:
dataClinicalSample_Seshagiri

,PATIENT_ID,SAMPLE_ID,TUMOR_TYPE,TISSUE_SOURCE_SITE,MSI_STATUS,TUMOR_CONTENT,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS
0,12912,587220,colon,Tumor,MSI,60,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
1,12914,587222,colon,Tumor,MSS,60,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
2,12915,587224,colon,Tumor,MSI,60,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
3,12919,587226,colon,Tumor,MSI,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
4,12926,587228,colon,Tumor,MSI,90,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
...,...,...,...,...,...,...,...,...,...,...
69,34994,587394,colon,Tumor,MSS,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
70,34997,587398,colon,Tumor,MSS,40,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
71,35001,587400,colon,Tumor,MSS,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
72,14962,587236,colon,Tumor,MSS,30,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
73,32758,587326,colon,Tumor,MSS,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched

In [58]:
dataClinicalSample_Seshagiri.to_csv(data['Seshagiri_all___samples'], sep='\t', index=False)

In [59]:
del dataClinicalSample_Seshagiri

## TCGA

### Mutation

In [60]:
dataMutation_TCGA = pd.read_csv(data['original___TCGA___mutations'], sep='\t', engine='python', comment='#')

In [61]:
dataMutation_TCGA

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,dbSNP_RS,dbSNP_Val_Status,Tumor_Sample_Barcode,Matched_Norm_Sample_Barcode,Match_Norm_Seq_Allele1,Match_Norm_Seq_Allele2,Tumor_Validation_Allele1,Tumor_Validation_Allele2,Match_Norm_Validation_Allele1,Match_Norm_Validation_Allele2,Verification_Status,Validation_Status,Mutation_Status,Sequencing_Phase,Sequence_Source,Validation_Method,Score,BAM_File,Sequencer,t_ref_count,t_alt_count,n_ref_count,n_alt_count,HGVSc,HGVSp,HGVSp_Short,Transcript_ID,RefSeq,Protein_position,Codons,Hotspot,NCALLERS,ALLELE_NUM,PICK,UNIPARC,n_depth,Feature,CONTEXT,CLIN_SIG,Gene,HGNC_ID,MERGESOURCE,ExAC_AF_AMR,t_depth,DISTANCE,SYMBOL_SOURCE,Existing_variation,SYMBOL,ExAC_AF_SAS,VARIANT_CLASS,AA_MAF,HIGH_INF_POS,GENE_PHENO,ExAC_AF_AFR,ASN_MAF,PHENO,BIOTYPE,AFR_MAF,DOMAINS,MOTIF_SCORE_CHANGE,Amino_acids,EA_MAF,Allele,cDNA_position,ExAC_AF_NFE,SIFT,INTRON,TREMBL,AMR_MAF,EAS_MAF,CANONICAL,DBVS,all_effects,ExAC_AF_EAS,GMAF,MOTIF_NAME,TSL,SOMATIC,MOTIF_POS,IMPACT,CDS_position,COSMIC,SWISSPROT,ExAC_AF_FIN,EUR_MAF,Feature_type,HGVS_OFFSET,PolyPhen,FILTER,ENSP,ExAC_AF,CENTERS,CCDS,EXON,ExAC_AF_OTH,SAS_MAF,Exon_Number,MINIMISED,PUBMED
0,WDR37,0,.,GRCh37,10,1130478,1130478,+,"missense_variant,splice_region_variant",Missense_Mutation,SNP,G,G,A,.,.,TCGA-AF-2687-01,TCGA-AF-2687-10,G,G,.,.,.,.,.,.,.,.,.,.,.,.,.,93,40,81,0,ENST00000263150.4:c.532G>A,p.Asp178Asn,p.D178N,ENST00000263150,NM_014023.3,178.0,Gat/Aat,0.0,5,.,.,UPI000013D3B7,81,ENST00000358220,CAGCCGGTGAG,.,ENSG00000047056,31406,PRIMARY,.,133,.,HGNC,COSM1560977,WDR37,.,SNV,.,.,.,.,.,1,protein_coding,.,"PROSITE_profiles:PS50294,PROSITE_profiles:PS50...",.,D/N,.,A,676,.,deleterious(0),.,A8K976_HUMAN,.,.,YES,.,"WDR37,missense_variant,p.Asp178Asn,ENST0000026...",.,.,.,.,1,.,MODERATE,532,NONE,WDR37_HUMAN,.,.,Transcript,.,probably_damaging(0.989),PASS,ENSP00000350954,.,SOMATICSNIPER|RADIA|MUTECT|MUSE|VARSCANS,CCDS7057.1,14-Jun,.,.,14-Jun,.,.
1,HSPA14,0,.,GRCh37,10,14896137,14896137,+,missense_variant,Missense_Mutation,SNP,G,G,A,novel,.,TCGA-AF-2687-01,TCGA-AF-2687-10,G,G,.,.,.,.,.,.,.,.,.,.,.,.,.,89,10,135,1,ENST00000378372.3:c.748G>A,p.Asp250Asn,p.D250N,ENST00000378372,NM_016299.3,250.0,Gat/Aat,0.0,4,.,.,UPI000013D6A8,136,ENST00000378372,AACATGATGTG,.,ENSG00000187522,29526,PRIMARY,.,100,.,HGNC,.,HSPA14,.,SNV,.,.,.,.,.,.,protein_coding,.,"hmmpanther:PTHR19375,hmmpanther:PTHR19375:SF15...",.,D/N,.,A,987,.,deleterious(0.02),.,B4DYI5_HUMAN,.,.,YES,.,"HSPA14,missense_variant,p.Asp250Asn,ENST000003...",.,.,.,.,.,.,MODERATE,748,NONE,HSP7E_HUMAN,.,.,Transcript,.,benign(0.092),PASS,ENSP00000367623,.,RADIA|MUTECT|MUSE|VARSCANS,CCDS7103.1,14-Sep,.,.,14-Sep,.,.
2,ARHGAP20,0,.,GRCh37,11,110450666,110450666,+,missense_variant,Missense_Mutation,SNP,G,G,A,rs760923229,.,TCGA-AF-2687-01,TCGA-AF-2687-10,G,G,.,.,.,.,.,.,.,.,.,.,.,.,.,102,16,71,0,ENST00000260283.4:c.3004C>T,p.Pro1002Ser,p.P1002S,ENST00000260283,NM_020809.3,1002.0,Ccc/Tcc,0.0,4,.,.,UPI000013D0BA,71,ENST00000260283,ACCGGGCATTC,.,ENSG00000137727,18357,PRIMARY,.,119,.,HGNC,"rs760923229,COSM1561100",ARHGAP20,.,SNV,.,.,.,.,.,"0,1",protein_coding,.,"hmmpanther:PTHR23179,hmmpanther:PTHR23179:SF24",.,P/S,.,A,3289,.,tolerated(0.27),.,.,.,.,YES,.,"ARHGAP20,missense_variant,p.Pro1002Ser,ENST000...",.,.,.,.,"0,1",.,MODERATE,3004,NONE,RHG20_HUMAN,.,.,Transcript,.,benign(0.143),PASS,ENSP00000260283,.,RADIA|MUTECT|MUSE|VARSCANS,CCDS31673.1,16/16,.,.,16/16,.,.
3,STT3A,0,.,GRCh37,11,125478127,125478127,+,missense_variant,Missense_Mutation,SNP,G,G,A,rs765580288,.,TCGA-AF-2687-01,TCGA-AF-2687-10,G,G,.,.,.,.,.,.,.,.,.,.,.,.,.,168,26,150,0,ENST00000392708.4:c.904G>A,p.Val302Ile,p.V302I,ENST00000392708,NM_001278503.1,302.0,Gtc/Atc,0.0,4,.,.,UPI0000071627,150,ENST00000392708,GGAGCGTCATC,.,ENSG00000134910,6172,PRIMARY,.,195,.,HGNC,"rs765580288,COSM1561538",STT3A,.,SNV,.,.,.,.,.,"0,1",protein_coding,.,"Transmembrane_helices:TMhelix,hmmpanther:PTHR1...",.,V/I,.,A,1063,.,tolerated(0.4),.,"E9PNQ1_HUMAN,E9PN73_HUMAN,E9PIJ8_HUMAN,E9PI32_...",.,.,YES,.,"STT3A,missense_variant,p.Val302Ile,ENST0000039...",.,.,.,.,"0,1",.,MODERATE,904,NONE,STT3A_HUMAN,.,.,Transcript,.,benign(0.009),PASS,ENSP00000376472,.,RADIA|MUTECT|MUSE|VARSCANS,CCDS8458.1,18-Sep,.,.,18-Sep,.,.
4,ANO3,0,.,GRCh37,11,26620415,26620415,+,missense_variant,Missense_Mutation,SNP,G,G,A,rs199929076,.,TCGA-AF-2687-01,TCGA-AF-2687-10,G,G,.,.,.,.,.,.,.,.,.,.,.,.,.,41,19,130,0,ENST00000256737.3:c.1541G>A,p.Arg514His,p.R514H,ENST00000256737,NM_031418.2,514.0,cGt/cAt,0.0,5,.,.,UPI00001F9ED8,130,ENST00000256737,ACTTCGTCCCC,.,ENSG00000134343,14004,PRIMARY,.,60,.,HGNC,"rs199929076,COSM1475347",ANO3,.,SNV,.,.,.,.,.,"0,1",protein_coding,A:0,"hmmpanther:PTHR12308:SF16,hmmpanther:PTHR12308...",.,R/H,.,A,2393,.,deleterious(0),.,"E9PQ79_HUMAN,B7Z3F5_HUMAN,B7Z3A8_HUMAN",A:0,A:0,YES,byCluster|by1000G,"ANO3,missense_variant,p.Arg368His,ENST00000531...",.,A:0.0002,.,.,"0,1",.,MODERATE,1541,SITE|p.R514H|c.1541G>A|3,ANO3_HUMAN,.,A:0.001,Transcript,.,probably_damaging(0.997),PASS,ENSP00000256737,.,SOMATICSNIPER|RADIA|MUTECT|MUSE|VARSCANS,CCDS31447.1,16/27,.,A:0,16/27,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332605,FFAR3,0,.,GRCh37,19,35849879,35862348,+,"splice_acceptor_variant,splice_donor_variant,c...",Splice_Site,DEL,CCCCCTCAACCTGCTGGCCCTGGTGGTCTTCGTGGGCAAGCTGCAG...,CCCCCTCAACCTGCTGGCCCTGGTGGTCTTCGTGGGCAAGCTGCAG...,-,novel,.,TCGA-D5-6928-01,TCGA-D5-6928-10,CCCCCTCAACCTGCTGGCCCTGGTGGTCTTCGTGGGCAAGCTGCAG...,CCCCCTCAACCTGCTGGCCCTGGTGGTCTTCGTGGGCAAGCTGCAG...,.,.,.,.,.,.,.,.,.,.,.,.,.,368,96,253,0,NaN,NaN,NaN,ENST00000454971,NaN,NaN,NaN,0.0,3,.,.,UPI0000001C3F,253,ENST00000327809,GGGGCTCCCCCTCAACCTGCTGGCCCTGGTGGTCTTCGTGGGCAAG...,.,ENSG00000185897,4499,PRIMARY,.,464,.,HGNC,.,FFAR3,.,deletion,.,.,.,.,.,.,protein_coding,.,.,.,.,.,-,288-?,.,.,.,.,.,.,YES,.,"FFAR3,coding_sequence_variant,,ENST00000327809...",.,.,.,.,.,.,MODIFIER,87-?,BUFFER|p.L294L|c.880T>C|3,FFAR3_HUMAN,.,.,Transcript,.,.,PASS,ENSP00000328230,.,INDELOCATOR*|VARSCANI*|PINDEL,CCDS12459.1,2-Feb,.,.,2-Feb,.,.
332606,ZNF799,0,.,GRCh37,19,12502563,12542338,+,"splice_acceptor_variant,splice_donor_variant,c...",Splice_Site,DEL,TCTCATGCATATGTAATAAACTGGGCCAAAAAAACGCTTTCCCACA...,TCTCATGCATATGTAATAAACTGGGCCAAAAAAACGCTTTCCCACA...,-,novel,.,TCGA-F4-6461-01,TCGA-F4-6461-10,TCTCATGCATATGTAATAAACTGGGCCAAAAAAACGCTTTCCCACA...,TCTCATGCATATGTAATAAACTGGGCCAAAAAAACGCTTTCCCACA...,.,.,.,.,.,.,.,.,.,.,.,.,.,129,39,171,0,NaN,NaN,NaN,ENST00000430385,NM_001080821.2,NaN,NaN,0.0,3,.,.,UPI000016184E,171,ENST00000430385,GCGTTCTCTCATGCATATGTAATAAACTGGGCCAAAAAAACGCTTT...,.,ENSG00000196466,28071,PRIMARY,.,168,.,HGNC,.,ZNF799,.,deletion,.,.,.,.,.,.,protein_coding,.,.,.,.,.,-,?-850,.,.,1/3/03,"M0R135_HUMAN,D3YTF2_HUMAN",.,.,YES,.,"ZNF799,transcript_ablation,,ENST00000595766,;C...",.,.,.,.,.,.,HIGH,?-649,"BUFFER|p.P615P|c.1845G>A|4,BUFFER|p.R301I|c.90...",ZN799_HUMAN,.,.,Transcript,.,.,PASS,ENSP00000411084,.,INDELOCATOR*|VARSCANI*|PINDEL,CCDS45989.1,1/4/04,.,.,1/4/04,.,.
332607,ITGA6,0,.,GRCh37,2,173368938,173368990,+,"coding_sequence_variant,3_prime_UTR_variant",3'UTR,DEL,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,-,novel,.,TCGA-G4-6588-01,TCGA-G4-6588-10,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,.,.,.,.,.,.,.,.,.,.,.,.,.,135,15,206,0,NaN,NaN,NaN,ENST00000442250,NaN,1117.0,NaN,0.0,2,.,.,UPI0000EA87E5,206,ENST00000409080,AAAAAAACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCA...,.,ENSG00000091409,6142,PRIMARY,.,150,.,HGNC,.,ITGA6,.,substitution,.,.,.,.,.,.,protein_coding,.,.,.,.,.,CAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGGG...,3234-3286,.,.,.,C9JXX7_HUMAN,.,.,YES,.,"ITGA6,coding_sequence_variant,,ENST00000416789...",.,.,.,.,.,.,MODIFIER,3234-?,NONE,ITA6_HUMAN,.,.,Transcript,.,.,PASS,ENSP00000386896,.,VARSCANI*|PINDEL,CCDS46451.1,25/25,.,.,25/25,.,.
332608,ORM2,0,.,GRCh37,9,117085694,117092465,+,"splice_acceptor_variant,splice_donor_variant,c...",Splice_Site,DEL,CCCCCTGCCTCCAAACACAGAAGCCTCACTGCAGAGTCCTTCACGG...,CCCCCTGCCTCCAAACACAGAAGCCTCACTGCAGAGTCCTTCACGG...,-,novel,.,TCGA-G4-6588-01,TCGA-G4-6588-10,CCCCCTGCCTCCAAACACAGAAGCCTCACTGCAGAGTCCTTCACGG...,CCCCCTGCCTCCAAACACAGAAGCCTCACTGCAGAGTCCTTCACGG...,.,.,.,.,.,.,.,.,.,.,.,.,.,50,16,66,0,NaN,NaN,NaN,ENST00000259396,NM_000607.2,NaN,NaN,0.0,3,.,.,UPI0000052DC9,66,ENST00000431067,GAGGCACCCCCTGCCTCCAAACACAGAAGCCTCACTGCAGAGTCCT...,.,ENSG00000228278,8499,PRIMARY,.,66,.,HGNC,.,ORM2,.,deletion,.,.,.,.,.,.,protein_coding,.,.,.,.,.,-,.,.,.,5-Jan,.,.,.,YES,.,"ORM2,splice_donor_variant,,ENST00000431067,;OR...",.,.,.,.,.,.,HIGH,.,"BUFFER|p.S48S|c.144G>A|3,BUFFER|p.R86P|c.257G>...",A1AG2_HUMAN,.,.,Transcript,.,.,PASS,ENSP00000394936,.,INDELOCATOR*|VARSCANI*|PINDEL,CCDS6804.1,6-Jan,.,.,6-Jan,.,.
332609,CLCNKB,0,.,GRCh37,1,16362868,16386126,+,"splice_acceptor_variant,splice_donor_variant,c...",Splice_Site,DEL,GGGGGGCATGGGTGGGGACGGCCTCAGTGCCTGATGGAGCTGCTCC...,GGGGGGCATGGGTGGGGACGGCCTCAGTGCCTGATGGAGCTGCTCC...,-,novel,.,TCGA-G4-6628-01,TCGA-G4-6628-10,GGGGGGCATGGGTGGGGACGGCCTCAGTGCCTGATGGAGCTGCTCC...,GGGGGGCATGGGTGGGGACGGCCTCAGTGCCTGATGGAGCTGCTCC...,.,.,.,.,.,.,.,.,.,.,.,.,.,82,11,96,0,NaN,NaN,NaN,ENST00000375662,NM_182623.2,NaN,NaN,0.0,2,.,.,UPI000040E261,96,ENST00000375679,AGCTCAGGGGGGCATGGGTGGGGACGGCCTCAGTGCCTGATGGAGC...,.,ENSG00000184908,2027,PRIMARY,.,93,.,HGNC,.,CLCNKB,.,deletion,.,.,.,.,.,.,protein_coding,.,.,.,.,.,-,.,.,.,1/19/19,.,.,.,YES,.,"CLCNKB,transcript_ablation,,ENST00000375667,;C...",.,.,.,.,.,.,HIGH,.,"BUFFER|p.V524I|c.1570G>A|3,BUFFER|p.P683L|c.20...",CLCKB_HUMAN,.,.,Transcript,.,.,PASS,ENSP00000364831,.,VARSCANI*|PINDEL,CCDS168.1,1/20/20,.,.,1/20/20,.,.

In [62]:
dataMutation_TCGA = dataMutation_TCGA[['Tumor_Sample_Barcode', 'Hugo_Symbol', 'Chromosome', 'Start_Position', 'End_Position', 'Strand', 'Variant_Classification', 'Variant_Type', 'Reference_Allele', 'Tumor_Seq_Allele1', 'Tumor_Seq_Allele2', 'HGVSc', 'HGVSp_Short', 'Protein_position', 'Transcript_ID']]

In [63]:
uniqueHugo = dataMutation_TCGA['Hugo_Symbol'].nunique()
uniqueTranscript = dataMutation_TCGA['Transcript_ID'].nunique()
uniqueHugo, uniqueTranscript

(19765, 20582)

In [64]:
unknownHugo = (dataMutation_TCGA['Hugo_Symbol'] == 'Unknown').sum()
emptyHugo = (dataMutation_TCGA['Hugo_Symbol'] == '').sum()
naHugo = pd.isna(dataMutation_TCGA['Hugo_Symbol']).sum()

unknownTranscript = (dataMutation_TCGA['Transcript_ID'] == 'Unknown').sum()
emptyTranscript = (dataMutation_TCGA['Transcript_ID'] == '').sum()
naTranscript = pd.isna(dataMutation_TCGA['Transcript_ID']).sum()

unknownHugoUnknownTranscript = (dataMutation_TCGA[dataMutation_TCGA['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == 'Unknown').sum()
emptyHugoUnknownTranscript = (dataMutation_TCGA[dataMutation_TCGA['Hugo_Symbol'] == '']['Transcript_ID'] == 'Unknown').sum()
naHugoUnknownTranscript = (dataMutation_TCGA[dataMutation_TCGA['Hugo_Symbol'].isna()]['Transcript_ID'] == 'Unknown').sum()
unknownHugoEmptyTranscript = (dataMutation_TCGA[dataMutation_TCGA['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()
emptyHugoEmptyTranscript = (dataMutation_TCGA[dataMutation_TCGA['Hugo_Symbol'] == '']['Transcript_ID'] == '').sum()
naHugoEmptyTranscript = (dataMutation_TCGA[dataMutation_TCGA['Hugo_Symbol'].isna()]['Transcript_ID'] == '').sum()
unknownHugoNaTranscript = (pd.isna(dataMutation_TCGA[dataMutation_TCGA['Hugo_Symbol'] == 'Unknown']['Transcript_ID'])).sum()
emptyHugoNaTranscript = (pd.isna(dataMutation_TCGA[dataMutation_TCGA['Hugo_Symbol'] == '']['Transcript_ID'])).sum()
naHugoNaTranscript = (pd.isna(dataMutation_TCGA[dataMutation_TCGA['Hugo_Symbol'].isna()]['Transcript_ID'])).sum()

unknownHugoEmptyTranscript = (dataMutation_TCGA[dataMutation_TCGA['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()

(unknownHugo, emptyHugo, naHugo), (unknownTranscript, emptyTranscript, naTranscript), ((unknownHugoUnknownTranscript, emptyHugoUnknownTranscript, naHugoUnknownTranscript), (unknownHugoEmptyTranscript, emptyHugoEmptyTranscript, naHugoEmptyTranscript), (unknownHugoNaTranscript, emptyHugoNaTranscript, naHugoNaTranscript))

((0, 0, 0), (0, 0, 0), ((0, 0, 0), (0, 0, 0), (0, 0, 0)))

In [65]:
# Get unique transcript ids
uniqueTranscriptIds = dataMutation_TCGA['Transcript_ID'].unique()

# Create a dictionary mapping from Transcript_ID to Hugo_Symbol
transcriptIds_HugoSymbol_mapping = {id: ensembl.gene_name_of_transcript_id(id) for id in uniqueTranscriptIds}

transcriptIds_HugoSymbol_mapping

{'ENST00000263150': 'WDR37',
 'ENST00000378372': 'HSPA14',
 'ENST00000260283': 'ARHGAP20',
 'ENST00000392708': 'STT3A',
 'ENST00000256737': 'ANO3',
 'ENST00000263776': 'ACCS',
 'ENST00000308064': 'CHST1',
 'ENST00000378623': 'LRP4',
 'ENST00000395079': 'OR10W1',
 'ENST00000358353': 'CDHR5',
 'ENST00000261637': 'UTP20',
 'ENST00000355819': 'CLEC9A',
 'ENST00000550722': 'HECTD4',
 'ENST00000261655': 'RIMBP2',
 'ENST00000359062': 'PDE3A',
 'ENST00000298892': 'CAPRIN2',
 'ENST00000382545': 'KCNA1',
 'ENST00000360299': 'RAB5B',
 'ENST00000286494': 'ARHGEF25',
 'ENST00000454289': 'TSFM',
 'ENST00000558850': 'ZNF839',
 'ENST00000539517': 'NOVA1',
 'ENST00000280979': 'AKAP6',
 'ENST00000395834': 'CDKL1',
 'ENST00000395125': 'DAAM1',
 'ENST00000430451': 'SYT16',
 'ENST00000163416': 'GOLGA5',
 'ENST00000249749': 'DLL4',
 'ENST00000301732': 'ABCA3',
 'ENST00000380148': 'TP53TG3D',
 'ENST00000251166': 'CORO7',
 'ENST00000300589': 'NOD2',
 'ENST00000379906': 'SLC6A2',
 'ENST00000290881': 'KIAA0895L',
 'ENST00000302628': 'CALB2',
 'ENST00000317447': 'ACSF3',
 'ENST00000321105': 'TOP3A',
 'ENST00000246646': 'KRT38',
 'ENST00000258960': 'NMT1',
 'ENST00000322765': 'PLCD3',
 'ENST00000336915': 'SKAP1',
 'ENST00000290866': 'ACE',
 'ENST00000314256': 'KIAA0195',
 'ENST00000586717': 'FBF1',
 'ENST00000269305': 'TP53',
 'ENST00000526991': 'CHMP1B',
 'ENST00000324750': 'MC5R',
 'ENST00000284202': 'IMPACT',
 'ENST00000400256': 'COLEC12',
 'ENST00000537592': 'SALL3',
 'ENST00000251472': 'MAST1',
 'ENST00000355537': 'ZNF536',
 'ENST00000221856': 'FSD1',
 'ENST00000262887': 'XRCC1',
 'ENST00000263257': 'NOVA2',
 'ENST00000359920': 'ARHGEF18',
 'ENST00000256637': 'SORT1',
 'ENST00000336338': 'SPAG17',
 'ENST00000368099': 'CCDC19',
 'ENST00000355305': 'DNM3',
 'ENST00000367460': 'RGS18',
 'ENST00000367342': 'C1orf106',
 'ENST00000367137': 'SLC41A1',
 'ENST00000366757': 'PRSS38',
 'ENST00000319653': 'FMN2',
 'ENST00000324856': 'ARID1A',
 'ENST00000207457': 'TEKT2',
 'ENST00000257181': 'PRPF38A',
 'ENST00000326637': 'TNNI3K',
 'ENST00000370757': 'PTGFR',
 'ENST00000370717': 'LPHN2',
 'ENST00000381458': 'TGM3',
 'ENST00000375494': 'BPIFB3',
 'ENST00000371998': 'NCOA3',
 'ENST00000371652': 'TMEM189',
 'ENST00000252999': 'LAMA5',
 'ENST00000359125': 'KCNQ2',
 'ENST00000284987': 'ADAMTS5',
 'ENST00000338306': 'CCDC157',
 'ENST00000591111': 'TTN',
 'ENST00000428443': 'SESTD1',
 'ENST00000236957': 'EEF1B2',
 'ENST00000439458': 'UNC80',
 'ENST00000347842': 'ASIC4',
 'ENST00000283943': 'TRIP12',
 'ENST00000295550': 'COL6A3',
 'ENST00000406316': 'NRXN1',
 'ENST00000256452': 'IL5RA',
 'ENST00000397491': 'CHL1',
 'ENST00000265564': 'EXOSC7',
 'ENST00000281708': 'FBXW7',
 'ENST00000264431': 'RAPGEF2',
 'ENST00000338566': 'NPY5R',
 'ENST00000280605': 'TKTL2',
 'ENST00000282924': 'JAKMIP1',
 'ENST00000310581': 'TERT',
 'ENST00000261366': 'LMNB1',
 'ENST00000395003': 'JADE2',
 'ENST00000532602': 'PCDHA9',
 'ENST00000307360': 'PCDHA10',
 'ENST00000239446': 'PCDHB10',
 'ENST00000519479': 'PCDHGB4',
 'ENST00000377365': 'FAM196B',
 'ENST00000335815': 'ZNF354A',
 'ENST00000389805': 'SQSTM1',
 'ENST00000382142': 'MTMR12',
 'ENST00000399503': 'MAP3K1',
 'ENST00000441448': 'RPF2',
 'ENST00000275233': 'SHPRH',
 'ENST00000367339': 'ULBP3',
 'ENST00000367255': 'SYNE1',
 'ENST00000274867': 'DAAM2',
 'ENST00000257749': 'BACH2',
 'ENST00000297431': 'ORC5',
 'ENST00000321063': 'PLXNA4',
 'ENST00000275815': 'EPHA1',
 'ENST00000251527': 'ESYT2',
 'ENST00000424383': 'ELFN1',
 'ENST00000408931': 'TBX20',
 'ENST00000199447': 'NME8',
 'ENST00000404826': 'SDK1',
 'ENST00000223324': 'MRPL32',
 'ENST00000396904': 'RBAK-RBAKDN',
 'ENST00000334955': 'RSBN1L',
 'ENST00000356239': 'AKAP9',
 'ENST00000359863': 'TRRAP',
 'ENST00000388996': 'KCNQ3',
 'ENST00000438773': 'TRAPPC9',
 'ENST00000379010': 'REXO1L1P',
 'ENST00000319675': 'DCAF4L2',
 'ENST00000374902': 'TEX10',
 'ENST00000259324': 'LRRC8A',
 'ENST00000303407': 'BRD3',
 'ENST00000298532': 'SNAPC4',
 'ENST00000308675': 'LINGO2',
 'ENST00000259569': 'RANBP6',
 'ENST00000376238': 'SLC28A3',
 'ENST00000372068': 'TMEM164',
 'ENST00000371106': 'XPNPEP2',
 'ENST00000370526': 'LDOC1',
 'ENST00000312600': 'PABPC5',
 'ENST00000304613': 'KNDC1',
 'ENST00000377071': 'KDM2B',
 'ENST00000483544': 'LINC00477',
 'ENST00000428670': 'ATP2B1',
 'ENST00000546474': 'BRF1',
 'ENST00000261609': 'HERC2',
 'ENST00000389286': 'PRTG',
 'ENST00000330684': 'GRIN2A',
 'ENST00000337929': 'IL21R',
 'ENST00000268296': 'ITGAX',
 'ENST00000393119': 'MKS1',
 'ENST00000315576': 'EMR2',
 'ENST00000379803': 'SIN3B',
 'ENST00000221891': 'APLP1',
 'ENST00000360614': 'LONP1',
 'ENST00000374221': 'UBXN11',
 'ENST00000373480': 'KIAA1522',
 'ENST00000421030': 'MROH7',
 'ENST00000252998': 'RBBP8NL',
 'ENST00000217182': 'EEF1A2',
 'ENST00000245663': 'ZBTB46',
 'ENST00000215739': 'LZTR1',
 'ENST00000215743': 'MMP11',
 'ENST00000337859': 'ZC3H15',
 'ENST00000328333': 'COL7A1',
 'ENST00000461745': 'ROBO2',
 'ENST00000256084': 'SPINK5',
 'ENST00000355472': 'GRK6',
 'ENST00000300179': 'NYAP1',
 'ENST00000392957': 'EPHB6',
 'ENST00000399583': 'RADIL',
 'ENST00000354212': 'MAGI2',
 'ENST00000220888': 'TRPS1',
 'ENST00000395297': 'FAM135B',
 'ENST00000356083': 'COL27A1',
 'ENST00000315480': 'USP20',
 'ENST00000378909': 'ARID3C',
 'ENST00000245838': 'THOC2',
 'ENST00000377604': 'RBM10',
 'ENST00000373358': 'PBDC1',
 'ENST00000373034': 'PCDH19',
 'ENST00000324109': 'DNMBP',
 'ENST00000369983': 'GBF1',
 'ENST00000369701': 'SORCS3',
 'ENST00000321505': 'KIAA1549L',
 'ENST00000279791': 'OR5M9',
 'ENST00000278407': 'SERPING1',
 'ENST00000532620': 'TSGA10IP',
 'ENST00000280258': 'PRSS23',
 'ENST00000320585': 'CHORDC1',
 'ENST00000279839': 'CWC15',
 'ENST00000070846': 'PKP2',
 'ENST00000266594': 'ANP32D',
 'ENST00000330722': 'KRT6A',
 'ENST00000549446': 'KCNC2',
 'ENST00000328827': 'PAWR',
 'ENST00000267339': 'ANKRD10',
 'ENST00000381527': 'CDK8',
 'ENST00000360631': 'DCLK1',
 'ENST00000250498': 'DAD1',
 'ENST00000541158': 'TSHR',
 'ENST00000329082': 'RGMA',
 'ENST00000396368': 'KIAA0430',
 'ENST00000219255': 'PARD6A',
 'ENST00000268802': 'NOB1',
 'ENST00000262144': 'WDR59',
 'ENST00000564536': 'RP11-303E16.8',
 'ENST00000268695': 'GALNS',
 'ENST00000409168': 'SHISA6',
 'ENST00000225916': 'KAT2A',
 'ENST00000342988': 'SMAD4',
 'ENST00000342784': 'SYDE1',
 'ENST00000355868': 'WDR88',
 'ENST00000222305': 'USF2',
 'ENST00000264554': 'SHC2',
 'ENST00000391876': 'FUT2',
 'ENST00000309877': 'IRF3',
 'ENST00000385103': 'MIR517C',
 'ENST00000270460': 'EPN1',
 'ENST00000390649': 'NLRP5',
 'ENST00000597188': 'ADAMTS10',
 'ENST00000369769': 'KCNA3',
 'ENST00000308647': 'ATAD3B',
 'ENST00000263525': 'TNR',
 'ENST00000367400': 'CRB1',
 'ENST00000366955': 'CENPF',
 'ENST00000323699': 'DEGS1',
 'ENST00000422127': 'OBSCN',
 'ENST00000262873': 'MYH7B',
 'ENST00000237536': 'SOGA1',
 'ENST00000262865': 'BPI',
 'ENST00000299824': 'PPP1R16B',
 'ENST00000372262': 'CDH22',
 'ENST00000359271': 'SLC2A10',
 'ENST00000475243': 'VAPB',
 'ENST00000291526': 'TFF2',
 'ENST00000354992': 'LARGE',
 'ENST00000337304': 'ATF4',
 'ENST00000328823': 'WBP2NL',
 'ENST00000409886': 'RGPD3',
 'ENST00000263331': 'POLR1B',
 'ENST00000389484': 'LRP1B',
 'ENST00000409855': 'SCN7A',
 'ENST00000359846': 'NT5C1B',
 'ENST00000404537': 'OBSL1',
 'ENST00000272907': 'NYAP2',
 'ENST00000392039': 'GPR55',
 'ENST00000311075': 'MUC13',
 'ENST00000273083': 'GRIP2',
 'ENST00000334444': 'ABCC5',
 'ENST00000450053': 'NBEAL2',
 'ENST00000409535': 'RAD54L2',
 'ENST00000273283': 'ITIH1',
 'ENST00000389617': 'GXYLT2',
 'ENST00000264193': 'CPOX',
 'ENST00000394820': 'NFKB1',
 'ENST00000438793': 'PAM',
 'ENST00000257430': 'APC',
 'ENST00000265104': 'DNAH5',
 'ENST00000504120': 'PCDHA1',
 'ENST00000283426': 'PLEKHG4B',
 'ENST00000356031': 'SPEF2',
 'ENST00000311381': 'C6orf203',
 'ENST00000360359': 'ANKS1A',
 'ENST00000373866': 'ARMC12',
 'ENST00000355574': 'SLC26A8',
 'ENST00000335870': 'ZNF212',
 'ENST00000312371': 'AMZ1',
 'ENST00000404991': 'PAPOLB',
 'ENST00000407838': 'VSTM2A',
 'ENST00000252037': 'FKBP6',
 'ENST00000286355': 'ADCY8',
 'ENST00000525985': 'EPPK1',
 'ENST00000276461': 'ERLIN2',
 'ENST00000487273': 'ADAM9',
 'ENST00000539294': 'YTHDF3',
 'ENST00000302190': 'SDC2',
 'ENST00000372731': 'SPTAN1',
 'ENST00000488444': 'KCNT1',
 'ENST00000376207': 'FOXP3',
 'ENST00000252336': 'STARD8',
 'ENST00000373200': 'POU3F4',
 'ENST00000369209': 'HSPA12A',
 'ENST00000257359': 'ADAMTS8',
 'ENST00000335987': 'OVOL1',
 'ENST00000312562': 'FOSL1',
 'ENST00000311330': 'CD248',
 'ENST00000551590': 'TCTN1',
 'ENST00000397558': 'CCDC64',
 'ENST00000399788': 'KDM5A',
 'ENST00000542859': 'FRY',
 'ENST00000397795': 'TRPM1',
 'ENST00000220514': 'OIP5',
 'ENST00000388942': 'C15orf27',
 'ENST00000399410': 'ABCC1',
 'ENST00000440851': 'CENPT',
 'ENST00000353379': 'CDK10',
 'ENST00000226247': 'FOXN1',
 'ENST00000306749': 'FASN',
 'ENST00000335255': 'FOXK2',
 'ENST00000501448': 'AC005329.7',
 'ENST00000245934': 'SYMPK',
 'ENST00000263266': 'FAM83E',
 'ENST00000358432': 'EPHA2',
 'ENST00000272117': 'ITPKB',
 'ENST00000378466': 'PANK4',
 'ENST00000370571': 'COL24A1',
 'ENST00000201979': 'REM1',
 'ENST00000373187': 'PTPRT',
 'ENST00000045083': 'FAM65C',
 'ENST00000361866': 'COL6A1',
 'ENST00000272321': 'WDPCP',
 'ENST00000264448': 'ALMS1',
 'ENST00000357750': 'HYAL2',
 'ENST00000399132': 'COL25A1',
 'ENST00000296739': 'SPZ1',
 'ENST00000338891': 'FAM184A',
 'ENST00000241069': 'ACHE',
 'ENST00000303921': 'GPR37',
 'ENST00000334705': 'FAM91A1',
 'ENST00000388913': 'FAM83H',
 'ENST00000322810': 'PLEC',
 'ENST00000221166': 'NEFM',
 'ENST00000218316': 'GPR50',
 'ENST00000340888': 'PNCK',
 'ENST00000263246': 'PACSIN2',
 'ENST00000329962': 'B4GALNT4',
 'ENST00000306904': 'RBMXL2',
 'ENST00000300648': 'GCN1L1',
 'ENST00000262375': 'DNAJA3',
 'ENST00000308251': 'KCNG4',
 'ENST00000340748': 'DNMT1',
 'ENST00000293771': 'ZNF653',
 'ENST00000233596': 'REEP6',
 'ENST00000361574': 'R3HDM4',
 'ENST00000375985': 'MYLK2',
 'ENST00000302326': 'MN1',
 'ENST00000408978': 'MYO3B',
 'ENST00000264771': 'TMEM175',
 'ENST00000529859': 'PCDHA5',
 'ENST00000348628': 'CAMK2A',
 'ENST00000329542': 'UNC5A',
 'ENST00000358571': 'PFN3',
 'ENST00000306085': 'TRIM56',
 'ENST00000003100': 'CYP51A1',
 'ENST00000327381': 'XKR4',
 'ENST00000371974': 'SURF1',
 'ENST00000372588': 'ESX1',
 'ENST00000342995': 'CXorf67',
 'ENST00000369839': 'TAF5',
 'ENST00000438700': 'PTCHD3',
 'ENST00000280886': 'DIP2C',
 'ENST00000380872': 'AKR1C1',
 'ENST00000399262': 'JMJD1C',
 'ENST00000334801': 'BCL9L',
 'ENST00000300632': 'IGF2',
 'ENST00000263401': 'COMMD9',
 'ENST00000396950': 'OR51E2',
 'ENST00000309106': 'MRGPRD',
 'ENST00000454689': 'OVCH2',
 'ENST00000280758': 'BTBD11',
 'ENST00000419234': 'BRAP',
 'ENST00000242592': 'ACADS',
 'ENST00000402868': 'SETD8',
 'ENST00000299308': 'TMEM132B',
 'ENST00000359864': 'TEAD4',
 'ENST00000331366': 'CPNE8',
 'ENST00000454784': 'MUC19',
 'ENST00000311268': 'GPR162',
 'ENST00000196169': 'TDRD3',
 'ENST00000216455': 'PSMA3',
 'ENST00000298351': 'TMEM63C',
 'ENST00000348070': 'PCSK6',
 'ENST00000335625': 'GABRA5',
 'ENST00000354181': 'SLC12A6',
 'ENST00000388901': 'COPS2',
 'ENST00000323940': 'STRA6',
 'ENST00000568449': 'EME2',
 'ENST00000356183': 'GTF3C1',
 'ENST00000251020': 'SALL1',
 'ENST00000339953': 'CLEC18B',
 'ENST00000570137': 'CDYL2',
 'ENST00000343629': 'TLDC1',
 'ENST00000253458': 'GSE1',
 'ENST00000301039': 'PROCA1',
 'ENST00000225972': 'LRRC59',
 'ENST00000433363': 'SLC13A5',
 'ENST00000284425': 'ABCA6',
 'ENST00000269081': 'ABCA10',
 'ENST00000446526': 'PRPSAP1',
 'ENST00000582970': 'RNF213',
 'ENST00000300976': 'KLHL26',
 'ENST00000301244': 'SPINT2',
 'ENST00000311308': 'TTC9B',
 'ENST00000222330': 'GSK3A',
 'ENST00000599921': 'PLA2G4C',
 'ENST00000270642': 'IGLON5',
 'ENST00000600412': 'ZNF665',
 'ENST00000342929': 'NLRP13',
 'ENST00000343320': 'CHIA',
 'ENST00000326233': 'LCE1D',
 'ENST00000338920': 'PRRC2C',
 'ENST00000367618': 'AXDND1',
 'ENST00000271588': 'HMCN1',
 'ENST00000367429': 'CFH',
 'ENST00000270218': 'IL19',
 'ENST00000366672': 'GALNT2',
 'ENST00000366574': 'RYR2',
 'ENST00000306687': 'OR2M4',
 'ENST00000439621': 'RP11-334A14.8',
 'ENST00000333082': 'PSMF1',
 'ENST00000278886': 'NINL',
 'ENST00000374273': 'SPAG4',
 'ENST00000356455': 'UBE2C',
 'ENST00000302342': 'ZNF217',
 'ENST00000331758': 'SS18L1',
 'ENST00000359759': 'COL18A1',
 'ENST00000300527': 'COL6A2',
 'ENST00000402027': 'POM121L1P',
 'ENST00000248996': 'GNAZ',
 'ENST00000453153': 'FASTKD1',
 'ENST00000249501': 'HOXD10',
 'ENST00000319170': 'RAPH1',
 'ENST00000331683': 'SPAG16',
 'ENST00000171887': 'TNS1',
 'ENST00000324695': 'TRPM8',
 'ENST00000327757': 'PLB1',
 'ENST00000421745': 'BIRC6',
 'ENST00000403751': 'GTF2A1L',
 'ENST00000318357': 'ANKRD23',
 'ENST00000290868': 'UROC1',
 'ENST00000296271': 'RHO',
 'ENST00000476941': 'TRPC1',
 'ENST00000360060': 'PLOD2',
 'ENST00000472924': 'KRT8P12',
 'ENST00000336824': 'FNDC3B',
 'ENST00000306376': 'ETV5',
 'ENST00000395052': 'GRM2',
 'ENST00000315423': 'TNIP2',
 'ENST00000263923': 'KDR',
 'ENST00000398631': 'PCDHA12',
 'ENST00000231134': 'PCDHB5',
 'ENST00000231137': 'PCDHB7',
 'ENST00000252087': 'PCDHGC5',
 'ENST00000435817': 'FCHSD1',
 'ENST00000411494': 'KCNIP1',
 'ENST00000425232': 'C5orf42',
 'ENST00000399438': 'TRAPPC13',
 'ENST00000264914': 'ARSB',
 'ENST00000405460': 'GPR98',
 'ENST00000274432': 'SPATA9',
 'ENST00000379982': 'RHOBTB3',
 'ENST00000368662': 'TUBE1',
 'ENST00000372445': 'TJAP1',
 'ENST00000302103': 'FUT9',
 'ENST00000205386': 'LAMB4',
 'ENST00000265854': 'MAD1L1',
 'ENST00000324972': 'DYNC1I1',
 'ENST00000297405': 'CSMD3',
 'ENST00000323289': 'BAI1',
 'ENST00000297423': 'SPIDR',
 'ENST00000356297': 'PXDNL',
 'ENST00000331251': 'NPBWR1',
 'ENST00000262215': 'ARFGEF1',
 'ENST00000276594': 'PRDM14',
 'ENST00000265814': 'RUNX1T1',
 'ENST00000371817': 'COL5A1',
 'ENST00000508529': 'TUBBP5',
 'ENST00000325303': 'CDK20',
 'ENST00000375854': 'NXNL2',
 'ENST00000358157': 'S1PR3',
 'ENST00000356444': 'SEMA4D',
 'ENST00000218032': 'TLR8',
 'ENST00000304543': 'ZFX',
 'ENST00000524993': 'TMPRSS13',
 'ENST00000527548': 'FAU',
 'ENST00000335154': 'FMNL3',
 'ENST00000257974': 'KRT82',
 'ENST00000341267': 'DLK1',
 'ENST00000268058': 'PML',
 'ENST00000344626': 'SMARCA4',
 'ENST00000170168': 'REXO1',
 'ENST00000270301': 'WDR62',
 'ENST00000318083': 'MAMSTR',
 'ENST00000282326': 'ZSCAN1',
 'ENST00000343090': 'UBE4B',
 'ENST00000368680': 'NPR1',
 'ENST00000367556': 'RGS8',
 'ENST00000379453': 'ADRA1D',
 'ENST00000360469': 'CDH4',
 'ENST00000336156': 'KIAA0930',
 'ENST00000342894': 'RIBC2',
 'ENST00000234142': 'GREB1',
 'ENST00000409878': 'SLC23A3',
 'ENST00000273353': 'MYH15',
 'ENST00000336307': 'HYAL3',
 'ENST00000399429': 'COL28A1',
 'ENST00000401592': 'SUN1',
 'ENST00000373880': 'PHYHIPL',
 'ENST00000372919': 'ANXA7',
 'ENST00000372027': 'MMRN2',
 'ENST00000302797': 'MRGPRX1',
 'ENST00000311659': 'UBQLN3',
 'ENST00000314612': 'OR4P4',
 'ENST00000333976': 'OR5D18',
 'ENST00000312253': 'OR5R1',
 'ENST00000300127': 'OR4D6',
 'ENST00000329328': 'OR4D9',
 'ENST00000294168': 'TAF6L',
 'ENST00000393324': 'ME3',
 'ENST00000321867': 'ULK1',
 'ENST00000261195': 'GYS2',
 'ENST00000300131': 'NAB2',
 'ENST00000376335': 'ZIC2',
 'ENST00000375774': 'ING1',
 'ENST00000361283': 'CHAMP1',
 'ENST00000515384': 'AMER2',
 'ENST00000379881': 'SOHLH2',
 'ENST00000409874': 'TDRD9',
 'ENST00000390551': 'IGHG3',
 'ENST00000299088': 'C14orf93',
 'ENST00000360586': 'WDHD1',
 'ENST00000554719': 'NRXN3',
 'ENST00000393151': 'UNC79',
 'ENST00000300177': 'GREM1',
 'ENST00000251076': 'DMXL2',
 'ENST00000343738': 'PKD1P6',
 'ENST00000389398': 'VWA3A',
 'ENST00000301740': 'SRRM2',
 'ENST00000262518': 'SRCAP',
 'ENST00000394979': 'ZNF646',
 'ENST00000359128': 'NLRC3',
 'ENST00000306875': 'COG8',
 'ENST00000323786': 'COG4',
 'ENST00000268489': 'ZFHX3',
 'ENST00000225387': 'CRYBA1',
 'ENST00000361566': 'KRT19',
 'ENST00000246914': 'WNK4',
 'ENST00000574590': 'KANSL1',
 'ENST00000381365': 'C17orf107',
 'ENST00000448276': 'SMARCD2',
 'ENST00000243457': 'KCNJ2',
 'ENST00000397545': 'CCDC40',
 'ENST00000426216': 'ATP9B',
 'ENST00000590320': 'S1PR2',
 'ENST00000343769': 'ZNF93',
 'ENST00000392213': 'MAG',
 'ENST00000221347': 'FCGBP',
 'ENST00000340963': 'ZNF780A',
 'ENST00000324001': 'PRX',
 'ENST00000246792': 'RRAS',
 'ENST00000355326': 'ZNF525',
 'ENST00000324602': 'LILRB1',
 'ENST00000456448': 'OR7E24',
 'ENST00000314485': 'IGSF8',
 'ENST00000368013': 'ARHGAP30',
 'ENST00000256785': 'CFHR5',
 'ENST00000373129': 'STK40',
 'ENST00000373091': 'GRIK3',
 'ENST00000356545': 'RSPO1',
 'ENST00000372207': 'BEST4',
 'ENST00000372980': 'JPH2',
 'ENST00000201031': 'TFAP2C',
 'ENST00000319441': 'PCK1',
 'ENST00000371030': 'ZNF831',
 'ENST00000414042': 'RP11-157P1.4',
 'ENST00000400546': 'NCAM2',
 'ENST00000381815': 'GART',
 'ENST00000260952': 'ASNSD1',
 'ENST00000233893': 'HSPE1',
 'ENST00000295049': 'RFTN2',
 'ENST00000406610': 'PARD3B',
 'ENST00000360351': 'MAP2',
 'ENST00000359671': 'FN1',
 'ENST00000393525': 'ANKRD36BP2',
 'ENST00000436022': 'EFCC1',
 'ENST00000324093': 'PLXND1',
 'ENST00000428331': 'ATP2C1',
 'ENST00000286349': 'TRIM42',
 'ENST00000231706': 'SLC7A14',
 'ENST00000311806': 'OXSR1',
 'ENST00000402939': 'MAGI1',
 'ENST00000265174': 'PAPSS1',
 'ENST00000302053': 'FGA',
 'ENST00000306193': 'CBR4',
 'ENST00000264229': 'KIAA1211',
 'ENST00000314595': 'POLR2B',
 'ENST00000381210': 'TECRL',
 'ENST00000379807': 'SLCO6A1',
 'ENST00000338882': 'METTL24',
 'ENST00000379446': 'NEDD9',
 'ENST00000448612': 'WDR27',
 'ENST00000306151': 'MUC17',
 'ENST00000340112': 'RNF133',
 'ENST00000285928': 'LRGUK',
 'ENST00000354042': 'SLC13A4',
 'ENST00000419765': 'SVOPL',
 'ENST00000404938': 'ABCB5',
 'ENST00000409508': 'DNAH11',
 'ENST00000396946': 'CARD11',
 'ENST00000223029': 'AIMP2',
 'ENST00000248564': 'GNG11',
 'ENST00000262113': 'MYOM2',
 'ENST00000301905': 'PBK',
 'ENST00000285393': 'ATP6V0D2',
 'ENST00000374879': 'TMEFF1',
 'ENST00000481272': 'FSD1L',
 'ENST00000408936': 'DAB2IP',
 'ENST00000302586': 'CCBL1',
 'ENST00000380055': 'LRRC19',
 'ENST00000377966': 'RECK',
 'ENST00000375544': 'ASPN',
 'ENST00000309720': 'TMEM255A',
 'ENST00000424805': 'PNMA3',
 'ENST00000358047': 'FAM47C',
 'ENST00000373316': 'PGK1',
 'ENST00000369849': 'INA',
 'ENST00000355995': 'TCF7L2',
 'ENST00000351270': 'HABP2',
 'ENST00000359988': 'NRAP',
 'ENST00000537242': 'PNLIPRP2',
 'ENST00000368654': 'MKI67',
 'ENST00000252936': 'TUBGCP2',
 'ENST00000298943': 'C1QL3',
 'ENST00000605216': 'ZSWIM8',
 'ENST00000371939': 'LIPJ',
 'ENST00000299333': 'SCN3B',
 'ENST00000319338': 'IGSF22',
 'ENST00000328224': 'KCNA4',
 'ENST00000360374': 'OR5B21',
 'ENST00000301765': 'VPS37C',
 'ENST00000448903': 'AP2A2',
 'ENST00000261740': 'TRPV4',
 'ENST00000389561': 'EP400',
 'ENST00000256958': 'SLCO1B1',
 'ENST00000256078': 'KRAS',
 'ENST00000432328': 'PCED1B',
 'ENST00000549396': 'PPFIA2',
 'ENST00000282397': 'FLT1',
 'ENST00000325089': 'SLITRK5',
 'ENST00000334743': 'PPP2R5C',
 'ENST00000390604': 'IGHV3-16',
 'ENST00000267426': 'FITM1',
 'ENST00000399232': 'MDGA2',
 'ENST00000282146': 'KCNK13',
 'ENST00000329468': 'NPAP1',
 'ENST00000389232': 'RYR3',
 'ENST00000316623': 'FBN1',
 'ENST00000261875': 'PTPLAD1',
 'ENST00000348261': 'CACNA1H',
 'ENST00000389176': 'CCDC154',
 'ENST00000262302': 'NUBP2',
 'ENST00000302445': 'KARS',
 'ENST00000320241': 'FOXL1',
 'ENST00000301030': 'ANKRD11',
 'ENST00000341712': 'MPRIP',
 'ENST00000311269': 'MARCH10',
 'ENST00000359995': 'SRSF2',
 'ENST00000310045': 'DSEL',
 'ENST00000299687': 'ZNF407',
 'ENST00000244336': 'CEACAM8',
 'ENST00000340093': 'PLAUR',
 'ENST00000301286': 'PLIN4',
 'ENST00000328771': 'DHX34',
 'ENST00000248244': 'TICAM1',
 'ENST00000323446': 'CPT1C',
 'ENST00000338372': 'VSTM1',
 'ENST00000391713': 'ZSCAN5A',
 'ENST00000346664': 'FCER2',
 'ENST00000369771': 'KCNA10',
 'ENST00000234739': 'BCL9',
 'ENST00000369047': 'ECM1',
 'ENST00000367330': 'TMEM9',
 'ENST00000367262': 'RABIF',
 'ENST00000367147': 'MFSD4',
 'ENST00000366582': 'HEATR1',
 'ENST00000361632': 'CSF3R',
 'ENST00000372470': 'MPL',

In [66]:
# add Ensembl Hugo_Symbol
dataMutation_TCGA_cleaned = dataMutation_TCGA.copy()
dataMutation_TCGA_cleaned.rename(columns={'Hugo_Symbol': 'original_Hugo_Symbol'}, inplace=True)
dataMutation_TCGA_cleaned.insert(1, 'Hugo_Symbol', '')
dataMutation_TCGA_cleaned.loc[:,'Hugo_Symbol'] = dataMutation_TCGA_cleaned['Transcript_ID'].map(transcriptIds_HugoSymbol_mapping)

In [67]:
# show rows where Hugo_Symbol and original_Hugo_Symbol are different
dataMutation_TCGA_cleaned.loc[dataMutation_TCGA_cleaned['Hugo_Symbol'] != dataMutation_TCGA_cleaned['original_Hugo_Symbol'], ['Transcript_ID', 'Hugo_Symbol', 'original_Hugo_Symbol']]

          Transcript_ID    Hugo_Symbol original_Hugo_Symbol
234     ENST00000532620       TSGA10IP                SART1
253     ENST00000564536  RP11-303E16.8        RP11-303E16.5
355     ENST00000501448     AC005329.7               NDUFS7
402     ENST00000501448     AC005329.7               NDUFS7
543     ENST00000439621  RP11-334A14.8               SLC1A7
...                 ...            ...                  ...
332601  ENST00000226207           MYH1                 MYH2
332602  ENST00000313472          OR8H3                OR8H2
332605  ENST00000454971          GPR42                FFAR3
332608  ENST00000259396           ORM1                 ORM2
332609  ENST00000375662        FAM131C               CLCNKB

[3685 rows x 3 columns]

In [68]:
# add gene length
dataMutation_TCGA_cleaned['Gene_Length'] = dataMutation_TCGA_cleaned['Hugo_Symbol'].apply(lambda x: ensembl.genes_by_name(x)[0].length)

In [69]:
dataMutation_TCGA_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length
0,TCGA-AF-2687-01,WDR37,WDR37,10,1130478,1130478,+,Missense_Mutation,SNP,G,G,A,ENST00000263150.4:c.532G>A,p.D178N,178.0,ENST00000263150,82760
1,TCGA-AF-2687-01,HSPA14,HSPA14,10,14896137,14896137,+,Missense_Mutation,SNP,G,G,A,ENST00000378372.3:c.748G>A,p.D250N,250.0,ENST00000378372,33578
2,TCGA-AF-2687-01,ARHGAP20,ARHGAP20,11,110450666,110450666,+,Missense_Mutation,SNP,G,G,A,ENST00000260283.4:c.3004C>T,p.P1002S,1002.0,ENST00000260283,136147
3,TCGA-AF-2687-01,STT3A,STT3A,11,125478127,125478127,+,Missense_Mutation,SNP,G,G,A,ENST00000392708.4:c.904G>A,p.V302I,302.0,ENST00000392708,33504
4,TCGA-AF-2687-01,ANO3,ANO3,11,26620415,26620415,+,Missense_Mutation,SNP,G,G,A,ENST00000256737.3:c.1541G>A,p.R514H,514.0,ENST00000256737,474007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332605,TCGA-D5-6928-01,GPR42,FFAR3,19,35849879,35862348,+,Splice_Site,DEL,CCCCCTCAACCTGCTGGCCCTGGTGGTCTTCGTGGGCAAGCTGCAG...,CCCCCTCAACCTGCTGGCCCTGGTGGTCTTCGTGGGCAAGCTGCAG...,-,NaN,NaN,NaN,ENST00000454971,2025
332606,TCGA-F4-6461-01,ZNF799,ZNF799,19,12502563,12542338,+,Splice_Site,DEL,TCTCATGCATATGTAATAAACTGGGCCAAAAAAACGCTTTCCCACA...,TCTCATGCATATGTAATAAACTGGGCCAAAAAAACGCTTTCCCACA...,-,NaN,NaN,NaN,ENST00000430385,11256
332607,TCGA-G4-6588-01,ITGA6,ITGA6,2,173368938,173368990,+,3'UTR,DEL,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,-,NaN,NaN,1117.0,ENST00000442250,79100
332608,TCGA-G4-6588-01,ORM1,ORM2,9,117085694,117092465,+,Splice_Site,DEL,CCCCCTGCCTCCAAACACAGAAGCCTCACTGCAGAGTCCTTCACGG...,CCCCCTGCCTCCAAACACAGAAGCCTCACTGCAGAGTCCTTCACGG...,-,NaN,NaN,NaN,ENST00000259396,3420
332609,TCGA-G4-6628-01,FAM131C,CLCNKB,1,16362868,16386126,+,Splice_Site,DEL,GGGGGGCATGGGTGGGGACGGCCTCAGTGCCTGATGGAGCTGCTCC...,GGGGGGCATGGGTGGGGACGGCCTCAGTGCCTGATGGAGCTGCTCC...,-,NaN,NaN,NaN,ENST00000375662,15864

In [70]:
uniqueHugo = dataMutation_TCGA_cleaned['Hugo_Symbol'].nunique(dropna=False)
uniqueTranscript = dataMutation_TCGA_cleaned['Transcript_ID'].nunique(dropna=False)
uniqueHugo, uniqueTranscript

(20206, 20582)

In [71]:
unknownHugo = (dataMutation_TCGA_cleaned['Hugo_Symbol'] == 'Unknown').sum()
emptyHugo = (dataMutation_TCGA_cleaned['Hugo_Symbol'] == '').sum()
naHugo = pd.isna(dataMutation_TCGA_cleaned['Hugo_Symbol']).sum()

unknownTranscript = (dataMutation_TCGA_cleaned['Transcript_ID'] == 'Unknown').sum()
emptyTranscript = (dataMutation_TCGA_cleaned['Transcript_ID'] == '').sum()
naTranscript = pd.isna(dataMutation_TCGA_cleaned['Transcript_ID']).sum()

unknownHugoUnknownTranscript = (dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == 'Unknown').sum()
emptyHugoUnknownTranscript = (dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Hugo_Symbol'] == '']['Transcript_ID'] == 'Unknown').sum()
naHugoUnknownTranscript = (dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Hugo_Symbol'].isna()]['Transcript_ID'] == 'Unknown').sum()
unknownHugoEmptyTranscript = (dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()
emptyHugoEmptyTranscript = (dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Hugo_Symbol'] == '']['Transcript_ID'] == '').sum()
naHugoEmptyTranscript = (dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Hugo_Symbol'].isna()]['Transcript_ID'] == '').sum()
unknownHugoNaTranscript = (pd.isna(dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'])).sum()
emptyHugoNaTranscript = (pd.isna(dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Hugo_Symbol'] == '']['Transcript_ID'])).sum()
naHugoNaTranscript = (pd.isna(dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Hugo_Symbol'].isna()]['Transcript_ID'])).sum()

unknownHugoEmptyTranscript = (dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Hugo_Symbol'] == 'Unknown']['Transcript_ID'] == '').sum()

(unknownHugo, emptyHugo, naHugo), (unknownTranscript, emptyTranscript, naTranscript), ((unknownHugoUnknownTranscript, emptyHugoUnknownTranscript, naHugoUnknownTranscript), (unknownHugoEmptyTranscript, emptyHugoEmptyTranscript, naHugoEmptyTranscript), (unknownHugoNaTranscript, emptyHugoNaTranscript, naHugoNaTranscript))

((0, 0, 0), (0, 0, 0), ((0, 0, 0), (0, 0, 0), (0, 0, 0)))

In [72]:
dataMutation_TCGA_cleaned['Mutation_Length'] = dataMutation_TCGA_cleaned['End_Position'] - dataMutation_TCGA_cleaned['Start_Position'] + 1
dataMutation_TCGA_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length
0,TCGA-AF-2687-01,WDR37,WDR37,10,1130478,1130478,+,Missense_Mutation,SNP,G,G,A,ENST00000263150.4:c.532G>A,p.D178N,178.0,ENST00000263150,82760,1
1,TCGA-AF-2687-01,HSPA14,HSPA14,10,14896137,14896137,+,Missense_Mutation,SNP,G,G,A,ENST00000378372.3:c.748G>A,p.D250N,250.0,ENST00000378372,33578,1
2,TCGA-AF-2687-01,ARHGAP20,ARHGAP20,11,110450666,110450666,+,Missense_Mutation,SNP,G,G,A,ENST00000260283.4:c.3004C>T,p.P1002S,1002.0,ENST00000260283,136147,1
3,TCGA-AF-2687-01,STT3A,STT3A,11,125478127,125478127,+,Missense_Mutation,SNP,G,G,A,ENST00000392708.4:c.904G>A,p.V302I,302.0,ENST00000392708,33504,1
4,TCGA-AF-2687-01,ANO3,ANO3,11,26620415,26620415,+,Missense_Mutation,SNP,G,G,A,ENST00000256737.3:c.1541G>A,p.R514H,514.0,ENST00000256737,474007,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332605,TCGA-D5-6928-01,GPR42,FFAR3,19,35849879,35862348,+,Splice_Site,DEL,CCCCCTCAACCTGCTGGCCCTGGTGGTCTTCGTGGGCAAGCTGCAG...,CCCCCTCAACCTGCTGGCCCTGGTGGTCTTCGTGGGCAAGCTGCAG...,-,NaN,NaN,NaN,ENST00000454971,2025,12470
332606,TCGA-F4-6461-01,ZNF799,ZNF799,19,12502563,12542338,+,Splice_Site,DEL,TCTCATGCATATGTAATAAACTGGGCCAAAAAAACGCTTTCCCACA...,TCTCATGCATATGTAATAAACTGGGCCAAAAAAACGCTTTCCCACA...,-,NaN,NaN,NaN,ENST00000430385,11256,39776
332607,TCGA-G4-6588-01,ITGA6,ITGA6,2,173368938,173368990,+,3'UTR,DEL,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,-,NaN,NaN,1117.0,ENST00000442250,79100,53
332608,TCGA-G4-6588-01,ORM1,ORM2,9,117085694,117092465,+,Splice_Site,DEL,CCCCCTGCCTCCAAACACAGAAGCCTCACTGCAGAGTCCTTCACGG...,CCCCCTGCCTCCAAACACAGAAGCCTCACTGCAGAGTCCTTCACGG...,-,NaN,NaN,NaN,ENST00000259396,3420,6772
332609,TCGA-G4-6628-01,FAM131C,CLCNKB,1,16362868,16386126,+,Splice_Site,DEL,GGGGGGCATGGGTGGGGACGGCCTCAGTGCCTGATGGAGCTGCTCC...,GGGGGGCATGGGTGGGGACGGCCTCAGTGCCTGATGGAGCTGCTCC...,-,NaN,NaN,NaN,ENST00000375662,15864,23259

In [73]:
### TODO: what to do with missing protein positions? For now, removing them
dataMutation_TCGA_cleaned = dataMutation_TCGA_cleaned[~dataMutation_TCGA_cleaned['Protein_position'].isna()].copy()
dataMutation_TCGA_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length
0,TCGA-AF-2687-01,WDR37,WDR37,10,1130478,1130478,+,Missense_Mutation,SNP,G,G,A,ENST00000263150.4:c.532G>A,p.D178N,178.0,ENST00000263150,82760,1
1,TCGA-AF-2687-01,HSPA14,HSPA14,10,14896137,14896137,+,Missense_Mutation,SNP,G,G,A,ENST00000378372.3:c.748G>A,p.D250N,250.0,ENST00000378372,33578,1
2,TCGA-AF-2687-01,ARHGAP20,ARHGAP20,11,110450666,110450666,+,Missense_Mutation,SNP,G,G,A,ENST00000260283.4:c.3004C>T,p.P1002S,1002.0,ENST00000260283,136147,1
3,TCGA-AF-2687-01,STT3A,STT3A,11,125478127,125478127,+,Missense_Mutation,SNP,G,G,A,ENST00000392708.4:c.904G>A,p.V302I,302.0,ENST00000392708,33504,1
4,TCGA-AF-2687-01,ANO3,ANO3,11,26620415,26620415,+,Missense_Mutation,SNP,G,G,A,ENST00000256737.3:c.1541G>A,p.R514H,514.0,ENST00000256737,474007,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332576,TCGA-WS-AB45-01,TBL1X,TBL1X,X,9661224,9661224,+,Silent,SNP,C,C,T,ENST00000217964.7:c.927C>T,p.D309=,309.0,ENST00000217964,256446,1
332577,TCGA-WS-AB45-01,SHROOM2,SHROOM2,X,9863424,9863424,+,Silent,SNP,G,G,A,ENST00000380913.3:c.1476G>A,p.A492=,492.0,ENST00000380913,162988,1
332578,TCGA-WS-AB45-01,PCDH19,PCDH19,X,99662857,99662857,+,Missense_Mutation,SNP,C,C,T,ENST00000373034.4:c.739G>A,p.V247M,247.0,ENST00000373034,118630,1
332583,TCGA-5M-AAT6-01,KRTAP1-1,KRTAP1-3,17,39190708,39197254,+,3'UTR,DEL,GGGGGGCAGGCAGGTACCCTCCACACGGCAGTCTGGGCGGCACCAC...,GGGGGGCAGGCAGGTACCCTCCACACGGCAGTCTGGGCGGCACCAC...,-,NaN,NaN,132.0,ENST00000306271,903,6547
332607,TCGA-G4-6588-01,ITGA6,ITGA6,2,173368938,173368990,+,3'UTR,DEL,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,-,NaN,NaN,1117.0,ENST00000442250,79100,53

In [74]:
### TODO: Is this correct?
transcriptIds_proteinIds_mapping = {tid: (len(ensembl.transcript_by_id(tid).protein_sequence) if ensembl.transcript_by_id(tid).protein_sequence is not None else np.nan) for tid in dataMutation_TCGA_cleaned['Transcript_ID'].unique()}
transcriptIds_proteinIds_mapping

{'ENST00000263150': 494,
 'ENST00000378372': 509,
 'ENST00000260283': 1191,
 'ENST00000392708': 705,
 'ENST00000256737': 981,
 'ENST00000263776': 501,
 'ENST00000308064': 411,
 'ENST00000378623': 1905,
 'ENST00000395079': 305,
 'ENST00000358353': 845,
 'ENST00000261637': 2785,
 'ENST00000355819': 241,
 'ENST00000550722': 4272,
 'ENST00000261655': 1052,
 'ENST00000359062': 1141,
 'ENST00000360299': 215,
 'ENST00000454289': 325,
 'ENST00000558850': 811,
 'ENST00000539517': 507,
 'ENST00000280979': 2319,
 'ENST00000395834': 358,
 'ENST00000395125': 1078,
 'ENST00000430451': 645,
 'ENST00000163416': 731,
 'ENST00000249749': 685,
 'ENST00000301732': 1704,
 'ENST00000380148': 132,
 'ENST00000251166': 925,
 'ENST00000300589': 1040,
 'ENST00000379906': 617,
 'ENST00000290881': 471,
 'ENST00000302628': 271,
 'ENST00000317447': 576,
 'ENST00000321105': 1001,
 'ENST00000246646': 456,
 'ENST00000258960': 496,
 'ENST00000322765': 788,
 'ENST00000336915': 359,
 'ENST00000290866': 1306,
 'ENST00000314256': 1356,
 'ENST00000586717': 1133,
 'ENST00000269305': 393,
 'ENST00000324750': 325,
 'ENST00000284202': 320,
 'ENST00000400256': 742,
 'ENST00000537592': 1300,
 'ENST00000251472': 1570,
 'ENST00000355537': 1300,
 'ENST00000221856': 496,
 'ENST00000262887': 633,
 'ENST00000263257': 492,
 'ENST00000359920': 1173,
 'ENST00000256637': 831,
 'ENST00000336338': 2223,
 'ENST00000368099': 551,
 'ENST00000355305': 869,
 'ENST00000367342': 663,
 'ENST00000366757': 326,
 'ENST00000319653': 1722,
 'ENST00000324856': 2285,
 'ENST00000207457': 430,
 'ENST00000257181': 312,
 'ENST00000370757': 359,
 'ENST00000370717': 1474,
 'ENST00000381458': 693,
 'ENST00000375494': 476,
 'ENST00000371998': 1424,
 'ENST00000371652': 270,
 'ENST00000252999': 3695,
 'ENST00000359125': 872,
 'ENST00000284987': 930,
 'ENST00000338306': 752,
 'ENST00000591111': 34350,
 'ENST00000428443': 696,
 'ENST00000236957': 225,
 'ENST00000439458': 3258,
 'ENST00000347842': 647,
 'ENST00000283943': 1992,
 'ENST00000295550': 3177,
 'ENST00000406316': 1477,
 'ENST00000256452': 420,
 'ENST00000397491': 1208,
 'ENST00000281708': 707,
 'ENST00000264431': 1499,
 'ENST00000338566': 445,
 'ENST00000280605': 626,
 'ENST00000282924': 626,
 'ENST00000310581': 1132,
 'ENST00000261366': 586,
 'ENST00000395003': 790,
 'ENST00000532602': 950,
 'ENST00000307360': 948,
 'ENST00000519479': 923,
 'ENST00000377365': 535,
 'ENST00000335815': 605,
 'ENST00000389805': 440,
 'ENST00000382142': 747,
 'ENST00000399503': 1512,
 'ENST00000441448': 306,
 'ENST00000275233': 1683,
 'ENST00000367339': 244,
 'ENST00000367255': 8797,
 'ENST00000274867': 1068,
 'ENST00000257749': 841,
 'ENST00000297431': 435,
 'ENST00000275815': 976,
 'ENST00000424383': 828,
 'ENST00000408931': 447,
 'ENST00000199447': 588,
 'ENST00000404826': 2213,
 'ENST00000223324': 188,
 'ENST00000334955': 846,
 'ENST00000356239': 3907,
 'ENST00000359863': 3859,
 'ENST00000388996': 872,
 'ENST00000438773': 1148,
 'ENST00000319675': 395,
 'ENST00000374902': 929,
 'ENST00000259324': 810,
 'ENST00000303407': 726,
 'ENST00000298532': 1469,
 'ENST00000308675': 606,
 'ENST00000259569': 1105,
 'ENST00000376238': 691,
 'ENST00000372068': 297,
 'ENST00000371106': 674,
 'ENST00000370526': 146,
 'ENST00000546474': 677,
 'ENST00000261609': 4834,
 'ENST00000389286': 1150,
 'ENST00000330684': 1464,
 'ENST00000337929': 538,
 'ENST00000268296': 1163,
 'ENST00000315576': 823,
 'ENST00000379803': 1162,
 'ENST00000221891': 651,
 'ENST00000374221': 520,
 'ENST00000373480': 1035,
 'ENST00000421030': 1323,
 'ENST00000252998': 664,
 'ENST00000217182': 463,
 'ENST00000245663': 589,
 'ENST00000215739': 840,
 'ENST00000215743': 488,
 'ENST00000337859': 426,
 'ENST00000328333': 2944,
 'ENST00000461745': 1378,
 'ENST00000256084': 1064,
 'ENST00000355472': 576,
 'ENST00000300179': 841,
 'ENST00000392957': 1021,
 'ENST00000399583': 1075,
 'ENST00000354212': 1455,
 'ENST00000220888': 1281,
 'ENST00000356083': 1860,
 'ENST00000378909': 412,
 'ENST00000245838': 1593,
 'ENST00000377604': 930,
 'ENST00000373034': 1148,
 'ENST00000324109': 1577,
 'ENST00000369983': 1859,
 'ENST00000369701': 1222,
 'ENST00000321505': 1849,
 'ENST00000279791': 310,
 'ENST00000278407': 500,
 'ENST00000320585': 332,
 'ENST00000279839': 228,
 'ENST00000070846': 881,
 'ENST00000266594': 131,
 'ENST00000330722': 564,
 'ENST00000549446': 638,
 'ENST00000328827': 340,
 'ENST00000267339': 420,
 'ENST00000360631': 740,
 'ENST00000250498': 113,
 'ENST00000541158': 764,
 'ENST00000329082': 450,
 'ENST00000396368': 1742,
 'ENST00000219255': 346,
 'ENST00000268802': 412,
 'ENST00000262144': 974,
 'ENST00000268695': 522,
 'ENST00000409168': 500,
 'ENST00000225916': 837,
 'ENST00000342988': 552,
 'ENST00000342784': 735,
 'ENST00000355868': 472,
 'ENST00000222305': 346,
 'ENST00000264554': 582,
 'ENST00000391876': 343,
 'ENST00000309877': 427,
 'ENST00000270460': 576,
 'ENST00000390649': 1200,
 'ENST00000597188': 1103,
 'ENST00000369769': 575,
 'ENST00000308647': 648,
 'ENST00000263525': 1358,
 'ENST00000367400': 1406,
 'ENST00000366955': 3114,
 'ENST00000323699': 323,
 'ENST00000422127': 7968,
 'ENST00000262873': 1983,
 'ENST00000237536': 1661,
 'ENST00000262865': 487,
 'ENST00000299824': 567,
 'ENST00000372262': 828,
 'ENST00000359271': 541,
 'ENST00000291526': 129,
 'ENST00000354992': 756,
 'ENST00000337304': 351,
 'ENST00000328823': 309,
 'ENST00000409886': 1758,
 'ENST00000263331': 1135,
 'ENST00000389484': 4599,
 'ENST00000409855': 1682,
 'ENST00000359846': 610,
 'ENST00000404537': 1896,
 'ENST00000272907': 653,
 'ENST00000392039': 319,
 'ENST00000311075': 511,
 'ENST00000334444': 1437,
 'ENST00000450053': 2754,
 'ENST00000409535': 1467,
 'ENST00000273283': 911,
 'ENST00000389617': 443,
 'ENST00000264193': 454,
 'ENST00000394820': 968,
 'ENST00000438793': 973,
 'ENST00000257430': 2843,
 'ENST00000265104': 4624,
 'ENST00000504120': 950,
 'ENST00000283426': 1271,
 'ENST00000356031': 1822,
 'ENST00000311381': 240,
 'ENST00000360359': 1134,
 'ENST00000373866': 340,
 'ENST00000355574': 970,
 'ENST00000335870': 495,
 'ENST00000312371': 498,
 'ENST00000404991': 636,
 'ENST00000407838': 236,
 'ENST00000286355': 1251,
 'ENST00000525985': 2420,
 'ENST00000276461': 339,
 'ENST00000487273': 819,
 'ENST00000539294': 584,
 'ENST00000302190': 201,
 'ENST00000372731': 2472,
 'ENST00000488444': 1235,
 'ENST00000376207': 431,
 'ENST00000252336': 1023,
 'ENST00000373200': 361,
 'ENST00000257359': 889,
 'ENST00000335987': 267,
 'ENST00000312562': 271,
 'ENST00000311330': 757,
 'ENST00000551590': 587,
 'ENST00000397558': 573,
 'ENST00000399788': 1690,
 'ENST00000542859': 383,
 'ENST00000397795': 1603,
 'ENST00000399410': 1531,
 'ENST00000440851': 561,
 'ENST00000335255': 660,
 'ENST00000263266': 478,
 'ENST00000358432': 976,
 'ENST00000272117': 946,
 'ENST00000378466': 773,
 'ENST00000370571': 1714,
 'ENST00000201979': 298,
 'ENST00000373187': 1441,
 'ENST00000045083': 946,
 'ENST00000361866': 1028,
 'ENST00000264448': 4167,
 'ENST00000357750': 473,
 'ENST00000399132': 654,
 'ENST00000296739': 430,
 'ENST00000338891': 1140,
 'ENST00000303921': 613,
 'ENST00000388913': 1179,
 'ENST00000322810': 4684,
 'ENST00000221166': 916,
 'ENST00000218316': 617,
 'ENST00000340888': 343,
 'ENST00000263246': 486,
 'ENST00000329962': 1039,
 'ENST00000306904': 392,
 'ENST00000300648': 2671,
 'ENST00000262375': 480,
 'ENST00000308251': 519,
 'ENST00000340748': 1616,
 'ENST00000293771': 615,
 'ENST00000233596': 184,
 'ENST00000361574': 268,
 'ENST00000375985': 596,
 'ENST00000302326': 1320,
 'ENST00000264771': 504,
 'ENST00000529859': 936,
 'ENST00000348628': 478,
 'ENST00000329542': 842,
 'ENST00000358571': 137,
 'ENST00000306085': 755,
 'ENST00000003100': 509,
 'ENST00000327381': 650,
 'ENST00000371974': 300,
 'ENST00000372588': 406,
 'ENST00000342995': 503,
 'ENST00000369839': 800,
 'ENST00000438700': 767,
 'ENST00000399262': 2540,
 'ENST00000334801': 1499,
 'ENST00000300632': 180,
 'ENST00000263401': 198,
 'ENST00000396950': 320,
 'ENST00000309106': 321,
 'ENST00000454689': 564,
 'ENST00000280758': 1104,
 'ENST00000242592': 412,
 'ENST00000402868': 352,
 'ENST00000299308': 1078,
 'ENST00000359864': 434,
 'ENST00000196169': 651,
 'ENST00000216455': 255,
 'ENST00000298351': 806,
 'ENST00000348070': 968,
 'ENST00000335625': 462,
 'ENST00000388901': 443,
 'ENST00000323940': 667,
 'ENST00000568449': 379,
 'ENST00000356183': 2109,
 'ENST00000251020': 1324,
 'ENST00000339953': 455,
 'ENST00000570137': 506,
 'ENST00000343629': 456,
 'ENST00000253458': 1217,
 'ENST00000225972': 307,
 'ENST00000284425': 1617,
 'ENST00000269081': 1543,
 'ENST00000446526': 385,
 'ENST00000582970': 5207,
 'ENST00000300976': 615,
 'ENST00000222330': 483,
 'ENST00000599921': 541,
 'ENST00000270642': 336,
 'ENST00000600412': 613,
 'ENST00000342929': 1043,
 'ENST00000343320': 476,
 'ENST00000326233': 114,
 'ENST00000338920': 2817,
 'ENST00000367618': 1012,
 'ENST00000271588': 5635,
 'ENST00000367429': 1231,
 'ENST00000270218': 177,
 'ENST00000366672': 571,
 'ENST00000366574': 4967,
 'ENST00000306687': 311,
 'ENST00000333082': 271,
 'ENST00000278886': 1382,
 'ENST00000302342': 1048,
 'ENST00000331758': 396,
 'ENST00000359759': 1754,
 'ENST00000300527': 1019,
 'ENST00000249501': 340,
 'ENST00000319170': 1250,
 'ENST00000331683': 631,
 'ENST00000171887': 1735,
 'ENST00000324695': 1104,
 'ENST00000327757': 1458,
 'ENST00000421745': 4857,
 'ENST00000318357': 305,
 'ENST00000290868': 676,
 'ENST00000476941': 793,
 'ENST00000336824': 1204,
 'ENST00000306376': 510,
 'ENST00000395052': 872,
 'ENST00000263923': 1356,
 'ENST00000398631': 941,
 'ENST00000231134': 795,
 'ENST00000231137': 793,
 'ENST00000252087': 944,
 'ENST00000435817': 690,
 'ENST00000411494': 227,
 'ENST00000425232': 3197,
 'ENST00000399438': 417,
 'ENST00000405460': 6306,
 'ENST00000274432': 254,
 'ENST00000379982': 611,
 'ENST00000368662': 475,
 'ENST00000372445': 557,
 'ENST00000205386': 1761,
 'ENST00000265854': 718,
 'ENST00000324972': 645,
 'ENST00000297405': 3707,
 'ENST00000323289': 1584,
 'ENST00000297423': 915,
 'ENST00000356297': 1463,
 'ENST00000331251': 328,
 'ENST00000276594': 571,
 'ENST00000265814': 604,
 'ENST00000371817': 1838,
 'ENST00000325303': 346,
 'ENST00000375854': 156,
 'ENST00000358157': 378,
 'ENST00000356444': 862,
 'ENST00000218032': 1041,
 'ENST00000527548': 133,
 'ENST00000257974': 513,
 'ENST00000341267': 383,
 'ENST00000268058': 882,
 'ENST00000344626': 1647,
 'ENST00000170168': 1221,
 'ENST00000270301': 1518,
 'ENST00000318083': 415,
 'ENST00000282326': 408,
 'ENST00000343090': 1302,
 'ENST00000368680': 1061,
 'ENST00000367556': 180,
 'ENST00000379453': 572,
 'ENST00000360469': 916,
 'ENST00000336156': 404,
 'ENST00000342894': 309,
 'ENST00000234142': 1949,
 'ENST00000409878': 610,
 'ENST00000273353': 1946,
 'ENST00000336307': 417,
 'ENST00000399429': 1125,
 'ENST00000401592': 785,
 'ENST00000372919': 488,
 'ENST00000372027': 949,
 'ENST00000302797': 322,
 'ENST00000311659': 655,
 'ENST00000314612': 312,
 'ENST00000333976': 313,
 'ENST00000312253': 324,
 'ENST00000300127': 314,
 'ENST00000329328': 314,
 'ENST00000294168': 622,
 'ENST00000393324': 604,
 'ENST00000321867': 1050,
 'ENST00000261195': 703,
 'ENST00000300131': 525,
 'ENST00000376335': 532,
 'ENST00000375774': 422,
 'ENST00000361283': 812,
 'ENST00000515384': 671,
 'ENST00000409874': 1382,
 'ENST00000390551': 377,
 'ENST00000299088': 538,
 'ENST00000360586': 1129,
 'ENST00000554719': 1061,
 'ENST00000393151': 2635,
 'ENST00000300177': 184,
 'ENST00000251076': 3036,
 'ENST00000389398': 1184,
 'ENST00000301740': 2752,
 'ENST00000262518': 3230,
 'ENST00000394979': 1829,
 'ENST00000359128': 1036,
 'ENST00000306875': 612,
 'ENST00000323786': 789,
 'ENST00000268489': 3703,
 'ENST00000225387': 215,
 'ENST00000361566': 400,
 'ENST00000246914': 1243,
 'ENST00000448276': 531,
 'ENST00000243457': 427,
 'ENST00000397545': 1142,
 'ENST00000426216': 1147,
 'ENST00000590320': 353,
 'ENST00000343769': 620,
 'ENST00000392213': 626,
 'ENST00000221347': 5405,
 'ENST00000340963': 641,
 'ENST00000324001': 1461,
 'ENST00000246792': 218,
 'ENST00000324602': 652,
 'ENST00000456448': 339,
 'ENST00000314485': 613,
 'ENST00000368013': 1101,
 'ENST00000256785': 569,
 'ENST00000373129': 435,
 'ENST00000373091': 919,
 'ENST00000372207': 473,
 'ENST00000372980': 696,
 'ENST00000201031': 450,
 'ENST00000319441': 622,
 'ENST00000371030': 1677,
 'ENST00000400546': 837,
 'ENST00000381815': 1010,
 'ENST00000260952': 643,
 'ENST00000295049': 501,
 'ENST00000406610': 1205,
 'ENST00000360351': 1827,
 'ENST00000359671': 2386,
 'ENST00000436022': 161,
 'ENST00000324093': 1925,
 'ENST00000428331': 919,
 'ENST00000286349': 723,
 'ENST00000231706': 771,
 'ENST00000311806': 527,
 'ENST00000402939': 1462,
 'ENST00000265174': 624,
 'ENST00000302053': 866,
 'ENST00000306193': 237,
 'ENST00000264229': 1233,
 'ENST00000314595': 1174,
 'ENST00000381210': 363,
 'ENST00000379807': 719,
 'ENST00000338882': 366,
 'ENST00000379446': 834,
 'ENST00000448612': 895,
 'ENST00000306151': 4493,
 'ENST00000340112': 376,
 'ENST00000285928': 825,
 'ENST00000354042': 626,
 'ENST00000404938': 1257,
 'ENST00000409508': 4516,
 'ENST00000396946': 1154,
 'ENST00000223029': 320,
 'ENST00000248564': 73,
 'ENST00000262113': 1465,
 'ENST00000301905': 322,
 'ENST00000285393': 350,
 'ENST00000374879': 380,
 'ENST00000481272': 530,
 'ENST00000408936': 1189,
 'ENST00000380055': 370,
 'ENST00000377966': 971,
 'ENST00000375544': 380,
 'ENST00000309720': 349,
 'ENST00000424805': 463,
 'ENST00000373316': 417,
 'ENST00000369849': 499,
 'ENST00000355995': 619,
 'ENST00000351270': 560,
 'ENST00000359988': 1730,
 'ENST00000537242': 468,
 'ENST00000368654': 3256,
 'ENST00000252936': 902,
 'ENST00000298943': 255,
 'ENST00000605216': 1837,
 'ENST00000319338': 903,
 'ENST00000360374': 309,
 'ENST00000301765': 355,
 'ENST00000448903': 939,
 'ENST00000261740': 871,
 'ENST00000389561': 3123,
 'ENST00000256958': 691,
 'ENST00000256078': 189,
 'ENST00000432328': 432,
 'ENST00000549396': 1257,
 'ENST00000282397': 1338,
 'ENST00000325089': 958,
 'ENST00000334743': 524,
 'ENST00000390604': 117,
 'ENST00000267426': 292,
 'ENST00000399232': 956,
 'ENST00000282146': 408,
 'ENST00000389232': 4870,
 'ENST00000316623': 2871,
 'ENST00000261875': 362,
 'ENST00000348261': 2353,
 'ENST00000389176': 674,
 'ENST00000262302': 271,
 'ENST00000301030': 2663,
 'ENST00000341712': 1025,
 'ENST00000311269': 808,
 'ENST00000359995': 221,
 'ENST00000306749': 2511,
 'ENST00000310045': 1222,
 'ENST00000299687': 2248,
 'ENST00000244336': 349,
 'ENST00000340093': 335,
 'ENST00000301286': 1357,
 'ENST00000328771': 1143,
 'ENST00000323446': 803,
 'ENST00000338372': 236,
 'ENST00000391713': 496,
 'ENST00000346664': 321,
 'ENST00000369771': 511,
 'ENST00000369047': 540,
 'ENST00000367262': 123,
 'ENST00000367147': 514,
 'ENST00000366582': 2144,
 'ENST00000361632': 836,
 'ENST00000372470': 635,
 'ENST00000337338': 858,
 'ENST00000338074': 881,
 'ENST00000344754': 1709,
 'ENST00000454036': 1139,
 'ENST00000359930': 870,
 'ENST00000417564': 1571,
 'ENST00000263119': 2220,
 'ENST00000407997': 384,
 'ENST00000409816': 2116,
 'ENST00000420890': 1530,
 'ENST00000312428': 4024,
 'ENST00000342788': 1308,
 'ENST00000357430': 720,
 'ENST00000254654': 392,
 'ENST00000310397': 1413,
 'ENST00000233557': 535,
 'ENST00000490686': 117,
 'ENST00000312481': 2615,
 'ENST00000285046': 1462,
 'ENST00000407528': 435,
 'ENST00000344876': 1135,
 'ENST00000257290': 1089,
 'ENST00000282478': 1301,
 'ENST00000281092': 822,
 'ENST00000282356': 473,
 'ENST00000285689': 432,
 'ENST00000296721': 768,
 'ENST00000428202': 575,
 'ENST00000610273': 520,
 'ENST00000366953': 555,
 'ENST00000356950': 126,
 'ENST00000326195': 845,
 'ENST00000275015': 500,
 'ENST00000230588': 746,
 'ENST00000369950': 797,
 'ENST00000315184': 344,
 'ENST00000436302': 920,
 'ENST00000422774': 1950,
 'ENST00000319551': 969,
 'ENST00000404767': 2190,
 'ENST00000297268': 1366,
 'ENST00000262585': 1198,
 'ENST00000256246': 2789,
 'ENST00000220659': 419,
 'ENST00000220676': 2156,
 'ENST00000286614': 607,
 'ENST00000434106': 829,
 'ENST00000341511': 2436,
 'ENST00000371122': 1054,
 'ENST00000370532': 262,
 'ENST00000369704': 872,
 'ENST00000305242': 1044,
 'ENST00000361713': 1341,
 'ENST00000355710': 1114,
 'ENST00000325239': 3184,
 'ENST00000282633': 1341,
 'ENST00000280772': 4377,
 'ENST00000373644': 2136,
 'ENST00000224721': 3359,
 'ENST00000278715': 361,
 'ENST00000392664': 391,
 'ENST00000377264': 1938,
 'ENST00000299441': 3298,
 'ENST00000265641': 773,
 'ENST00000318881': 491,
 'ENST00000409709': 2215,
 'ENST00000328194': 1287,
 'ENST00000317775': 1434,
 'ENST00000315436': 404,
 'ENST00000288912': 1149,
 'ENST00000405201': 2514,
 'ENST00000303846': 431,
 'ENST00000262061': 177,
 'ENST00000382871': 1377,
 'ENST00000242839': 1465,
 'ENST00000335290': 544,
 'ENST00000298694': 1519,
 'ENST00000354386': 1644,
 'ENST00000380950': 1710,
 'ENST00000261844': 1076,
 'ENST00000268124': 1239,
 'ENST00000299320': 520,
 'ENST00000290567': 575,
 'ENST00000254940': 180,
 'ENST00000248248': 547,
 'ENST00000302536': 419,
 'ENST00000341671': 947,
 'ENST00000381951': 309,
 'ENST00000559488': 788,
 'ENST00000309794': 456,
 'ENST00000299721': 160,
 'ENST00000221980': 924,
 'ENST00000252595': 646,
 'ENST00000261560': 570,
 'ENST00000597761': 503,
 'ENST00000078445': 461,
 'ENST00000310054': 504,
 'ENST00000251268': 2845,
 'ENST00000215637': 382,
 'ENST00000359032': 977,
 'ENST00000359798': 903,
 'ENST00000321030': 499,
 'ENST00000414468': 627,
 'ENST00000397910': 14507,
 'ENST00000336751': 426,
 'ENST00000271915': 731,
 'ENST00000294794': 750,
 'ENST00000375662': 280,
 'ENST00000251296': 467,
 'ENST00000374490': 325,
 'ENST00000356575': 1541,
 'ENST00000235628': 368,
 'ENST00000312233': 620,
 'ENST00000354431': 624,
 'ENST00000370192': 1025,
 'ENST00000263177': 321,
 'ENST00000252996': 1085,
 'ENST00000217188': 488,
 'ENST00000333337': 323,
 'ENST00000400485': 939,
 'ENST00000359337': 1838,
 'ENST00000309863': 1684,
 'ENST00000272520': 287,
 'ENST00000322313': 1336,
 'ENST00000356920': 1075,
 'ENST00000409487': 1214,
 'ENST00000260988': 175,
 'ENST00000233242': 4563,
 'ENST00000258411': 417,
 'ENST00000341772': 737,
 'ENST00000392017': 607,
 'ENST00000408934': 389,
 'ENST00000282388': 494,
 'ENST00000238714': 736,
 'ENST00000272395': 446,
 'ENST00000307296': 868,
 'ENST00000273173': 594,
 'ENST00000449082': 1956,
 'ENST00000296518': 690,
 'ENST00000393743': 1712,
 'ENST00000399878': 1132,
 'ENST00000358602': 2603,
 'ENST00000361016': 776,
 'ENST00000296604': 465,
 'ENST00000389100': 592,
 'ENST00000254765': 291,
 'ENST00000368508': 2347,
 'ENST00000253332': 1782,
 'ENST00000321394': 556,
 'ENST00000392142': 1608,
 'ENST00000412168': 221,
 'ENST00000377050': 165,
 'ENST00000377034': 961,
 'ENST00000237201': 294,
 'ENST00000369352': 543,
 'ENST00000292644': 433,
 'ENST00000287907': 357,
 'ENST00000490531': 1562,
 'ENST00000440155': 293,
 'ENST00000457091': 1211,
 'ENST00000297186': 870,
 'ENST00000405086': 949,
 'ENST00000265723': 1286,
 'ENST00000395172': 132,
 'ENST00000409379': 1378,
 'ENST00000381840': 312,
 'ENST00000381418': 1189,
 'ENST00000522362': 364,
 'ENST00000305364': 493,
 'ENST00000537824': 3564,
 'ENST00000458549': 380,
 'ENST00000380821': 411,
 'ENST00000324333': 775,
 'ENST00000344803': 1576,
 'ENST00000372774': 183,
 'ENST00000255499': 428,
 'ENST00000262820': 655,
 'ENST00000285879': 1142,
 'ENST00000331035': 378,
 'ENST00000369850': 2647,
 'ENST00000360256': 2351,
 'ENST00000379059': 1462,
 'ENST00000346193': 791,
 'ENST00000297866': 976,
 'ENST00000374906': 258,
 'ENST00000362002': 318,
 'ENST00000374852': 704,
 'ENST00000342206': 339,
 'ENST00000381003': 332,
 'ENST00000361355': 511,
 'ENST00000369068': 1461,
 'ENST00000370196': 330,
 'ENST00000392982': 755,
 'ENST00000355044': 1379,
 'ENST00000377833': 3623,
 'ENST00000377602': 398,
 'ENST00000361271': 288,
 'ENST00000373207': 1223,
 'ENST00000358415': 946,
 'ENST00000344327': 931,
 'ENST00000375735': 4307,
 'ENST00000344514': 310,

In [75]:
dataMutation_TCGA_cleaned['Protein_Length'] = dataMutation_TCGA_cleaned['Transcript_ID'].map(transcriptIds_proteinIds_mapping)
dataMutation_TCGA_cleaned

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,TCGA-AF-2687-01,WDR37,WDR37,10,1130478,1130478,+,Missense_Mutation,SNP,G,G,A,ENST00000263150.4:c.532G>A,p.D178N,178.0,ENST00000263150,82760,1,494
1,TCGA-AF-2687-01,HSPA14,HSPA14,10,14896137,14896137,+,Missense_Mutation,SNP,G,G,A,ENST00000378372.3:c.748G>A,p.D250N,250.0,ENST00000378372,33578,1,509
2,TCGA-AF-2687-01,ARHGAP20,ARHGAP20,11,110450666,110450666,+,Missense_Mutation,SNP,G,G,A,ENST00000260283.4:c.3004C>T,p.P1002S,1002.0,ENST00000260283,136147,1,1191
3,TCGA-AF-2687-01,STT3A,STT3A,11,125478127,125478127,+,Missense_Mutation,SNP,G,G,A,ENST00000392708.4:c.904G>A,p.V302I,302.0,ENST00000392708,33504,1,705
4,TCGA-AF-2687-01,ANO3,ANO3,11,26620415,26620415,+,Missense_Mutation,SNP,G,G,A,ENST00000256737.3:c.1541G>A,p.R514H,514.0,ENST00000256737,474007,1,981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332576,TCGA-WS-AB45-01,TBL1X,TBL1X,X,9661224,9661224,+,Silent,SNP,C,C,T,ENST00000217964.7:c.927C>T,p.D309=,309.0,ENST00000217964,256446,1,577
332577,TCGA-WS-AB45-01,SHROOM2,SHROOM2,X,9863424,9863424,+,Silent,SNP,G,G,A,ENST00000380913.3:c.1476G>A,p.A492=,492.0,ENST00000380913,162988,1,1616
332578,TCGA-WS-AB45-01,PCDH19,PCDH19,X,99662857,99662857,+,Missense_Mutation,SNP,C,C,T,ENST00000373034.4:c.739G>A,p.V247M,247.0,ENST00000373034,118630,1,1148
332583,TCGA-5M-AAT6-01,KRTAP1-1,KRTAP1-3,17,39190708,39197254,+,3'UTR,DEL,GGGGGGCAGGCAGGTACCCTCCACACGGCAGTCTGGGCGGCACCAC...,GGGGGGCAGGCAGGTACCCTCCACACGGCAGTCTGGGCGGCACCAC...,-,NaN,NaN,132.0,ENST00000306271,903,6547,177
332607,TCGA-G4-6588-01,ITGA6,ITGA6,2,173368938,173368990,+,3'UTR,DEL,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,-,NaN,NaN,1117.0,ENST00000442250,79100,53,1130

In [76]:
dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Protein_Length'].isna()]

Empty DataFrame
Columns: [Tumor_Sample_Barcode, Hugo_Symbol, original_Hugo_Symbol, Chromosome, Start_Position, End_Position, Strand, Variant_Classification, Variant_Type, Reference_Allele, Tumor_Seq_Allele1, Tumor_Seq_Allele2, HGVSc, HGVSp_Short, Protein_position, Transcript_ID, Gene_Length, Mutation_Length, Protein_Length]
Index: []

In [77]:
### TODO: What to do with nan protein length? for now remove
dataMutation_TCGA_cleaned = dataMutation_TCGA_cleaned[~dataMutation_TCGA_cleaned['Protein_Length'].isna()]

In [78]:
dataMutation_TCGA_cleaned[dataMutation_TCGA_cleaned['Protein_Length'].isna()]

Empty DataFrame
Columns: [Tumor_Sample_Barcode, Hugo_Symbol, original_Hugo_Symbol, Chromosome, Start_Position, End_Position, Strand, Variant_Classification, Variant_Type, Reference_Allele, Tumor_Seq_Allele1, Tumor_Seq_Allele2, HGVSc, HGVSp_Short, Protein_position, Transcript_ID, Gene_Length, Mutation_Length, Protein_Length]
Index: []

In [79]:
#save cleaned data
dataMutation_TCGA_cleaned.to_csv(data['TCGA_all___mutations'], sep="\t", index=False)

In [80]:
# clean memory
del dataMutation_TCGA, dataMutation_TCGA_cleaned

### Clinical Samples

In [81]:
dataClinicalSample_TCGA = pd.read_csv(data['original___TCGA___samples'], sep='\t', engine='python', comment='#')

In [82]:
dataClinicalSample_TCGA

,PATIENT_ID,SAMPLE_ID,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,TUMOR_TYPE,GRADE,TISSUE_PROSPECTIVE_COLLECTION_INDICATOR,TISSUE_RETROSPECTIVE_COLLECTION_INDICATOR,TISSUE_SOURCE_SITE,TUMOR_TISSUE_SITE,ANEUPLOIDY_SCORE,SAMPLE_TYPE,MSI_SCORE_MANTIS,MSI_SENSOR_SCORE,SOMATIC_STATUS,TMB_NONSYNONYMOUS
0,TCGA-AF-2687,TCGA-AF-2687-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,24.0,Primary,0.3529,0.08,Matched,3.233333
1,TCGA-AF-2689,TCGA-AF-2689-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,18.0,Primary,0.3486,1.28,Matched,1.733333
2,TCGA-AF-2690,TCGA-AF-2690-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,25.0,Primary,0.3412,0.03,Matched,2.400000
3,TCGA-AF-2691,TCGA-AF-2691-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,11.0,Primary,0.3267,1.16,Matched,2.233333
4,TCGA-AF-2692,TCGA-AF-2692-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectum Adenocarcinoma,NaN,Yes,No,AF,NaN,16.0,Primary,0.3259,1.32,Matched,0.733333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,TCGA-SS-A7HO,TCGA-SS-A7HO-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,No,Yes,SS,Colon,18.0,Primary,0.3318,1.19,Matched,4.833333
590,TCGA-T9-A92H,TCGA-T9-A92H-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,Yes,No,T9,Colon,11.0,Primary,0.3170,0.40,Matched,5.333333
591,TCGA-WS-AB45,TCGA-WS-AB45-01,MACR,Colorectal Adenocarcinoma,Mucinous Adenocarcinoma of the Colon and Rectum,"Colon Adenocarcinoma, Mucinous Type",NaN,No,Yes,WS,Colon,7.0,Primary,0.6782,24.48,Matched,84.166667
592,TCGA-5M-AAT5,TCGA-5M-AAT5-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,NaN,NaN,5M,NaN,10.0,Primary,0.3131,0.35,Matched,2.633333
593,TCGA-5M-AATA,TCGA-5M-AATA-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,NaN,NaN,5M,NaN,14.0,Primary,0.3123,0.08,Matched,2.366667

In [83]:
dataClinicalSample_TCGA.to_csv(data['TCGA_all___samples'], sep='\t', index=False)

In [84]:
del dataClinicalSample_TCGA

## Merge Datasets

### Mutation

In [85]:
dataMutation_Giannakis = pd.read_csv(data['Giannakis_all___mutations'], sep='\t', engine='python', comment='#')
dataMutation_Seshagiri = pd.read_csv(data['Seshagiri_all___mutations'], sep='\t', engine='python', comment='#')
dataMutation_TCGA = pd.read_csv(data['TCGA_all___mutations'], sep='\t', engine='python', comment='#')

In [86]:
len(dataMutation_Giannakis), len(dataMutation_Seshagiri), len(dataMutation_TCGA)

(277462, 35062, 278701)

In [87]:
dataMutation = pd.concat([dataMutation_Giannakis, dataMutation_Seshagiri, dataMutation_TCGA], ignore_index=True)

In [88]:
dataMutation

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,coadread_dfci_2016_1231,A1BG,A1BG,19,58862793,58862793,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100,8322,1,495
1,coadread_dfci_2016_1231,A1BG,A1BG,19,58862794,58862794,+,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100,8322,1,495
2,coadread_dfci_2016_2269,A1BG,A1BG,19,58862775,58862775,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.892G>A,p.E298K,298.0,ENST00000263100,8322,1,495
3,coadread_dfci_2016_230737,A1BG,A1BG,19,58858744,58858744,+,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100,8322,1,495
4,coadread_dfci_2016_2429,A1BG,A1BG,19,58862934,58862934,+,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100,8322,1,495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591220,TCGA-WS-AB45-01,TBL1X,TBL1X,X,9661224,9661224,+,Silent,SNP,C,C,T,ENST00000217964.7:c.927C>T,p.D309=,309.0,ENST00000217964,256446,1,577
591221,TCGA-WS-AB45-01,SHROOM2,SHROOM2,X,9863424,9863424,+,Silent,SNP,G,G,A,ENST00000380913.3:c.1476G>A,p.A492=,492.0,ENST00000380913,162988,1,1616
591222,TCGA-WS-AB45-01,PCDH19,PCDH19,X,99662857,99662857,+,Missense_Mutation,SNP,C,C,T,ENST00000373034.4:c.739G>A,p.V247M,247.0,ENST00000373034,118630,1,1148
591223,TCGA-5M-AAT6-01,KRTAP1-1,KRTAP1-3,17,39190708,39197254,+,3'UTR,DEL,GGGGGGCAGGCAGGTACCCTCCACACGGCAGTCTGGGCGGCACCAC...,GGGGGGCAGGCAGGTACCCTCCACACGGCAGTCTGGGCGGCACCAC...,-,NaN,NaN,132.0,ENST00000306271,903,6547,177
591224,TCGA-G4-6588-01,ITGA6,ITGA6,2,173368938,173368990,+,3'UTR,DEL,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,-,NaN,NaN,1117.0,ENST00000442250,79100,53,1130

In [89]:
dataMutation.duplicated().sum()

11427

In [90]:
# check if there are null gene length
dataMutation[dataMutation['Gene_Length'].isna()]

Empty DataFrame
Columns: [Tumor_Sample_Barcode, Hugo_Symbol, original_Hugo_Symbol, Chromosome, Start_Position, End_Position, Strand, Variant_Classification, Variant_Type, Reference_Allele, Tumor_Seq_Allele1, Tumor_Seq_Allele2, HGVSc, HGVSp_Short, Protein_position, Transcript_ID, Gene_Length, Mutation_Length, Protein_Length]
Index: []

In [106]:
len(dataMutation)

NameError: name 'dataMutation' is not defined

In [92]:
f = open(data['all_all___mutations'], "w")

In [93]:
f.write("# Merged Data" + "\t "*(dataMutation.shape[1]-1) +"\n")
f.write("# from entry 0 to " + str(len(dataMutation_Giannakis)-1) +": Giannakis" + "\t "*(dataMutation.shape[1]-1) + "\n")
f.write("# from entry " + str(len(dataMutation_Giannakis)) + " to " + str(len(dataMutation_Giannakis)+len(dataMutation_Seshagiri)-1) +": Seshagiri" + "\t "*(dataMutation.shape[1]-1) + "\n")
f.write("# from entry " + str(len(dataMutation_Giannakis)+len(dataMutation_Seshagiri)) + " to " + str(len(dataMutation)-1) +": TCGA" + "\t "*(dataMutation.shape[1]-1) + "\n")
f.write("# " + "\t "*(dataMutation.shape[1]-1) + "\n")

39

In [94]:
dataMutation.to_csv(f, sep="\t", index=False, mode='a')

In [95]:
f.close()
del dataMutation_Giannakis, dataMutation_Seshagiri, dataMutation_TCGA, dataMutation

### Clinical Samples

In [96]:
dataClinicalSample_Giannakis = pd.read_csv(data['Giannakis_all___samples'], sep='\t', engine='python', comment='#')
dataClinicalSample_Seshagiri = pd.read_csv(data['Seshagiri_all___samples'], sep='\t', engine='python', comment='#')
dataClinicalSample_TCGA = pd.read_csv(data['TCGA_all___samples'], sep='\t', engine='python', comment='#')

In [97]:
len(dataClinicalSample_Giannakis), len(dataClinicalSample_Seshagiri), len(dataClinicalSample_TCGA)

(619, 74, 594)

In [98]:
dataClinicalSample = pd.concat([dataClinicalSample_Giannakis, dataClinicalSample_Seshagiri, dataClinicalSample_TCGA], ignore_index=True)

In [99]:
dataClinicalSample

,SAMPLE_ID,PATIENT_ID,TUMOR_STAGE,TUMOR_PURITY,PRIMARY_TUMOR_GRADE,MSI_STATUS,CIMP_CATEGORY,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS,TUMOR_TYPE,TISSUE_SOURCE_SITE,TUMOR_CONTENT,GRADE,TISSUE_PROSPECTIVE_COLLECTION_INDICATOR,TISSUE_RETROSPECTIVE_COLLECTION_INDICATOR,TUMOR_TISSUE_SITE,ANEUPLOIDY_SCORE,SAMPLE_TYPE,MSI_SCORE_MANTIS,MSI_SENSOR_SCORE,TMB_NONSYNONYMOUS
0,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,coadread_dfci_2016_593,coadread_dfci_2016_593,II,NaN,Well-Moderate,NaN,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,coadread_dfci_2016_2269,coadread_dfci_2016_2269,I,60.0,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,coadread_dfci_2016_578,coadread_dfci_2016_578,II,NaN,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,coadread_dfci_2016_3021,coadread_dfci_2016_3021,III,NaN,Well-Moderate,MSI-high,CIMP-high,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,TCGA-SS-A7HO-01,TCGA-SS-A7HO,NaN,NaN,NaN,NaN,NaN,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Matched,Colon Adenocarcinoma,SS,NaN,NaN,No,Yes,Colon,18.0,Primary,0.3318,1.19,4.833333
1283,TCGA-T9-A92H-01,TCGA-T9-A92H,NaN,NaN,NaN,NaN,NaN,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Matched,Colon Adenocarcinoma,T9,NaN,NaN,Yes,No,Colon,11.0,Primary,0.3170,0.40,5.333333
1284,TCGA-WS-AB45-01,TCGA-WS-AB45,NaN,NaN,NaN,NaN,NaN,MACR,Colorectal Adenocarcinoma,Mucinous Adenocarcinoma of the Colon and Rectum,Matched,"Colon Adenocarcinoma, Mucinous Type",WS,NaN,NaN,No,Yes,Colon,7.0,Primary,0.6782,24.48,84.166667
1285,TCGA-5M-AAT5-01,TCGA-5M-AAT5,NaN,NaN,NaN,NaN,NaN,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Matched,Colon Adenocarcinoma,5M,NaN,NaN,NaN,NaN,NaN,10.0,Primary,0.3131,0.35,2.633333
1286,TCGA-5M-AATA-01,TCGA-5M-AATA,NaN,NaN,NaN,NaN,NaN,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Matched,Colon Adenocarcinoma,5M,NaN,NaN,NaN,NaN,NaN,14.0,Primary,0.3123,0.08,2.366667

In [100]:
dataClinicalSample.duplicated().sum()

0

In [101]:
len(dataClinicalSample)

1287

In [102]:
f = open(data['all_all___samples'], "w")

In [103]:
f.write("# Merged Data" + "\t "*(dataClinicalSample.shape[1]-1) +"\n")
f.write("# from entry 0 to " + str(len(dataClinicalSample_Giannakis)-1) +": Giannakis" + "\t "*(dataClinicalSample.shape[1]-1) + "\n")
f.write("# from entry " + str(len(dataClinicalSample_Giannakis)) + " to " + str(len(dataClinicalSample_Giannakis)+len(dataClinicalSample_Seshagiri)-1) +": Seshagiri" + "\t "*(dataClinicalSample.shape[1]-1) + "\n")
f.write("# from entry " + str(len(dataClinicalSample_Giannakis)+len(dataClinicalSample_Seshagiri)) + " to " + str(len(dataClinicalSample)-1) +": TCGA" + "\t "*(dataClinicalSample.shape[1]-1) + "\n")
f.write("# " + "\t "*(dataClinicalSample.shape[1]-1) + "\n")

47

In [104]:
dataClinicalSample.to_csv(f, sep="\t", index=False, mode='a')

In [105]:
f.close()
del dataClinicalSample_Giannakis, dataClinicalSample_Seshagiri, dataClinicalSample_TCGA, dataClinicalSample