In [1]:
import configparser
import os

import pandas as pd
import ydata_profiling as yp

In [ ]:
os.chdir('../')

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
data = configparser.ConfigParser(interpolation=configparser.ExtendedInterpolation())
data.read('data.ini')
data = data['DEFAULT']

## Giannakis

In [4]:
dataMutation_Giannakis = pd.read_csv(data['Giannakis_all___mutations'], sep='\t', comment='#')

In [5]:
dataMutation_Giannakis

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,coadread_dfci_2016_1231,A1BG,A1BG,19,58862793,58862793,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100,8322,1,495
1,coadread_dfci_2016_1231,A1BG,A1BG,19,58862794,58862794,+,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100,8322,1,495
2,coadread_dfci_2016_2269,A1BG,A1BG,19,58862775,58862775,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.892G>A,p.E298K,298.0,ENST00000263100,8322,1,495
3,coadread_dfci_2016_230737,A1BG,A1BG,19,58858744,58858744,+,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100,8322,1,495
4,coadread_dfci_2016_2429,A1BG,A1BG,19,58862934,58862934,+,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100,8322,1,495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277457,coadread_dfci_2016_3263,ZZZ3,ZZZ3,1,78097977,78097977,+,Missense_Mutation,SNP,A,A,G,ENST00000370801.3:c.1063T>C,p.S355P,355.0,ENST00000370801,121004,1,903
277458,coadread_dfci_2016_335135,ZZZ3,ZZZ3,1,78098938,78098938,+,Silent,SNP,C,C,T,ENST00000370801.3:c.102G>A,p.A34=,34.0,ENST00000370801,121004,1,903
277459,coadread_dfci_2016_430,ZZZ3,ZZZ3,1,78098587,78098587,+,Silent,SNP,C,C,T,ENST00000370801.3:c.453G>A,p.V151=,151.0,ENST00000370801,121004,1,903
277460,coadread_dfci_2016_50,ZZZ3,ZZZ3,1,78031395,78031395,+,Missense_Mutation,SNP,C,C,G,ENST00000370801.3:c.2642G>C,p.R881T,881.0,ENST00000370801,121004,1,903
277461,coadread_dfci_2016_613,ZZZ3,ZZZ3,1,78047760,78047760,+,Missense_Mutation,SNP,C,C,T,ENST00000370801.3:c.1696G>A,p.V566I,566.0,ENST00000370801,121004,1,903

In [6]:
dataMutation_Giannakis_report = dataMutation_Giannakis.profile_report(title='Data Mutations Giannakis Report', explorative=True)
dataMutation_Giannakis_report.to_file(data['profilingReports'] + "Giannakis_mutations_profilingReport.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
# dataMutation_Giannakis_report

In [8]:
dataClinical_Giannakis = pd.read_csv(data['Giannakis_all___samples'], sep="\t", comment="#")

In [9]:
dataClinical_Giannakis

,SAMPLE_ID,PATIENT_ID,TUMOR_STAGE,TUMOR_PURITY,PRIMARY_TUMOR_GRADE,MSI_STATUS,CIMP_CATEGORY,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS
0,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
1,coadread_dfci_2016_593,coadread_dfci_2016_593,II,NaN,Well-Moderate,NaN,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
2,coadread_dfci_2016_2269,coadread_dfci_2016_2269,I,60.0,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
3,coadread_dfci_2016_578,coadread_dfci_2016_578,II,NaN,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
4,coadread_dfci_2016_3021,coadread_dfci_2016_3021,III,NaN,Well-Moderate,MSI-high,CIMP-high,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
...,...,...,...,...,...,...,...,...,...,...,...
614,coadread_dfci_2016_283,coadread_dfci_2016_283,NaN,NaN,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
615,coadread_dfci_2016_3242,coadread_dfci_2016_3242,III,33.0,Well-Moderate,NaN,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
616,coadread_dfci_2016_2262,coadread_dfci_2016_2262,NaN,20.0,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
617,coadread_dfci_2016_3512,coadread_dfci_2016_3512,III,33.0,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched
618,coadread_dfci_2016_2997,coadread_dfci_2016_2997,II,55.0,Well-Moderate,MSS,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched

In [10]:
dataClinical_Giannakis_report = dataClinical_Giannakis.profile_report(title='Giannakis Clinical Samples Data Profiling Report')
dataClinical_Giannakis_report.to_file(data['profilingReports'] + "Giannakis_clinicalSamples_profilingReport.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [11]:
# dataClinical_Giannakis_report

In [12]:
# join dataClinical_Giannakis with dataMutation_Giannakis on SAMPLE_ID = Tumor_Sample_Barcode
merged_data = dataClinical_Giannakis.merge(dataMutation_Giannakis, left_on='SAMPLE_ID', right_on='Tumor_Sample_Barcode')
merged_data

,SAMPLE_ID,PATIENT_ID,TUMOR_STAGE,TUMOR_PURITY,PRIMARY_TUMOR_GRADE,MSI_STATUS,CIMP_CATEGORY,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,coadread_dfci_2016_335135,A1CF,A1CF,10,52569687,52569687,+,Missense_Mutation,SNP,C,C,T,ENST00000373993.1:c.1600G>A,p.A534T,534.0,ENST00000373993,86267,1,594
1,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,coadread_dfci_2016_335135,A2M,A2M,12,9227209,9227209,+,Missense_Mutation,SNP,C,C,T,ENST00000318602.7:c.3703G>A,p.V1235M,1235.0,ENST00000318602,48566,1,1474
2,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,coadread_dfci_2016_335135,A2ML1,A2ML1,12,9013508,9013508,+,Missense_Mutation,SNP,C,C,T,ENST00000299698.7:c.3296C>T,p.A1099V,1099.0,ENST00000299698,64530,1,1454
3,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,coadread_dfci_2016_335135,AACS,AACS,12,125621367,125621367,+,Missense_Mutation,SNP,C,C,T,ENST00000316519.6:c.1838C>T,p.A613V,613.0,ENST00000316519,77949,1,672
4,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,coadread_dfci_2016_335135,AAGAB,AAGAB,15,67524206,67524206,+,Nonsense_Mutation,SNP,G,G,A,ENST00000261880.5:c.481C>T,p.R161*,161.0,ENST00000261880,54163,1,315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277457,coadread_dfci_2016_3512,coadread_dfci_2016_3512,III,33.0,Well-Moderate,MSS,CIMP-0/low,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,coadread_dfci_2016_3512,ZAN,ZAN,7,100388611,100388611,+,Missense_Mutation,SNP,G,G,A,ENST00000546292.1:c.7402G>A,p.G2468R,2468.0,ENST00000546292,64171,1,2720
277458,coadread_dfci_2016_2997,coadread_dfci_2016_2997,II,55.0,Well-Moderate,MSS,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,coadread_dfci_2016_2997,ANAPC2,ANAPC2,9,140076216,140076216,+,Missense_Mutation,SNP,G,G,A,ENST00000323927.2:c.1385C>T,p.A462V,462.0,ENST00000323927,13754,1,822
277459,coadread_dfci_2016_2997,coadread_dfci_2016_2997,II,55.0,Well-Moderate,MSS,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,coadread_dfci_2016_2997,PCLO,PCLO,7,82784687,82784687,+,Nonsense_Mutation,SNP,G,G,A,ENST00000333891.9:c.1270C>T,p.Q424*,424.0,ENST00000333891,408918,1,5142
277460,coadread_dfci_2016_2997,coadread_dfci_2016_2997,II,55.0,Well-Moderate,MSS,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,coadread_dfci_2016_2997,TBP,TBP,6,170871070,170871070,+,Silent,SNP,G,G,A,ENST00000230354.6:c.246G>A,p.Q82=,82.0,ENST00000230354,18569,1,339
277461,coadread_dfci_2016_2997,coadread_dfci_2016_2997,II,55.0,Well-Moderate,MSS,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,coadread_dfci_2016_2997,ZMYM4,ZMYM4,1,35858270,35858270,+,Silent,SNP,G,G,A,ENST00000314607.6:c.2751G>A,p.A917=,917.0,ENST00000314607,153092,1,1548

### RAS mutated samples

In [13]:
samples_RAS = pd.Series(merged_data[merged_data['Hugo_Symbol'].isin(['HRAS', 'NRAS', 'KRAS'])]['SAMPLE_ID'].unique())

samples_HRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'HRAS']['SAMPLE_ID'].unique())
samples_NRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'NRAS']['SAMPLE_ID'].unique())
samples_KRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'KRAS']['SAMPLE_ID'].unique())

samples_HRAS_NRAS = pd.Series(samples_HRAS[samples_HRAS.isin(samples_NRAS)].unique())
samples_HRAS_KRAS = pd.Series(samples_HRAS[samples_HRAS.isin(samples_KRAS)].unique())
samples_NRAS_KRAS = pd.Series(samples_NRAS[samples_NRAS.isin(samples_KRAS)].unique())

samples_HRAS_NRAS_KRAS = pd.Series(samples_HRAS[samples_HRAS.isin(samples_NRAS_KRAS)].unique())

In [14]:
print(f"Number of samples with RAS mutations: {samples_RAS.size}")
print(f"Number of samples with HRAS mutations: {samples_HRAS.size}")
print(f"Number of samples with NRAS mutations: {samples_NRAS.size}")
print(f"Number of samples with KRAS mutations: {samples_KRAS.size}")
print(f"Number of patients with HRAS and NRAS mutations: {samples_HRAS_NRAS.size}")
print(f"Number of patients with HRAS and KRAS mutations: {samples_HRAS_KRAS.size}")
print(f"Number of patients with NRAS and KRAS mutations: {samples_NRAS_KRAS.size}")
print(f"Number of patients with HRAS, NRAS and KRAS mutations: {samples_HRAS_NRAS_KRAS.size}")

Number of samples with RAS mutations: 208
Number of samples with HRAS mutations: 8
Number of samples with NRAS mutations: 30
Number of samples with KRAS mutations: 173
Number of patients with HRAS and NRAS mutations: 0
Number of patients with HRAS and KRAS mutations: 0
Number of patients with NRAS and KRAS mutations: 3
Number of patients with HRAS, NRAS and KRAS mutations: 0

In [15]:
dataMutation_Giannakis_RAS = dataMutation_Giannakis[dataMutation_Giannakis['Tumor_Sample_Barcode'].isin(samples_RAS)]
dataClinical_Giannakis_RAS = dataClinical_Giannakis[dataClinical_Giannakis['SAMPLE_ID'].isin(samples_RAS)]
dataMutation_Giannakis_nonRAS = dataMutation_Giannakis[~dataMutation_Giannakis['Tumor_Sample_Barcode'].isin(samples_RAS)]
dataClinical_Giannakis_nonRAS = dataClinical_Giannakis[~dataClinical_Giannakis['SAMPLE_ID'].isin(samples_RAS)]

In [16]:
dataMutation_Giannakis_RAS.to_csv(data['Giannakis_RAS___mutations'], sep='\t', index=False)
dataClinical_Giannakis_RAS.to_csv(data['Giannakis_RAS___samples'], sep='\t', index=False)
dataMutation_Giannakis_nonRAS.to_csv(data['Giannakis_nonRAS___mutations'], sep='\t', index=False)
dataClinical_Giannakis_nonRAS.to_csv(data['Giannakis_nonRAS___samples'], sep='\t', index=False)

In [17]:
del dataMutation_Giannakis, dataMutation_Giannakis_report, dataClinical_Giannakis, dataClinical_Giannakis_report, merged_data, dataMutation_Giannakis_RAS, dataClinical_Giannakis_RAS, dataMutation_Giannakis_nonRAS, dataClinical_Giannakis_nonRAS

## Seshagiri

In [18]:
dataMutation_Seshagiri = pd.read_csv(data['Seshagiri_all___mutations'], sep='\t', comment='#')

In [19]:
dataMutation_Seshagiri

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,587220,A1CF,A1CF,10,52573792,52573792,+,Missense_Mutation,SNP,G,G,A,ENST00000373993.1:c.1172C>T,p.A391V,391.0,ENST00000373993,86267,1,594
1,587220,A4GALT,A4GALT,22,43089044,43089044,+,Missense_Mutation,SNP,G,G,A,ENST00000249005.2:c.914C>T,p.P305L,305.0,ENST00000249005,29178,1,353
2,587220,AARS2,AARS2,6,44272932,44272932,+,Missense_Mutation,SNP,G,G,A,ENST00000244571.4:c.1438C>T,p.R480W,480.0,ENST00000244571,13673,1,985
3,587220,ABCA1,ABCA1,9,107620834,107620834,+,Missense_Mutation,SNP,C,C,T,ENST00000374736.3:c.689G>A,p.R230H,230.0,ENST00000374736,147236,1,2261
4,587220,ABCA12,ABCA12,2,215840638,215840638,+,Missense_Mutation,SNP,A,A,G,ENST00000272895.7:c.5252T>C,p.V1751A,1751.0,ENST00000272895,206886,1,2595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35057,587400,WRNIP1,WRNIP1,6,2766302,2766302,+,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.446C>A,p.A149E,149.0,ENST00000380773,21539,1,665
35058,587400,XKRX,XKRX,X,100183004,100183004,+,Missense_Mutation,SNP,G,G,A,ENST00000372956.2:c.290C>T,p.P97L,97.0,ENST00000372956,15992,1,449
35059,587400,ZNF256,ZNF256,19,58452579,58452579,+,Missense_Mutation,SNP,T,T,G,ENST00000282308.3:c.1597A>C,p.S533R,533.0,ENST00000282308,6843,1,627
35060,587400,ZNF300,ZNF300,5,150275726,150275726,+,Missense_Mutation,SNP,C,C,T,ENST00000274599.5:c.1075G>A,p.G359R,359.0,ENST00000274599,10592,1,604
35061,587400,ZSWIM4,ZSWIM4,19,13923841,13923841,+,Missense_Mutation,SNP,C,C,T,ENST00000254323.2:c.1043C>T,p.P348L,348.0,ENST00000254323,36771,1,989

In [20]:
dataMutation_Seshagiri_report = dataMutation_Seshagiri.profile_report(title='Data Mutations Seshagiri Report', explorative=True)
dataMutation_Seshagiri_report.to_file(data['profilingReports'] + "Seshagiri_mutations_profilingReport.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [21]:
# dataMutation_Seshagiri_report

In [22]:
dataClinical_Seshagiri = pd.read_csv(data['Seshagiri_all___samples'], sep="\t", comment="#")

In [23]:
dataClinical_Seshagiri

,PATIENT_ID,SAMPLE_ID,TUMOR_TYPE,TISSUE_SOURCE_SITE,MSI_STATUS,TUMOR_CONTENT,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS
0,12912,587220,colon,Tumor,MSI,60,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
1,12914,587222,colon,Tumor,MSS,60,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
2,12915,587224,colon,Tumor,MSI,60,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
3,12919,587226,colon,Tumor,MSI,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
4,12926,587228,colon,Tumor,MSI,90,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
...,...,...,...,...,...,...,...,...,...,...
69,34994,587394,colon,Tumor,MSS,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
70,34997,587398,colon,Tumor,MSS,40,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
71,35001,587400,colon,Tumor,MSS,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
72,14962,587236,colon,Tumor,MSS,30,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched
73,32758,587326,colon,Tumor,MSS,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched

In [24]:
dataClinical_Seshagiri_report = dataClinical_Seshagiri.profile_report(title='Seshagiri Clinical Samples Data Profiling Report')
dataClinical_Seshagiri_report.to_file(data['profilingReports'] + "Seshagiri_clinicalSamples_profilingReport.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [25]:
# dataClinical_Seshagiri_report

In [26]:
merged_data = dataClinical_Seshagiri.merge(dataMutation_Seshagiri, left_on='SAMPLE_ID', right_on='Tumor_Sample_Barcode')
merged_data

,PATIENT_ID,SAMPLE_ID,TUMOR_TYPE,TISSUE_SOURCE_SITE,MSI_STATUS,TUMOR_CONTENT,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,12912,587220,colon,Tumor,MSI,60,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched,587220,A1CF,A1CF,10,52573792,52573792,+,Missense_Mutation,SNP,G,G,A,ENST00000373993.1:c.1172C>T,p.A391V,391.0,ENST00000373993,86267,1,594
1,12912,587220,colon,Tumor,MSI,60,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched,587220,A4GALT,A4GALT,22,43089044,43089044,+,Missense_Mutation,SNP,G,G,A,ENST00000249005.2:c.914C>T,p.P305L,305.0,ENST00000249005,29178,1,353
2,12912,587220,colon,Tumor,MSI,60,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched,587220,AARS2,AARS2,6,44272932,44272932,+,Missense_Mutation,SNP,G,G,A,ENST00000244571.4:c.1438C>T,p.R480W,480.0,ENST00000244571,13673,1,985
3,12912,587220,colon,Tumor,MSI,60,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched,587220,ABCA1,ABCA1,9,107620834,107620834,+,Missense_Mutation,SNP,C,C,T,ENST00000374736.3:c.689G>A,p.R230H,230.0,ENST00000374736,147236,1,2261
4,12912,587220,colon,Tumor,MSI,60,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched,587220,ABCA12,ABCA12,2,215840638,215840638,+,Missense_Mutation,SNP,A,A,G,ENST00000272895.7:c.5252T>C,p.V1751A,1751.0,ENST00000272895,206886,1,2595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35057,35001,587400,colon,Tumor,MSS,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched,587400,WRNIP1,WRNIP1,6,2766302,2766302,+,Missense_Mutation,SNP,C,C,A,ENST00000380773.4:c.446C>A,p.A149E,149.0,ENST00000380773,21539,1,665
35058,35001,587400,colon,Tumor,MSS,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched,587400,XKRX,XKRX,X,100183004,100183004,+,Missense_Mutation,SNP,G,G,A,ENST00000372956.2:c.290C>T,p.P97L,97.0,ENST00000372956,15992,1,449
35059,35001,587400,colon,Tumor,MSS,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched,587400,ZNF256,ZNF256,19,58452579,58452579,+,Missense_Mutation,SNP,T,T,G,ENST00000282308.3:c.1597A>C,p.S533R,533.0,ENST00000282308,6843,1,627
35060,35001,587400,colon,Tumor,MSS,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched,587400,ZNF300,ZNF300,5,150275726,150275726,+,Missense_Mutation,SNP,C,C,T,ENST00000274599.5:c.1075G>A,p.G359R,359.0,ENST00000274599,10592,1,604
35061,35001,587400,colon,Tumor,MSS,80,COADREAD,Colorectal Cancer,Colorectal Adenocarcinoma,Matched,587400,ZSWIM4,ZSWIM4,19,13923841,13923841,+,Missense_Mutation,SNP,C,C,T,ENST00000254323.2:c.1043C>T,p.P348L,348.0,ENST00000254323,36771,1,989

### RAS mutated samples

In [27]:
samples_RAS = pd.Series(merged_data[merged_data['Hugo_Symbol'].isin(['HRAS', 'NRAS', 'KRAS'])]['SAMPLE_ID'].unique())

samples_HRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'HRAS']['SAMPLE_ID'].unique())
samples_NRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'NRAS']['SAMPLE_ID'].unique())
samples_KRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'KRAS']['SAMPLE_ID'].unique())

patients_HRAS_NRAS = pd.Series(samples_HRAS[samples_HRAS.isin(samples_NRAS)].unique())
patients_HRAS_KRAS = pd.Series(samples_HRAS[samples_HRAS.isin(samples_KRAS)].unique())
patients_NRAS_KRAS = pd.Series(samples_NRAS[samples_NRAS.isin(samples_KRAS)].unique())

patients_HRAS_NRAS_KRAS = pd.Series(samples_HRAS[samples_HRAS.isin(patients_NRAS_KRAS)].unique())

In [28]:
print(f"Number of samples with RAS mutations: {samples_RAS.size}")
print(f"Number of samples with HRAS mutations: {samples_HRAS.size}")
print(f"Number of samples with NRAS mutations: {samples_NRAS.size}")
print(f"Number of samples with KRAS mutations: {samples_KRAS.size}")
print(f"Number of patients with HRAS and NRAS mutations: {patients_HRAS_NRAS.size}")
print(f"Number of patients with HRAS and KRAS mutations: {patients_HRAS_KRAS.size}")
print(f"Number of patients with NRAS and KRAS mutations: {patients_NRAS_KRAS.size}")
print(f"Number of patients with HRAS, NRAS and KRAS mutations: {patients_HRAS_NRAS_KRAS.size}")

Number of samples with RAS mutations: 39
Number of samples with HRAS mutations: 0
Number of samples with NRAS mutations: 2
Number of samples with KRAS mutations: 37
Number of patients with HRAS and NRAS mutations: 0
Number of patients with HRAS and KRAS mutations: 0
Number of patients with NRAS and KRAS mutations: 0
Number of patients with HRAS, NRAS and KRAS mutations: 0

In [29]:
dataMutation_Seshagiri_RAS = dataMutation_Seshagiri[dataMutation_Seshagiri['Tumor_Sample_Barcode'].isin(samples_RAS)]
dataClinical_Seshagiri_RAS = dataClinical_Seshagiri[dataClinical_Seshagiri['SAMPLE_ID'].isin(samples_RAS)]
dataMutation_Seshagiri_nonRAS = dataMutation_Seshagiri[~dataMutation_Seshagiri['Tumor_Sample_Barcode'].isin(samples_RAS)]
dataClinical_Seshagiri_nonRAS = dataClinical_Seshagiri[~dataClinical_Seshagiri['SAMPLE_ID'].isin(samples_RAS)]

In [30]:
dataMutation_Seshagiri_RAS.to_csv(data['Seshagiri_RAS___mutations'], sep='\t', index=False)
dataClinical_Seshagiri_RAS.to_csv(data['Seshagiri_RAS___samples'], sep='\t', index=False)
dataMutation_Seshagiri_nonRAS.to_csv(data['Seshagiri_nonRAS___mutations'], sep='\t', index=False)
dataClinical_Seshagiri_nonRAS.to_csv(data['Seshagiri_nonRAS___samples'], sep='\t', index=False)

In [31]:
del dataMutation_Seshagiri, dataMutation_Seshagiri_report, dataClinical_Seshagiri, dataClinical_Seshagiri_report, merged_data, dataMutation_Seshagiri_RAS, dataMutation_Seshagiri_nonRAS, dataClinical_Seshagiri_RAS, dataClinical_Seshagiri_nonRAS

## TCGA

In [32]:
dataMutation_TCGA = pd.read_csv(data['TCGA_all___mutations'], sep='\t', comment='#')

In [33]:
dataMutation_TCGA

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,TCGA-AF-2687-01,WDR37,WDR37,10,1130478,1130478,+,Missense_Mutation,SNP,G,G,A,ENST00000263150.4:c.532G>A,p.D178N,178.0,ENST00000263150,82760,1,494
1,TCGA-AF-2687-01,HSPA14,HSPA14,10,14896137,14896137,+,Missense_Mutation,SNP,G,G,A,ENST00000378372.3:c.748G>A,p.D250N,250.0,ENST00000378372,33578,1,509
2,TCGA-AF-2687-01,ARHGAP20,ARHGAP20,11,110450666,110450666,+,Missense_Mutation,SNP,G,G,A,ENST00000260283.4:c.3004C>T,p.P1002S,1002.0,ENST00000260283,136147,1,1191
3,TCGA-AF-2687-01,STT3A,STT3A,11,125478127,125478127,+,Missense_Mutation,SNP,G,G,A,ENST00000392708.4:c.904G>A,p.V302I,302.0,ENST00000392708,33504,1,705
4,TCGA-AF-2687-01,ANO3,ANO3,11,26620415,26620415,+,Missense_Mutation,SNP,G,G,A,ENST00000256737.3:c.1541G>A,p.R514H,514.0,ENST00000256737,474007,1,981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267269,TCGA-WS-AB45-01,TBL1X,TBL1X,X,9661224,9661224,+,Silent,SNP,C,C,T,ENST00000217964.7:c.927C>T,p.D309=,309.0,ENST00000217964,256446,1,577
267270,TCGA-WS-AB45-01,SHROOM2,SHROOM2,X,9863424,9863424,+,Silent,SNP,G,G,A,ENST00000380913.3:c.1476G>A,p.A492=,492.0,ENST00000380913,162988,1,1616
267271,TCGA-WS-AB45-01,PCDH19,PCDH19,X,99662857,99662857,+,Missense_Mutation,SNP,C,C,T,ENST00000373034.4:c.739G>A,p.V247M,247.0,ENST00000373034,118630,1,1148
267272,TCGA-5M-AAT6-01,KRTAP1-1,KRTAP1-3,17,39190708,39197254,+,3'UTR,DEL,GGGGGGCAGGCAGGTACCCTCCACACGGCAGTCTGGGCGGCACCAC...,GGGGGGCAGGCAGGTACCCTCCACACGGCAGTCTGGGCGGCACCAC...,-,NaN,NaN,132.0,ENST00000306271,903,6547,177
267273,TCGA-G4-6588-01,ITGA6,ITGA6,2,173368938,173368990,+,3'UTR,DEL,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,-,NaN,NaN,1117.0,ENST00000442250,79100,53,1130

In [34]:
dataMutation_TCGA_report = dataMutation_TCGA.profile_report(title='Data Mutations TCGA Report', explorative=True)
dataMutation_TCGA_report.to_file(data['profilingReports'] + "TCGA_mutations_profilingReport.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [35]:
# dataMutation_TCGA_report

In [36]:
dataClinical_TCGA = pd.read_csv(data['TCGA_all___samples'], sep="\t", comment="#")

In [37]:
dataClinical_TCGA

,PATIENT_ID,SAMPLE_ID,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,TUMOR_TYPE,GRADE,TISSUE_PROSPECTIVE_COLLECTION_INDICATOR,TISSUE_RETROSPECTIVE_COLLECTION_INDICATOR,TISSUE_SOURCE_SITE,TUMOR_TISSUE_SITE,ANEUPLOIDY_SCORE,SAMPLE_TYPE,MSI_SCORE_MANTIS,MSI_SENSOR_SCORE,SOMATIC_STATUS,TMB_NONSYNONYMOUS
0,TCGA-AF-2687,TCGA-AF-2687-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,24.0,Primary,0.3529,0.08,Matched,3.233333
1,TCGA-AF-2689,TCGA-AF-2689-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,18.0,Primary,0.3486,1.28,Matched,1.733333
2,TCGA-AF-2690,TCGA-AF-2690-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,25.0,Primary,0.3412,0.03,Matched,2.400000
3,TCGA-AF-2691,TCGA-AF-2691-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,11.0,Primary,0.3267,1.16,Matched,2.233333
4,TCGA-AF-2692,TCGA-AF-2692-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectum Adenocarcinoma,NaN,Yes,No,AF,NaN,16.0,Primary,0.3259,1.32,Matched,0.733333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,TCGA-SS-A7HO,TCGA-SS-A7HO-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,No,Yes,SS,Colon,18.0,Primary,0.3318,1.19,Matched,4.833333
590,TCGA-T9-A92H,TCGA-T9-A92H-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,Yes,No,T9,Colon,11.0,Primary,0.3170,0.40,Matched,5.333333
591,TCGA-WS-AB45,TCGA-WS-AB45-01,MACR,Colorectal Adenocarcinoma,Mucinous Adenocarcinoma of the Colon and Rectum,"Colon Adenocarcinoma, Mucinous Type",NaN,No,Yes,WS,Colon,7.0,Primary,0.6782,24.48,Matched,84.166667
592,TCGA-5M-AAT5,TCGA-5M-AAT5-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,NaN,NaN,5M,NaN,10.0,Primary,0.3131,0.35,Matched,2.633333
593,TCGA-5M-AATA,TCGA-5M-AATA-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,NaN,NaN,5M,NaN,14.0,Primary,0.3123,0.08,Matched,2.366667

In [38]:
dataClinical_TCGA_report = dataClinical_TCGA.profile_report(title='TCGA Clinical Samples Data Profiling Report')
dataClinical_TCGA_report.to_file(data['profilingReports'] + "TCGA_clinicalSamples_profilingReport.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [39]:
# dataClinical_TCGA_report

In [40]:
merged_data = dataClinical_TCGA.merge(dataMutation_TCGA, left_on='SAMPLE_ID', right_on='Tumor_Sample_Barcode')
merged_data

,PATIENT_ID,SAMPLE_ID,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,TUMOR_TYPE,GRADE,TISSUE_PROSPECTIVE_COLLECTION_INDICATOR,TISSUE_RETROSPECTIVE_COLLECTION_INDICATOR,TISSUE_SOURCE_SITE,TUMOR_TISSUE_SITE,ANEUPLOIDY_SCORE,SAMPLE_TYPE,MSI_SCORE_MANTIS,MSI_SENSOR_SCORE,SOMATIC_STATUS,TMB_NONSYNONYMOUS,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,TCGA-AF-2687,TCGA-AF-2687-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,24.0,Primary,0.3529,0.08,Matched,3.233333,TCGA-AF-2687-01,WDR37,WDR37,10,1130478,1130478,+,Missense_Mutation,SNP,G,G,A,ENST00000263150.4:c.532G>A,p.D178N,178.0,ENST00000263150,82760,1,494
1,TCGA-AF-2687,TCGA-AF-2687-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,24.0,Primary,0.3529,0.08,Matched,3.233333,TCGA-AF-2687-01,HSPA14,HSPA14,10,14896137,14896137,+,Missense_Mutation,SNP,G,G,A,ENST00000378372.3:c.748G>A,p.D250N,250.0,ENST00000378372,33578,1,509
2,TCGA-AF-2687,TCGA-AF-2687-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,24.0,Primary,0.3529,0.08,Matched,3.233333,TCGA-AF-2687-01,ARHGAP20,ARHGAP20,11,110450666,110450666,+,Missense_Mutation,SNP,G,G,A,ENST00000260283.4:c.3004C>T,p.P1002S,1002.0,ENST00000260283,136147,1,1191
3,TCGA-AF-2687,TCGA-AF-2687-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,24.0,Primary,0.3529,0.08,Matched,3.233333,TCGA-AF-2687-01,STT3A,STT3A,11,125478127,125478127,+,Missense_Mutation,SNP,G,G,A,ENST00000392708.4:c.904G>A,p.V302I,302.0,ENST00000392708,33504,1,705
4,TCGA-AF-2687,TCGA-AF-2687-01,READ,Colorectal Adenocarcinoma,Rectal Adenocarcinoma,Rectal Adenocarcinoma,NaN,Yes,No,AF,Rectum,24.0,Primary,0.3529,0.08,Matched,3.233333,TCGA-AF-2687-01,ANO3,ANO3,11,26620415,26620415,+,Missense_Mutation,SNP,G,G,A,ENST00000256737.3:c.1541G>A,p.R514H,514.0,ENST00000256737,474007,1,981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267269,TCGA-5M-AATA,TCGA-5M-AATA-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,NaN,NaN,5M,NaN,14.0,Primary,0.3123,0.08,Matched,2.366667,TCGA-5M-AATA-01,NUTM2F,NUTM2F,9,97082718,97082718,+,Silent,SNP,C,C,T,ENST00000253262.4:c.1140G>A,p.R380=,380.0,ENST00000253262,13322,1,756
267270,TCGA-5M-AATA,TCGA-5M-AATA-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,NaN,NaN,5M,NaN,14.0,Primary,0.3123,0.08,Matched,2.366667,TCGA-5M-AATA-01,DCAF8L1,DCAF8L1,X,27997790,27997790,+,Missense_Mutation,SNP,G,G,C,ENST00000441525.1:c.1662C>G,p.H554Q,554.0,ENST00000441525,3457,1,600
267271,TCGA-5M-AATA,TCGA-5M-AATA-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,NaN,NaN,5M,NaN,14.0,Primary,0.3123,0.08,Matched,2.366667,TCGA-5M-AATA-01,UBQLN2,UBQLN2,X,56590478,56590478,+,Missense_Mutation,SNP,A,A,C,ENST00000338222.5:c.172A>C,p.K58Q,58.0,ENST00000338222,3418,1,624
267272,TCGA-5M-AATA,TCGA-5M-AATA-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,NaN,NaN,5M,NaN,14.0,Primary,0.3123,0.08,Matched,2.366667,TCGA-5M-AATA-01,NLGN4X,NLGN4X,X,5821582,5821582,+,Silent,SNP,G,G,A,ENST00000275857.6:c.1137C>T,p.F379=,379.0,ENST00000275857,388227,1,816
267273,TCGA-5M-AATA,TCGA-5M-AATA-01,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Colon Adenocarcinoma,NaN,NaN,NaN,5M,NaN,14.0,Primary,0.3123,0.08,Matched,2.366667,TCGA-5M-AATA-01,AR,AR,X,66766356,66766356,+,Silent,SNP,T,T,C,ENST00000374690.3:c.1368T>C,p.G456=,456.0,ENST00000374690,185997,1,920

### RAS mutated samples

In [41]:
samples_RAS = pd.Series(merged_data[merged_data['Hugo_Symbol'].isin(['HRAS', 'NRAS', 'KRAS'])]['SAMPLE_ID'].unique())

samples_HRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'HRAS']['SAMPLE_ID'].unique())
samples_NRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'NRAS']['SAMPLE_ID'].unique())
samples_KRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'KRAS']['SAMPLE_ID'].unique())

patients_HRAS_NRAS = pd.Series(samples_HRAS[samples_HRAS.isin(samples_NRAS)].unique())
patients_HRAS_KRAS = pd.Series(samples_HRAS[samples_HRAS.isin(samples_KRAS)].unique())
patients_NRAS_KRAS = pd.Series(samples_NRAS[samples_NRAS.isin(samples_KRAS)].unique())

patients_HRAS_NRAS_KRAS = pd.Series(samples_HRAS[samples_HRAS.isin(patients_NRAS_KRAS)].unique())

In [42]:
print(f"Number of samples with RAS mutations: {samples_RAS.size}")
print(f"Number of samples with HRAS mutations: {samples_HRAS.size}")
print(f"Number of samples with NRAS mutations: {samples_NRAS.size}")
print(f"Number of samples with KRAS mutations: {samples_KRAS.size}")
print(f"Number of patients with HRAS and NRAS mutations: {patients_HRAS_NRAS.size}")
print(f"Number of patients with HRAS and KRAS mutations: {patients_HRAS_KRAS.size}")
print(f"Number of patients with NRAS and KRAS mutations: {patients_NRAS_KRAS.size}")
print(f"Number of patients with HRAS, NRAS and KRAS mutations: {patients_HRAS_NRAS_KRAS.size}")

Number of samples with RAS mutations: 254
Number of samples with HRAS mutations: 6
Number of samples with NRAS mutations: 35
Number of samples with KRAS mutations: 218
Number of patients with HRAS and NRAS mutations: 0
Number of patients with HRAS and KRAS mutations: 0
Number of patients with NRAS and KRAS mutations: 5
Number of patients with HRAS, NRAS and KRAS mutations: 0

In [43]:
dataMutation_TCGA_RAS = dataMutation_TCGA[dataMutation_TCGA['Tumor_Sample_Barcode'].isin(samples_RAS)]
dataClinical_TCGA_RAS = dataClinical_TCGA[dataClinical_TCGA['SAMPLE_ID'].isin(samples_RAS)]
dataMutation_TCGA_nonRAS = dataMutation_TCGA[~dataMutation_TCGA['Tumor_Sample_Barcode'].isin(samples_RAS)]
dataClinical_TCGA_nonRAS = dataClinical_TCGA[~dataClinical_TCGA['SAMPLE_ID'].isin(samples_RAS)]

In [44]:
dataMutation_TCGA_RAS.to_csv(data['TCGA_RAS___mutations'], sep='\t', index=False)
dataClinical_TCGA_RAS.to_csv(data['TCGA_RAS___samples'], sep='\t', index=False)
dataMutation_TCGA_nonRAS.to_csv(data['TCGA_nonRAS___mutations'], sep='\t', index=False)
dataClinical_TCGA_nonRAS.to_csv(data['TCGA_nonRAS___samples'], sep='\t', index=False)

In [45]:
del dataMutation_TCGA, dataMutation_TCGA_report, dataClinical_TCGA, dataClinical_TCGA_report, merged_data, dataMutation_TCGA_RAS, dataMutation_TCGA_nonRAS, dataClinical_TCGA_RAS, dataClinical_TCGA_nonRAS

## All Datasets

In [46]:
dataMutation = pd.read_csv(data['all_all___mutations'], sep='\t', comment='#')

In [47]:
dataMutation

,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,coadread_dfci_2016_1231,A1BG,A1BG,19,58862793,58862793,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.874G>A,p.G292R,292.0,ENST00000263100,8322,1,495
1,coadread_dfci_2016_1231,A1BG,A1BG,19,58862794,58862794,+,Silent,SNP,G,G,A,ENST00000263100.3:c.873C>T,p.S291=,291.0,ENST00000263100,8322,1,495
2,coadread_dfci_2016_2269,A1BG,A1BG,19,58862775,58862775,+,Missense_Mutation,SNP,C,C,T,ENST00000263100.3:c.892G>A,p.E298K,298.0,ENST00000263100,8322,1,495
3,coadread_dfci_2016_230737,A1BG,A1BG,19,58858744,58858744,+,Silent,SNP,G,G,A,ENST00000263100.3:c.1455C>T,p.S485=,485.0,ENST00000263100,8322,1,495
4,coadread_dfci_2016_2429,A1BG,A1BG,19,58862934,58862934,+,Missense_Mutation,SNP,G,G,A,ENST00000263100.3:c.733C>T,p.R245C,245.0,ENST00000263100,8322,1,495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579793,TCGA-WS-AB45-01,TBL1X,TBL1X,X,9661224,9661224,+,Silent,SNP,C,C,T,ENST00000217964.7:c.927C>T,p.D309=,309.0,ENST00000217964,256446,1,577
579794,TCGA-WS-AB45-01,SHROOM2,SHROOM2,X,9863424,9863424,+,Silent,SNP,G,G,A,ENST00000380913.3:c.1476G>A,p.A492=,492.0,ENST00000380913,162988,1,1616
579795,TCGA-WS-AB45-01,PCDH19,PCDH19,X,99662857,99662857,+,Missense_Mutation,SNP,C,C,T,ENST00000373034.4:c.739G>A,p.V247M,247.0,ENST00000373034,118630,1,1148
579796,TCGA-5M-AAT6-01,KRTAP1-1,KRTAP1-3,17,39190708,39197254,+,3'UTR,DEL,GGGGGGCAGGCAGGTACCCTCCACACGGCAGTCTGGGCGGCACCAC...,GGGGGGCAGGCAGGTACCCTCCACACGGCAGTCTGGGCGGCACCAC...,-,NaN,NaN,132.0,ENST00000306271,903,6547,177
579797,TCGA-G4-6588-01,ITGA6,ITGA6,2,173368938,173368990,+,3'UTR,DEL,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,ACAGTGGATCACAAAGTGGAACGAAAATGAAAGCTACTCATAGCGG...,-,NaN,NaN,1117.0,ENST00000442250,79100,53,1130

In [48]:
dataMutation_report = dataMutation.profile_report(title='All Data Mutations Report', explorative=True)
dataMutation_report.to_file(data['profilingReports'] + "all_mutations_profilingReport.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [49]:
# dataMutation_report

In [50]:
dataClinical = pd.read_csv(data['all_all___samples'], sep="\t", comment="#")

In [51]:
dataClinical_report = dataClinical.profile_report(title='All Clinical Samples Data Profiling Report')
dataClinical_report.to_file(data['profilingReports'] + "all_clinicalSamples_profilingReport.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [52]:
# dataClinical_report

In [53]:
merged_data = dataClinical.merge(dataMutation, left_on='SAMPLE_ID', right_on='Tumor_Sample_Barcode')
merged_data

,SAMPLE_ID,PATIENT_ID,TUMOR_STAGE,TUMOR_PURITY,PRIMARY_TUMOR_GRADE,MSI_STATUS,CIMP_CATEGORY,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS,TUMOR_TYPE,TISSUE_SOURCE_SITE,TUMOR_CONTENT,GRADE,TISSUE_PROSPECTIVE_COLLECTION_INDICATOR,TISSUE_RETROSPECTIVE_COLLECTION_INDICATOR,TUMOR_TISSUE_SITE,ANEUPLOIDY_SCORE,SAMPLE_TYPE,MSI_SCORE_MANTIS,MSI_SENSOR_SCORE,TMB_NONSYNONYMOUS,Tumor_Sample_Barcode,Hugo_Symbol,original_Hugo_Symbol,Chromosome,Start_Position,End_Position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,HGVSc,HGVSp_Short,Protein_position,Transcript_ID,Gene_Length,Mutation_Length,Protein_Length
0,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coadread_dfci_2016_335135,A1CF,A1CF,10,52569687,52569687,+,Missense_Mutation,SNP,C,C,T,ENST00000373993.1:c.1600G>A,p.A534T,534.0,ENST00000373993,86267,1,594
1,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coadread_dfci_2016_335135,A2M,A2M,12,9227209,9227209,+,Missense_Mutation,SNP,C,C,T,ENST00000318602.7:c.3703G>A,p.V1235M,1235.0,ENST00000318602,48566,1,1474
2,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coadread_dfci_2016_335135,A2ML1,A2ML1,12,9013508,9013508,+,Missense_Mutation,SNP,C,C,T,ENST00000299698.7:c.3296C>T,p.A1099V,1099.0,ENST00000299698,64530,1,1454
3,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coadread_dfci_2016_335135,AACS,AACS,12,125621367,125621367,+,Missense_Mutation,SNP,C,C,T,ENST00000316519.6:c.1838C>T,p.A613V,613.0,ENST00000316519,77949,1,672
4,coadread_dfci_2016_335135,coadread_dfci_2016_335135,I,NaN,NaN,NaN,NaN,COADREAD,Colorectal Adenocarcinoma,Colorectal Adenocarcinoma,Matched,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,coadread_dfci_2016_335135,AAGAB,AAGAB,15,67524206,67524206,+,Nonsense_Mutation,SNP,G,G,A,ENST00000261880.5:c.481C>T,p.R161*,161.0,ENST00000261880,54163,1,315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579793,TCGA-5M-AATA-01,TCGA-5M-AATA,NaN,NaN,NaN,NaN,NaN,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Matched,Colon Adenocarcinoma,5M,NaN,NaN,NaN,NaN,NaN,14.0,Primary,0.3123,0.08,2.366667,TCGA-5M-AATA-01,NUTM2F,NUTM2F,9,97082718,97082718,+,Silent,SNP,C,C,T,ENST00000253262.4:c.1140G>A,p.R380=,380.0,ENST00000253262,13322,1,756
579794,TCGA-5M-AATA-01,TCGA-5M-AATA,NaN,NaN,NaN,NaN,NaN,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Matched,Colon Adenocarcinoma,5M,NaN,NaN,NaN,NaN,NaN,14.0,Primary,0.3123,0.08,2.366667,TCGA-5M-AATA-01,DCAF8L1,DCAF8L1,X,27997790,27997790,+,Missense_Mutation,SNP,G,G,C,ENST00000441525.1:c.1662C>G,p.H554Q,554.0,ENST00000441525,3457,1,600
579795,TCGA-5M-AATA-01,TCGA-5M-AATA,NaN,NaN,NaN,NaN,NaN,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Matched,Colon Adenocarcinoma,5M,NaN,NaN,NaN,NaN,NaN,14.0,Primary,0.3123,0.08,2.366667,TCGA-5M-AATA-01,UBQLN2,UBQLN2,X,56590478,56590478,+,Missense_Mutation,SNP,A,A,C,ENST00000338222.5:c.172A>C,p.K58Q,58.0,ENST00000338222,3418,1,624
579796,TCGA-5M-AATA-01,TCGA-5M-AATA,NaN,NaN,NaN,NaN,NaN,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Matched,Colon Adenocarcinoma,5M,NaN,NaN,NaN,NaN,NaN,14.0,Primary,0.3123,0.08,2.366667,TCGA-5M-AATA-01,NLGN4X,NLGN4X,X,5821582,5821582,+,Silent,SNP,G,G,A,ENST00000275857.6:c.1137C>T,p.F379=,379.0,ENST00000275857,388227,1,816
579797,TCGA-5M-AATA-01,TCGA-5M-AATA,NaN,NaN,NaN,NaN,NaN,COAD,Colorectal Adenocarcinoma,Colon Adenocarcinoma,Matched,Colon Adenocarcinoma,5M,NaN,NaN,NaN,NaN,NaN,14.0,Primary,0.3123,0.08,2.366667,TCGA-5M-AATA-01,AR,AR,X,66766356,66766356,+,Silent,SNP,T,T,C,ENST00000374690.3:c.1368T>C,p.G456=,456.0,ENST00000374690,185997,1,920

### RAS mutated samples

In [54]:
samples_RAS = pd.Series(merged_data[merged_data['Hugo_Symbol'].isin(['HRAS', 'NRAS', 'KRAS'])]['SAMPLE_ID'].unique())

samples_HRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'HRAS']['SAMPLE_ID'].unique())
samples_NRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'NRAS']['SAMPLE_ID'].unique())
samples_KRAS = pd.Series(merged_data[merged_data['Hugo_Symbol'] == 'KRAS']['SAMPLE_ID'].unique())

patients_HRAS_NRAS = pd.Series(samples_HRAS[samples_HRAS.isin(samples_NRAS)].unique())
patients_HRAS_KRAS = pd.Series(samples_HRAS[samples_HRAS.isin(samples_KRAS)].unique())
patients_NRAS_KRAS = pd.Series(samples_NRAS[samples_NRAS.isin(samples_KRAS)].unique())

patients_HRAS_NRAS_KRAS = pd.Series(samples_HRAS[samples_HRAS.isin(patients_NRAS_KRAS)].unique())

In [55]:
print(f"Number of samples with RAS mutations: {samples_RAS.size}")
print(f"Number of samples with HRAS mutations: {samples_HRAS.size}")
print(f"Number of samples with NRAS mutations: {samples_NRAS.size}")
print(f"Number of samples with KRAS mutations: {samples_KRAS.size}")
print(f"Number of patients with HRAS and NRAS mutations: {patients_HRAS_NRAS.size}")
print(f"Number of patients with HRAS and KRAS mutations: {patients_HRAS_KRAS.size}")
print(f"Number of patients with NRAS and KRAS mutations: {patients_NRAS_KRAS.size}")
print(f"Number of patients with HRAS, NRAS and KRAS mutations: {patients_HRAS_NRAS_KRAS.size}")

Number of samples with RAS mutations: 501
Number of samples with HRAS mutations: 14
Number of samples with NRAS mutations: 67
Number of samples with KRAS mutations: 428
Number of patients with HRAS and NRAS mutations: 0
Number of patients with HRAS and KRAS mutations: 0
Number of patients with NRAS and KRAS mutations: 8
Number of patients with HRAS, NRAS and KRAS mutations: 0

In [56]:
dataMutation_RAS = dataMutation[dataMutation['Tumor_Sample_Barcode'].isin(samples_RAS)]
dataClinical_RAS = dataClinical[dataClinical['SAMPLE_ID'].isin(samples_RAS)]
dataMutation_nonRAS = dataMutation[~dataMutation['Tumor_Sample_Barcode'].isin(samples_RAS)]
dataClinical_nonRAS = dataClinical[~dataClinical['SAMPLE_ID'].isin(samples_RAS)]

In [58]:
dataMutation_RAS.to_csv(data['all_RAS___mutations'], sep='\t', index=False)
dataClinical_RAS.to_csv(data['all_RAS___samples'], sep='\t', index=False)
dataMutation_nonRAS.to_csv(data['all_nonRAS___mutations'], sep='\t', index=False)
dataClinical_nonRAS.to_csv(data['all_nonRAS___samples'], sep='\t', index=False)

In [59]:
del dataMutation, dataMutation_report, dataClinical, dataClinical_report, merged_data, dataMutation_RAS, dataMutation_nonRAS, dataClinical_RAS, dataClinical_nonRAS